// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: acl.proto

/* eslint-disable */
import { SocketAddr } from "./common";

export const protobufPackage = "acl";

/** Enhanced protocol enum with more granular options */
export enum Protocol {
  Unspecified = 0,
  TCP = 1,
  UDP = 2,
  ICMP = 3,
  ICMPv6 = 4,
  Any = 5,
  UNRECOGNIZED = -1,
}

export function protocolFromJSON(object: any): Protocol {
  switch (object) {
    case 0:
    case "Unspecified":
      return Protocol.Unspecified;
    case 1:
    case "TCP":
      return Protocol.TCP;
    case 2:
    case "UDP":
      return Protocol.UDP;
    case 3:
    case "ICMP":
      return Protocol.ICMP;
    case 4:
    case "ICMPv6":
      return Protocol.ICMPv6;
    case 5:
    case "Any":
      return Protocol.Any;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Protocol.UNRECOGNIZED;
  }
}

export function protocolToJSON(object: Protocol): string {
  switch (object) {
    case Protocol.Unspecified:
      return "Unspecified";
    case Protocol.TCP:
      return "TCP";
    case Protocol.UDP:
      return "UDP";
    case Protocol.ICMP:
      return "ICMP";
    case Protocol.ICMPv6:
      return "ICMPv6";
    case Protocol.Any:
      return "Any";
    case Protocol.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Action {
  Noop = 0,
  Allow = 1,
  /** Drop - Silent drop (no response) */
  Drop = 2,
  UNRECOGNIZED = -1,
}

export function actionFromJSON(object: any): Action {
  switch (object) {
    case 0:
    case "Noop":
      return Action.Noop;
    case 1:
    case "Allow":
      return Action.Allow;
    case 2:
    case "Drop":
      return Action.Drop;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Action.UNRECOGNIZED;
  }
}

export function actionToJSON(object: Action): string {
  switch (object) {
    case Action.Noop:
      return "Noop";
    case Action.Allow:
      return "Allow";
    case Action.Drop:
      return "Drop";
    case Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ChainType {
  UnspecifiedChain = 0,
  /** Inbound - send to this node */
  Inbound = 1,
  /** Outbound - send from this node */
  Outbound = 2,
  /** Forward - subnet proxy */
  Forward = 3,
  UNRECOGNIZED = -1,
}

export function chainTypeFromJSON(object: any): ChainType {
  switch (object) {
    case 0:
    case "UnspecifiedChain":
      return ChainType.UnspecifiedChain;
    case 1:
    case "Inbound":
      return ChainType.Inbound;
    case 2:
    case "Outbound":
      return ChainType.Outbound;
    case 3:
    case "Forward":
      return ChainType.Forward;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChainType.UNRECOGNIZED;
  }
}

export function chainTypeToJSON(object: ChainType): string {
  switch (object) {
    case ChainType.UnspecifiedChain:
      return "UnspecifiedChain";
    case ChainType.Inbound:
      return "Inbound";
    case ChainType.Outbound:
      return "Outbound";
    case ChainType.Forward:
      return "Forward";
    case ChainType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ConnState {
  New = 0,
  Established = 1,
  Related = 2,
  Invalid = 3,
  UNRECOGNIZED = -1,
}

export function connStateFromJSON(object: any): ConnState {
  switch (object) {
    case 0:
    case "New":
      return ConnState.New;
    case 1:
    case "Established":
      return ConnState.Established;
    case 2:
    case "Related":
      return ConnState.Related;
    case 3:
    case "Invalid":
      return ConnState.Invalid;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConnState.UNRECOGNIZED;
  }
}

export function connStateToJSON(object: ConnState): string {
  switch (object) {
    case ConnState.New:
      return "New";
    case ConnState.Established:
      return "Established";
    case ConnState.Related:
      return "Related";
    case ConnState.Invalid:
      return "Invalid";
    case ConnState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Time-based access control */
export interface TimeWindow {
  /** Days of week: 0=Sunday, 1=Monday, ..., 6=Saturday */
  days_of_week: number[];
  /** Time in minutes from midnight (0-1439) */
  start_time: number;
  end_time: number;
  /** Timezone offset in minutes from UTC */
  timezone_offset: number;
}

/** Enhanced rule with priority and metadata */
export interface Rule {
  /** Rule identification and metadata */
  name: string;
  /** Rule description */
  description: string;
  /** Higher number = higher priority (0-65535) */
  priority: number;
  /** Rule enable/disabled state */
  enabled: boolean;
  /** Core matching criteria */
  protocol: Protocol;
  ports: string[];
  /** Source IP ranges */
  source_ips: string[];
  /** Destination IP ranges */
  destination_ips: string[];
  /** Enhanced matching criteria */
  source_ports: string[];
  /** Action and logging */
  action: Action;
  /** Rate limiting (packets per second) */
  rate_limit: number;
  /** Burst allowance */
  burst_limit: number;
  /** Connection tracking */
  stateful: boolean;
  /** Group matching criteria */
  source_groups: string[];
  destination_groups: string[];
}

/** Rule chain with metadata and optimization hints */
export interface Chain {
  /** Chain identification */
  name: string;
  chain_type: ChainType;
  /** Chain description */
  description: string;
  /** Chain enable/disabled state */
  enabled: boolean;
  /** Rules in priority order (highest priority first) */
  rules: Rule[];
  /** Default action when no rules match */
  default_action: Action;
}

export interface GroupInfo {
  declares: GroupIdentity[];
  members: string[];
}

export interface GroupIdentity {
  group_name: string;
  group_secret: string;
}

export interface AclV1 {
  chains: Chain[];
  group: GroupInfo | undefined;
}

/** Connection tracking entry for stateful ACLs */
export interface ConnTrackEntry {
  src_addr: SocketAddr | undefined;
  dst_addr:
    | SocketAddr
    | undefined;
  /** IP protocol number (e.g., 6 = TCP, 17 = UDP) */
  protocol: Protocol;
  state: ConnState;
  /** Unix timestamp (seconds) */
  created_at: number;
  /** Unix timestamp (seconds) */
  last_seen: number;
  packet_count: number;
  byte_count: number;
}

/** Top-level ACL configuration */
export interface Acl {
  acl_v1: AclV1 | undefined;
}

export interface StatItem {
  packet_count: number;
  byte_count: number;
}

export interface RuleStats {
  rule: Rule | undefined;
  stat: StatItem | undefined;
}

export interface AclStats {
  rules: RuleStats[];
  conn_track: ConnTrackEntry[];
  global: { [key: string]: number };
}

export interface AclStats_GlobalEntry {
  key: string;
  value: number;
}

function createBaseTimeWindow(): TimeWindow {
  return { days_of_week: [], start_time: 0, end_time: 0, timezone_offset: 0 };
}

export const TimeWindow: MessageFns<TimeWindow> = {
  fromJSON(object: any): TimeWindow {
    return {
      days_of_week: globalThis.Array.isArray(object?.daysOfWeek)
        ? object.daysOfWeek.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.days_of_week)
        ? object.days_of_week.map((e: any) => globalThis.Number(e))
        : [],
      start_time: isSet(object.startTime)
        ? globalThis.Number(object.startTime)
        : isSet(object.start_time)
        ? globalThis.Number(object.start_time)
        : 0,
      end_time: isSet(object.endTime)
        ? globalThis.Number(object.endTime)
        : isSet(object.end_time)
        ? globalThis.Number(object.end_time)
        : 0,
      timezone_offset: isSet(object.timezoneOffset)
        ? globalThis.Number(object.timezoneOffset)
        : isSet(object.timezone_offset)
        ? globalThis.Number(object.timezone_offset)
        : 0,
    };
  },

  toJSON(message: TimeWindow): unknown {
    const obj: any = {};
    if (message.days_of_week?.length) {
      obj.daysOfWeek = message.days_of_week.map((e) => Math.round(e));
    }
    if (message.start_time !== 0) {
      obj.startTime = Math.round(message.start_time);
    }
    if (message.end_time !== 0) {
      obj.endTime = Math.round(message.end_time);
    }
    if (message.timezone_offset !== 0) {
      obj.timezoneOffset = Math.round(message.timezone_offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TimeWindow>, I>>(base?: I): TimeWindow {
    return TimeWindow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TimeWindow>, I>>(object: I): TimeWindow {
    const message = createBaseTimeWindow();
    message.days_of_week = object.days_of_week?.map((e) => e) || [];
    message.start_time = object.start_time ?? 0;
    message.end_time = object.end_time ?? 0;
    message.timezone_offset = object.timezone_offset ?? 0;
    return message;
  },
};

function createBaseRule(): Rule {
  return {
    name: "",
    description: "",
    priority: 0,
    enabled: false,
    protocol: 0,
    ports: [],
    source_ips: [],
    destination_ips: [],
    source_ports: [],
    action: 0,
    rate_limit: 0,
    burst_limit: 0,
    stateful: false,
    source_groups: [],
    destination_groups: [],
  };
}

export const Rule: MessageFns<Rule> = {
  fromJSON(object: any): Rule {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
      ports: globalThis.Array.isArray(object?.ports) ? object.ports.map((e: any) => globalThis.String(e)) : [],
      source_ips: globalThis.Array.isArray(object?.sourceIps)
        ? object.sourceIps.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.source_ips)
        ? object.source_ips.map((e: any) => globalThis.String(e))
        : [],
      destination_ips: globalThis.Array.isArray(object?.destinationIps)
        ? object.destinationIps.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.destination_ips)
        ? object.destination_ips.map((e: any) => globalThis.String(e))
        : [],
      source_ports: globalThis.Array.isArray(object?.sourcePorts)
        ? object.sourcePorts.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.source_ports)
        ? object.source_ports.map((e: any) => globalThis.String(e))
        : [],
      action: isSet(object.action) ? actionFromJSON(object.action) : 0,
      rate_limit: isSet(object.rateLimit)
        ? globalThis.Number(object.rateLimit)
        : isSet(object.rate_limit)
        ? globalThis.Number(object.rate_limit)
        : 0,
      burst_limit: isSet(object.burstLimit)
        ? globalThis.Number(object.burstLimit)
        : isSet(object.burst_limit)
        ? globalThis.Number(object.burst_limit)
        : 0,
      stateful: isSet(object.stateful) ? globalThis.Boolean(object.stateful) : false,
      source_groups: globalThis.Array.isArray(object?.sourceGroups)
        ? object.sourceGroups.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.source_groups)
        ? object.source_groups.map((e: any) => globalThis.String(e))
        : [],
      destination_groups: globalThis.Array.isArray(object?.destinationGroups)
        ? object.destinationGroups.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.destination_groups)
        ? object.destination_groups.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Rule): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.priority !== 0) {
      obj.priority = Math.round(message.priority);
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    if (message.ports?.length) {
      obj.ports = message.ports;
    }
    if (message.source_ips?.length) {
      obj.sourceIps = message.source_ips;
    }
    if (message.destination_ips?.length) {
      obj.destinationIps = message.destination_ips;
    }
    if (message.source_ports?.length) {
      obj.sourcePorts = message.source_ports;
    }
    if (message.action !== 0) {
      obj.action = actionToJSON(message.action);
    }
    if (message.rate_limit !== 0) {
      obj.rateLimit = Math.round(message.rate_limit);
    }
    if (message.burst_limit !== 0) {
      obj.burstLimit = Math.round(message.burst_limit);
    }
    if (message.stateful !== false) {
      obj.stateful = message.stateful;
    }
    if (message.source_groups?.length) {
      obj.sourceGroups = message.source_groups;
    }
    if (message.destination_groups?.length) {
      obj.destinationGroups = message.destination_groups;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Rule>, I>>(base?: I): Rule {
    return Rule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Rule>, I>>(object: I): Rule {
    const message = createBaseRule();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.priority = object.priority ?? 0;
    message.enabled = object.enabled ?? false;
    message.protocol = object.protocol ?? 0;
    message.ports = object.ports?.map((e) => e) || [];
    message.source_ips = object.source_ips?.map((e) => e) || [];
    message.destination_ips = object.destination_ips?.map((e) => e) || [];
    message.source_ports = object.source_ports?.map((e) => e) || [];
    message.action = object.action ?? 0;
    message.rate_limit = object.rate_limit ?? 0;
    message.burst_limit = object.burst_limit ?? 0;
    message.stateful = object.stateful ?? false;
    message.source_groups = object.source_groups?.map((e) => e) || [];
    message.destination_groups = object.destination_groups?.map((e) => e) || [];
    return message;
  },
};

function createBaseChain(): Chain {
  return { name: "", chain_type: 0, description: "", enabled: false, rules: [], default_action: 0 };
}

export const Chain: MessageFns<Chain> = {
  fromJSON(object: any): Chain {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      chain_type: isSet(object.chainType)
        ? chainTypeFromJSON(object.chainType)
        : isSet(object.chain_type)
        ? chainTypeFromJSON(object.chain_type)
        : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      rules: globalThis.Array.isArray(object?.rules)
        ? object.rules.map((e: any) => Rule.fromJSON(e))
        : [],
      default_action: isSet(object.defaultAction)
        ? actionFromJSON(object.defaultAction)
        : isSet(object.default_action)
        ? actionFromJSON(object.default_action)
        : 0,
    };
  },

  toJSON(message: Chain): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.chain_type !== 0) {
      obj.chainType = chainTypeToJSON(message.chain_type);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.rules?.length) {
      obj.rules = message.rules.map((e) => Rule.toJSON(e));
    }
    if (message.default_action !== 0) {
      obj.defaultAction = actionToJSON(message.default_action);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Chain>, I>>(base?: I): Chain {
    return Chain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Chain>, I>>(object: I): Chain {
    const message = createBaseChain();
    message.name = object.name ?? "";
    message.chain_type = object.chain_type ?? 0;
    message.description = object.description ?? "";
    message.enabled = object.enabled ?? false;
    message.rules = object.rules?.map((e) => Rule.fromPartial(e)) || [];
    message.default_action = object.default_action ?? 0;
    return message;
  },
};

function createBaseGroupInfo(): GroupInfo {
  return { declares: [], members: [] };
}

export const GroupInfo: MessageFns<GroupInfo> = {
  fromJSON(object: any): GroupInfo {
    return {
      declares: globalThis.Array.isArray(object?.declares)
        ? object.declares.map((e: any) => GroupIdentity.fromJSON(e))
        : [],
      members: globalThis.Array.isArray(object?.members)
        ? object.members.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: GroupInfo): unknown {
    const obj: any = {};
    if (message.declares?.length) {
      obj.declares = message.declares.map((e) => GroupIdentity.toJSON(e));
    }
    if (message.members?.length) {
      obj.members = message.members;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupInfo>, I>>(base?: I): GroupInfo {
    return GroupInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupInfo>, I>>(object: I): GroupInfo {
    const message = createBaseGroupInfo();
    message.declares = object.declares?.map((e) => GroupIdentity.fromPartial(e)) || [];
    message.members = object.members?.map((e) => e) || [];
    return message;
  },
};

function createBaseGroupIdentity(): GroupIdentity {
  return { group_name: "", group_secret: "" };
}

export const GroupIdentity: MessageFns<GroupIdentity> = {
  fromJSON(object: any): GroupIdentity {
    return {
      group_name: isSet(object.groupName)
        ? globalThis.String(object.groupName)
        : isSet(object.group_name)
        ? globalThis.String(object.group_name)
        : "",
      group_secret: isSet(object.groupSecret)
        ? globalThis.String(object.groupSecret)
        : isSet(object.group_secret)
        ? globalThis.String(object.group_secret)
        : "",
    };
  },

  toJSON(message: GroupIdentity): unknown {
    const obj: any = {};
    if (message.group_name !== "") {
      obj.groupName = message.group_name;
    }
    if (message.group_secret !== "") {
      obj.groupSecret = message.group_secret;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupIdentity>, I>>(base?: I): GroupIdentity {
    return GroupIdentity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupIdentity>, I>>(object: I): GroupIdentity {
    const message = createBaseGroupIdentity();
    message.group_name = object.group_name ?? "";
    message.group_secret = object.group_secret ?? "";
    return message;
  },
};

function createBaseAclV1(): AclV1 {
  return { chains: [], group: undefined };
}

export const AclV1: MessageFns<AclV1> = {
  fromJSON(object: any): AclV1 {
    return {
      chains: globalThis.Array.isArray(object?.chains) ? object.chains.map((e: any) => Chain.fromJSON(e)) : [],
      group: isSet(object.group) ? GroupInfo.fromJSON(object.group) : undefined,
    };
  },

  toJSON(message: AclV1): unknown {
    const obj: any = {};
    if (message.chains?.length) {
      obj.chains = message.chains.map((e) => Chain.toJSON(e));
    }
    if (message.group !== undefined) {
      obj.group = GroupInfo.toJSON(message.group);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AclV1>, I>>(base?: I): AclV1 {
    return AclV1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AclV1>, I>>(object: I): AclV1 {
    const message = createBaseAclV1();
    message.chains = object.chains?.map((e) => Chain.fromPartial(e)) || [];
    message.group = (object.group !== undefined && object.group !== null)
      ? GroupInfo.fromPartial(object.group)
      : undefined;
    return message;
  },
};

function createBaseConnTrackEntry(): ConnTrackEntry {
  return {
    src_addr: undefined,
    dst_addr: undefined,
    protocol: 0,
    state: 0,
    created_at: 0,
    last_seen: 0,
    packet_count: 0,
    byte_count: 0,
  };
}

export const ConnTrackEntry: MessageFns<ConnTrackEntry> = {
  fromJSON(object: any): ConnTrackEntry {
    return {
      src_addr: isSet(object.srcAddr)
        ? SocketAddr.fromJSON(object.srcAddr)
        : isSet(object.src_addr)
        ? SocketAddr.fromJSON(object.src_addr)
        : undefined,
      dst_addr: isSet(object.dstAddr)
        ? SocketAddr.fromJSON(object.dstAddr)
        : isSet(object.dst_addr)
        ? SocketAddr.fromJSON(object.dst_addr)
        : undefined,
      protocol: isSet(object.protocol) ? protocolFromJSON(object.protocol) : 0,
      state: isSet(object.state) ? connStateFromJSON(object.state) : 0,
      created_at: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      last_seen: isSet(object.lastSeen)
        ? globalThis.Number(object.lastSeen)
        : isSet(object.last_seen)
        ? globalThis.Number(object.last_seen)
        : 0,
      packet_count: isSet(object.packetCount)
        ? globalThis.Number(object.packetCount)
        : isSet(object.packet_count)
        ? globalThis.Number(object.packet_count)
        : 0,
      byte_count: isSet(object.byteCount)
        ? globalThis.Number(object.byteCount)
        : isSet(object.byte_count)
        ? globalThis.Number(object.byte_count)
        : 0,
    };
  },

  toJSON(message: ConnTrackEntry): unknown {
    const obj: any = {};
    if (message.src_addr !== undefined) {
      obj.srcAddr = SocketAddr.toJSON(message.src_addr);
    }
    if (message.dst_addr !== undefined) {
      obj.dstAddr = SocketAddr.toJSON(message.dst_addr);
    }
    if (message.protocol !== 0) {
      obj.protocol = protocolToJSON(message.protocol);
    }
    if (message.state !== 0) {
      obj.state = connStateToJSON(message.state);
    }
    if (message.created_at !== 0) {
      obj.createdAt = Math.round(message.created_at);
    }
    if (message.last_seen !== 0) {
      obj.lastSeen = Math.round(message.last_seen);
    }
    if (message.packet_count !== 0) {
      obj.packetCount = Math.round(message.packet_count);
    }
    if (message.byte_count !== 0) {
      obj.byteCount = Math.round(message.byte_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnTrackEntry>, I>>(base?: I): ConnTrackEntry {
    return ConnTrackEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnTrackEntry>, I>>(object: I): ConnTrackEntry {
    const message = createBaseConnTrackEntry();
    message.src_addr = (object.src_addr !== undefined && object.src_addr !== null)
      ? SocketAddr.fromPartial(object.src_addr)
      : undefined;
    message.dst_addr = (object.dst_addr !== undefined && object.dst_addr !== null)
      ? SocketAddr.fromPartial(object.dst_addr)
      : undefined;
    message.protocol = object.protocol ?? 0;
    message.state = object.state ?? 0;
    message.created_at = object.created_at ?? 0;
    message.last_seen = object.last_seen ?? 0;
    message.packet_count = object.packet_count ?? 0;
    message.byte_count = object.byte_count ?? 0;
    return message;
  },
};

function createBaseAcl(): Acl {
  return { acl_v1: undefined };
}

export const Acl: MessageFns<Acl> = {
  fromJSON(object: any): Acl {
    return {
      acl_v1: isSet(object.aclV1)
        ? AclV1.fromJSON(object.aclV1)
        : isSet(object.acl_v1)
        ? AclV1.fromJSON(object.acl_v1)
        : undefined,
    };
  },

  toJSON(message: Acl): unknown {
    const obj: any = {};
    if (message.acl_v1 !== undefined) {
      obj.aclV1 = AclV1.toJSON(message.acl_v1);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Acl>, I>>(base?: I): Acl {
    return Acl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Acl>, I>>(object: I): Acl {
    const message = createBaseAcl();
    message.acl_v1 = (object.acl_v1 !== undefined && object.acl_v1 !== null)
      ? AclV1.fromPartial(object.acl_v1)
      : undefined;
    return message;
  },
};

function createBaseStatItem(): StatItem {
  return { packet_count: 0, byte_count: 0 };
}

export const StatItem: MessageFns<StatItem> = {
  fromJSON(object: any): StatItem {
    return {
      packet_count: isSet(object.packetCount)
        ? globalThis.Number(object.packetCount)
        : isSet(object.packet_count)
        ? globalThis.Number(object.packet_count)
        : 0,
      byte_count: isSet(object.byteCount)
        ? globalThis.Number(object.byteCount)
        : isSet(object.byte_count)
        ? globalThis.Number(object.byte_count)
        : 0,
    };
  },

  toJSON(message: StatItem): unknown {
    const obj: any = {};
    if (message.packet_count !== 0) {
      obj.packetCount = Math.round(message.packet_count);
    }
    if (message.byte_count !== 0) {
      obj.byteCount = Math.round(message.byte_count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatItem>, I>>(base?: I): StatItem {
    return StatItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatItem>, I>>(object: I): StatItem {
    const message = createBaseStatItem();
    message.packet_count = object.packet_count ?? 0;
    message.byte_count = object.byte_count ?? 0;
    return message;
  },
};

function createBaseRuleStats(): RuleStats {
  return { rule: undefined, stat: undefined };
}

export const RuleStats: MessageFns<RuleStats> = {
  fromJSON(object: any): RuleStats {
    return {
      rule: isSet(object.rule) ? Rule.fromJSON(object.rule) : undefined,
      stat: isSet(object.stat) ? StatItem.fromJSON(object.stat) : undefined,
    };
  },

  toJSON(message: RuleStats): unknown {
    const obj: any = {};
    if (message.rule !== undefined) {
      obj.rule = Rule.toJSON(message.rule);
    }
    if (message.stat !== undefined) {
      obj.stat = StatItem.toJSON(message.stat);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RuleStats>, I>>(base?: I): RuleStats {
    return RuleStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RuleStats>, I>>(object: I): RuleStats {
    const message = createBaseRuleStats();
    message.rule = (object.rule !== undefined && object.rule !== null) ? Rule.fromPartial(object.rule) : undefined;
    message.stat = (object.stat !== undefined && object.stat !== null) ? StatItem.fromPartial(object.stat) : undefined;
    return message;
  },
};

function createBaseAclStats(): AclStats {
  return { rules: [], conn_track: [], global: {} };
}

export const AclStats: MessageFns<AclStats> = {
  fromJSON(object: any): AclStats {
    return {
      rules: globalThis.Array.isArray(object?.rules) ? object.rules.map((e: any) => RuleStats.fromJSON(e)) : [],
      conn_track: globalThis.Array.isArray(object?.connTrack)
        ? object.connTrack.map((e: any) => ConnTrackEntry.fromJSON(e))
        : globalThis.Array.isArray(object?.conn_track)
        ? object.conn_track.map((e: any) => ConnTrackEntry.fromJSON(e))
        : [],
      global: isObject(object.global)
        ? (globalThis.Object.entries(object.global) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: AclStats): unknown {
    const obj: any = {};
    if (message.rules?.length) {
      obj.rules = message.rules.map((e) => RuleStats.toJSON(e));
    }
    if (message.conn_track?.length) {
      obj.connTrack = message.conn_track.map((e) => ConnTrackEntry.toJSON(e));
    }
    if (message.global) {
      const entries = globalThis.Object.entries(message.global) as [string, number][];
      if (entries.length > 0) {
        obj.global = {};
        entries.forEach(([k, v]) => {
          obj.global[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AclStats>, I>>(base?: I): AclStats {
    return AclStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AclStats>, I>>(object: I): AclStats {
    const message = createBaseAclStats();
    message.rules = object.rules?.map((e) => RuleStats.fromPartial(e)) || [];
    message.conn_track = object.conn_track?.map((e) => ConnTrackEntry.fromPartial(e)) || [];
    message.global = (globalThis.Object.entries(object.global ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseAclStats_GlobalEntry(): AclStats_GlobalEntry {
  return { key: "", value: 0 };
}

export const AclStats_GlobalEntry: MessageFns<AclStats_GlobalEntry> = {
  fromJSON(object: any): AclStats_GlobalEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: AclStats_GlobalEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AclStats_GlobalEntry>, I>>(base?: I): AclStats_GlobalEntry {
    return AclStats_GlobalEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AclStats_GlobalEntry>, I>>(object: I): AclStats_GlobalEntry {
    const message = createBaseAclStats_GlobalEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
