// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api_instance.proto

/* eslint-disable */
import { AclStats } from "./acl";
import {
  Ipv4Inet,
  Ipv6Inet,
  PeerFeatureFlag,
  PortForwardConfigPb,
  SocketAddr,
  StunInfo,
  TunnelInfo,
  Url,
  UUID,
} from "./common";
import { GetIpListResponse, RouteForeignNetworkSummary } from "./peer_rpc";

export const protobufPackage = "api.instance";

export enum ConnectorStatus {
  CONNECTED = 0,
  DISCONNECTED = 1,
  CONNECTING = 2,
  UNRECOGNIZED = -1,
}

export function connectorStatusFromJSON(object: any): ConnectorStatus {
  switch (object) {
    case 0:
    case "CONNECTED":
      return ConnectorStatus.CONNECTED;
    case 1:
    case "DISCONNECTED":
      return ConnectorStatus.DISCONNECTED;
    case 2:
    case "CONNECTING":
      return ConnectorStatus.CONNECTING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConnectorStatus.UNRECOGNIZED;
  }
}

export function connectorStatusToJSON(object: ConnectorStatus): string {
  switch (object) {
    case ConnectorStatus.CONNECTED:
      return "CONNECTED";
    case ConnectorStatus.DISCONNECTED:
      return "DISCONNECTED";
    case ConnectorStatus.CONNECTING:
      return "CONNECTING";
    case ConnectorStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TcpProxyEntryTransportType {
  TCP = 0,
  KCP = 1,
  QUIC = 2,
  UNRECOGNIZED = -1,
}

export function tcpProxyEntryTransportTypeFromJSON(object: any): TcpProxyEntryTransportType {
  switch (object) {
    case 0:
    case "TCP":
      return TcpProxyEntryTransportType.TCP;
    case 1:
    case "KCP":
      return TcpProxyEntryTransportType.KCP;
    case 2:
    case "QUIC":
      return TcpProxyEntryTransportType.QUIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TcpProxyEntryTransportType.UNRECOGNIZED;
  }
}

export function tcpProxyEntryTransportTypeToJSON(object: TcpProxyEntryTransportType): string {
  switch (object) {
    case TcpProxyEntryTransportType.TCP:
      return "TCP";
    case TcpProxyEntryTransportType.KCP:
      return "KCP";
    case TcpProxyEntryTransportType.QUIC:
      return "QUIC";
    case TcpProxyEntryTransportType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TcpProxyEntryState {
  Unknown = 0,
  /** SynReceived - receive syn packet but not start connecting to dst */
  SynReceived = 1,
  /** ConnectingDst - connecting to dst */
  ConnectingDst = 2,
  /** Connected - connected to dst */
  Connected = 3,
  /** Closed - connection closed */
  Closed = 4,
  /** ClosingSrc - closing src */
  ClosingSrc = 5,
  /** ClosingDst - closing dst */
  ClosingDst = 6,
  UNRECOGNIZED = -1,
}

export function tcpProxyEntryStateFromJSON(object: any): TcpProxyEntryState {
  switch (object) {
    case 0:
    case "Unknown":
      return TcpProxyEntryState.Unknown;
    case 1:
    case "SynReceived":
      return TcpProxyEntryState.SynReceived;
    case 2:
    case "ConnectingDst":
      return TcpProxyEntryState.ConnectingDst;
    case 3:
    case "Connected":
      return TcpProxyEntryState.Connected;
    case 4:
    case "Closed":
      return TcpProxyEntryState.Closed;
    case 5:
    case "ClosingSrc":
      return TcpProxyEntryState.ClosingSrc;
    case 6:
    case "ClosingDst":
      return TcpProxyEntryState.ClosingDst;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TcpProxyEntryState.UNRECOGNIZED;
  }
}

export function tcpProxyEntryStateToJSON(object: TcpProxyEntryState): string {
  switch (object) {
    case TcpProxyEntryState.Unknown:
      return "Unknown";
    case TcpProxyEntryState.SynReceived:
      return "SynReceived";
    case TcpProxyEntryState.ConnectingDst:
      return "ConnectingDst";
    case TcpProxyEntryState.Connected:
      return "Connected";
    case TcpProxyEntryState.Closed:
      return "Closed";
    case TcpProxyEntryState.ClosingSrc:
      return "ClosingSrc";
    case TcpProxyEntryState.ClosingDst:
      return "ClosingDst";
    case TcpProxyEntryState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface InstanceIdentifier {
  id?: UUID | undefined;
  instanceSelector?: InstanceIdentifier_InstanceSelector | undefined;
}

export interface InstanceIdentifier_InstanceSelector {
  name?: string | undefined;
}

export interface Status {
  code: number;
  message: string;
}

export interface PeerConnStats {
  rxBytes: number;
  txBytes: number;
  rxPackets: number;
  txPackets: number;
  latencyUs: number;
}

export interface PeerConnInfo {
  connId: string;
  myPeerId: number;
  peerId: number;
  features: string[];
  tunnel: TunnelInfo | undefined;
  stats: PeerConnStats | undefined;
  lossRate: number;
  isClient: boolean;
  networkName: string;
  isClosed: boolean;
}

export interface PeerInfo {
  peerId: number;
  conns: PeerConnInfo[];
  defaultConnId: UUID | undefined;
  directlyConnectedConns: UUID[];
}

export interface ListPeerRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListPeerResponse {
  peerInfos: PeerInfo[];
  myInfo: NodeInfo | undefined;
}

export interface Route {
  peerId: number;
  ipv4Addr: Ipv4Inet | undefined;
  nextHopPeerId: number;
  cost: number;
  pathLatency: number;
  proxyCidrs: string[];
  hostname: string;
  stunInfo: StunInfo | undefined;
  instId: string;
  version: string;
  featureFlag: PeerFeatureFlag | undefined;
  nextHopPeerIdLatencyFirst?: number | undefined;
  costLatencyFirst?: number | undefined;
  pathLatencyLatencyFirst?: number | undefined;
  ipv6Addr: Ipv6Inet | undefined;
}

export interface PeerRoutePair {
  route: Route | undefined;
  peer: PeerInfo | undefined;
}

export interface NodeInfo {
  peerId: number;
  ipv4Addr: string;
  proxyCidrs: string[];
  hostname: string;
  stunInfo: StunInfo | undefined;
  instId: string;
  listeners: string[];
  config: string;
  version: string;
  featureFlag: PeerFeatureFlag | undefined;
  ipList: GetIpListResponse | undefined;
}

export interface ShowNodeInfoRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ShowNodeInfoResponse {
  nodeInfo: NodeInfo | undefined;
}

export interface ListRouteRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListRouteResponse {
  routes: Route[];
}

export interface DumpRouteRequest {
  instance: InstanceIdentifier | undefined;
}

export interface DumpRouteResponse {
  result: string;
}

export interface ListForeignNetworkRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ForeignNetworkEntryPb {
  peers: PeerInfo[];
  networkSecretDigest: Uint8Array;
  myPeerIdForThisNetwork: number;
}

export interface ListForeignNetworkResponse {
  /** foreign network in local */
  foreignNetworks: { [key: string]: ForeignNetworkEntryPb };
}

export interface ListForeignNetworkResponse_ForeignNetworksEntry {
  key: string;
  value: ForeignNetworkEntryPb | undefined;
}

export interface ListGlobalForeignNetworkRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListGlobalForeignNetworkResponse {
  foreignNetworks: { [key: number]: ListGlobalForeignNetworkResponse_ForeignNetworks };
}

/** foreign network in the entire network */
export interface ListGlobalForeignNetworkResponse_OneForeignNetwork {
  networkName: string;
  peerIds: number[];
  lastUpdated: string;
  version: number;
}

export interface ListGlobalForeignNetworkResponse_ForeignNetworks {
  foreignNetworks: ListGlobalForeignNetworkResponse_OneForeignNetwork[];
}

export interface ListGlobalForeignNetworkResponse_ForeignNetworksEntry {
  key: number;
  value: ListGlobalForeignNetworkResponse_ForeignNetworks | undefined;
}

export interface GetForeignNetworkSummaryRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetForeignNetworkSummaryResponse {
  summary: RouteForeignNetworkSummary | undefined;
}

export interface Connector {
  url: Url | undefined;
  status: ConnectorStatus;
}

export interface ListConnectorRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListConnectorResponse {
  connectors: Connector[];
}

export interface MappedListener {
  url: Url | undefined;
}

export interface ListMappedListenerRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListMappedListenerResponse {
  mappedlisteners: MappedListener[];
}

export interface VpnPortalInfo {
  vpnType: string;
  clientConfig: string;
  connectedClients: string[];
}

export interface GetVpnPortalInfoRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetVpnPortalInfoResponse {
  vpnPortalInfo: VpnPortalInfo | undefined;
}

export interface TcpProxyEntry {
  src: SocketAddr | undefined;
  dst: SocketAddr | undefined;
  startTime: number;
  state: TcpProxyEntryState;
  transportType: TcpProxyEntryTransportType;
}

export interface ListTcpProxyEntryRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListTcpProxyEntryResponse {
  entries: TcpProxyEntry[];
}

export interface GetAclStatsRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetAclStatsResponse {
  aclStats: AclStats | undefined;
}

export interface GetWhitelistRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetWhitelistResponse {
  tcpPorts: string[];
  udpPorts: string[];
}

export interface ListPortForwardRequest {
  instance: InstanceIdentifier | undefined;
}

export interface ListPortForwardResponse {
  cfgs: PortForwardConfigPb[];
}

export interface MetricSnapshot {
  name: string;
  value: number;
  labels: { [key: string]: string };
}

export interface MetricSnapshot_LabelsEntry {
  key: string;
  value: string;
}

export interface GetStatsRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetStatsResponse {
  metrics: MetricSnapshot[];
}

export interface GetPrometheusStatsRequest {
  instance: InstanceIdentifier | undefined;
}

export interface GetPrometheusStatsResponse {
  prometheusText: string;
}

function createBaseInstanceIdentifier(): InstanceIdentifier {
  return { id: undefined, instanceSelector: undefined };
}

export const InstanceIdentifier: MessageFns<InstanceIdentifier> = {
  fromJSON(object: any): InstanceIdentifier {
    return {
      id: isSet(object.id) ? UUID.fromJSON(object.id) : undefined,
      instanceSelector: isSet(object.instanceSelector)
        ? InstanceIdentifier_InstanceSelector.fromJSON(object.instanceSelector)
        : undefined,
    };
  },

  toJSON(message: InstanceIdentifier): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = UUID.toJSON(message.id);
    }
    if (message.instanceSelector !== undefined) {
      obj.instanceSelector = InstanceIdentifier_InstanceSelector.toJSON(message.instanceSelector);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstanceIdentifier>, I>>(base?: I): InstanceIdentifier {
    return InstanceIdentifier.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstanceIdentifier>, I>>(object: I): InstanceIdentifier {
    const message = createBaseInstanceIdentifier();
    message.id = (object.id !== undefined && object.id !== null) ? UUID.fromPartial(object.id) : undefined;
    message.instanceSelector = (object.instanceSelector !== undefined && object.instanceSelector !== null)
      ? InstanceIdentifier_InstanceSelector.fromPartial(object.instanceSelector)
      : undefined;
    return message;
  },
};

function createBaseInstanceIdentifier_InstanceSelector(): InstanceIdentifier_InstanceSelector {
  return { name: undefined };
}

export const InstanceIdentifier_InstanceSelector: MessageFns<InstanceIdentifier_InstanceSelector> = {
  fromJSON(object: any): InstanceIdentifier_InstanceSelector {
    return { name: isSet(object.name) ? globalThis.String(object.name) : undefined };
  },

  toJSON(message: InstanceIdentifier_InstanceSelector): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstanceIdentifier_InstanceSelector>, I>>(
    base?: I,
  ): InstanceIdentifier_InstanceSelector {
    return InstanceIdentifier_InstanceSelector.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstanceIdentifier_InstanceSelector>, I>>(
    object: I,
  ): InstanceIdentifier_InstanceSelector {
    const message = createBaseInstanceIdentifier_InstanceSelector();
    message.name = object.name ?? undefined;
    return message;
  },
};

function createBaseStatus(): Status {
  return { code: 0, message: "" };
}

export const Status: MessageFns<Status> = {
  fromJSON(object: any): Status {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: Status): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Status>, I>>(base?: I): Status {
    return Status.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Status>, I>>(object: I): Status {
    const message = createBaseStatus();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBasePeerConnStats(): PeerConnStats {
  return { rxBytes: 0, txBytes: 0, rxPackets: 0, txPackets: 0, latencyUs: 0 };
}

export const PeerConnStats: MessageFns<PeerConnStats> = {
  fromJSON(object: any): PeerConnStats {
    return {
      rxBytes: isSet(object.rxBytes) ? globalThis.Number(object.rxBytes) : 0,
      txBytes: isSet(object.txBytes) ? globalThis.Number(object.txBytes) : 0,
      rxPackets: isSet(object.rxPackets) ? globalThis.Number(object.rxPackets) : 0,
      txPackets: isSet(object.txPackets) ? globalThis.Number(object.txPackets) : 0,
      latencyUs: isSet(object.latencyUs) ? globalThis.Number(object.latencyUs) : 0,
    };
  },

  toJSON(message: PeerConnStats): unknown {
    const obj: any = {};
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.rxPackets !== 0) {
      obj.rxPackets = Math.round(message.rxPackets);
    }
    if (message.txPackets !== 0) {
      obj.txPackets = Math.round(message.txPackets);
    }
    if (message.latencyUs !== 0) {
      obj.latencyUs = Math.round(message.latencyUs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerConnStats>, I>>(base?: I): PeerConnStats {
    return PeerConnStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerConnStats>, I>>(object: I): PeerConnStats {
    const message = createBasePeerConnStats();
    message.rxBytes = object.rxBytes ?? 0;
    message.txBytes = object.txBytes ?? 0;
    message.rxPackets = object.rxPackets ?? 0;
    message.txPackets = object.txPackets ?? 0;
    message.latencyUs = object.latencyUs ?? 0;
    return message;
  },
};

function createBasePeerConnInfo(): PeerConnInfo {
  return {
    connId: "",
    myPeerId: 0,
    peerId: 0,
    features: [],
    tunnel: undefined,
    stats: undefined,
    lossRate: 0,
    isClient: false,
    networkName: "",
    isClosed: false,
  };
}

export const PeerConnInfo: MessageFns<PeerConnInfo> = {
  fromJSON(object: any): PeerConnInfo {
    return {
      connId: isSet(object.connId) ? globalThis.String(object.connId) : "",
      myPeerId: isSet(object.myPeerId) ? globalThis.Number(object.myPeerId) : 0,
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      features: globalThis.Array.isArray(object?.features) ? object.features.map((e: any) => globalThis.String(e)) : [],
      tunnel: isSet(object.tunnel) ? TunnelInfo.fromJSON(object.tunnel) : undefined,
      stats: isSet(object.stats) ? PeerConnStats.fromJSON(object.stats) : undefined,
      lossRate: isSet(object.lossRate) ? globalThis.Number(object.lossRate) : 0,
      isClient: isSet(object.isClient) ? globalThis.Boolean(object.isClient) : false,
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : "",
      isClosed: isSet(object.isClosed) ? globalThis.Boolean(object.isClosed) : false,
    };
  },

  toJSON(message: PeerConnInfo): unknown {
    const obj: any = {};
    if (message.connId !== "") {
      obj.connId = message.connId;
    }
    if (message.myPeerId !== 0) {
      obj.myPeerId = Math.round(message.myPeerId);
    }
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.features?.length) {
      obj.features = message.features;
    }
    if (message.tunnel !== undefined) {
      obj.tunnel = TunnelInfo.toJSON(message.tunnel);
    }
    if (message.stats !== undefined) {
      obj.stats = PeerConnStats.toJSON(message.stats);
    }
    if (message.lossRate !== 0) {
      obj.lossRate = message.lossRate;
    }
    if (message.isClient !== false) {
      obj.isClient = message.isClient;
    }
    if (message.networkName !== "") {
      obj.networkName = message.networkName;
    }
    if (message.isClosed !== false) {
      obj.isClosed = message.isClosed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerConnInfo>, I>>(base?: I): PeerConnInfo {
    return PeerConnInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerConnInfo>, I>>(object: I): PeerConnInfo {
    const message = createBasePeerConnInfo();
    message.connId = object.connId ?? "";
    message.myPeerId = object.myPeerId ?? 0;
    message.peerId = object.peerId ?? 0;
    message.features = object.features?.map((e) => e) || [];
    message.tunnel = (object.tunnel !== undefined && object.tunnel !== null)
      ? TunnelInfo.fromPartial(object.tunnel)
      : undefined;
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? PeerConnStats.fromPartial(object.stats)
      : undefined;
    message.lossRate = object.lossRate ?? 0;
    message.isClient = object.isClient ?? false;
    message.networkName = object.networkName ?? "";
    message.isClosed = object.isClosed ?? false;
    return message;
  },
};

function createBasePeerInfo(): PeerInfo {
  return { peerId: 0, conns: [], defaultConnId: undefined, directlyConnectedConns: [] };
}

export const PeerInfo: MessageFns<PeerInfo> = {
  fromJSON(object: any): PeerInfo {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      conns: globalThis.Array.isArray(object?.conns) ? object.conns.map((e: any) => PeerConnInfo.fromJSON(e)) : [],
      defaultConnId: isSet(object.defaultConnId) ? UUID.fromJSON(object.defaultConnId) : undefined,
      directlyConnectedConns: globalThis.Array.isArray(object?.directlyConnectedConns)
        ? object.directlyConnectedConns.map((e: any) => UUID.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PeerInfo): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.conns?.length) {
      obj.conns = message.conns.map((e) => PeerConnInfo.toJSON(e));
    }
    if (message.defaultConnId !== undefined) {
      obj.defaultConnId = UUID.toJSON(message.defaultConnId);
    }
    if (message.directlyConnectedConns?.length) {
      obj.directlyConnectedConns = message.directlyConnectedConns.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerInfo>, I>>(base?: I): PeerInfo {
    return PeerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerInfo>, I>>(object: I): PeerInfo {
    const message = createBasePeerInfo();
    message.peerId = object.peerId ?? 0;
    message.conns = object.conns?.map((e) => PeerConnInfo.fromPartial(e)) || [];
    message.defaultConnId = (object.defaultConnId !== undefined && object.defaultConnId !== null)
      ? UUID.fromPartial(object.defaultConnId)
      : undefined;
    message.directlyConnectedConns = object.directlyConnectedConns?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListPeerRequest(): ListPeerRequest {
  return { instance: undefined };
}

export const ListPeerRequest: MessageFns<ListPeerRequest> = {
  fromJSON(object: any): ListPeerRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListPeerRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPeerRequest>, I>>(base?: I): ListPeerRequest {
    return ListPeerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPeerRequest>, I>>(object: I): ListPeerRequest {
    const message = createBaseListPeerRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListPeerResponse(): ListPeerResponse {
  return { peerInfos: [], myInfo: undefined };
}

export const ListPeerResponse: MessageFns<ListPeerResponse> = {
  fromJSON(object: any): ListPeerResponse {
    return {
      peerInfos: globalThis.Array.isArray(object?.peerInfos)
        ? object.peerInfos.map((e: any) => PeerInfo.fromJSON(e))
        : [],
      myInfo: isSet(object.myInfo) ? NodeInfo.fromJSON(object.myInfo) : undefined,
    };
  },

  toJSON(message: ListPeerResponse): unknown {
    const obj: any = {};
    if (message.peerInfos?.length) {
      obj.peerInfos = message.peerInfos.map((e) => PeerInfo.toJSON(e));
    }
    if (message.myInfo !== undefined) {
      obj.myInfo = NodeInfo.toJSON(message.myInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPeerResponse>, I>>(base?: I): ListPeerResponse {
    return ListPeerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPeerResponse>, I>>(object: I): ListPeerResponse {
    const message = createBaseListPeerResponse();
    message.peerInfos = object.peerInfos?.map((e) => PeerInfo.fromPartial(e)) || [];
    message.myInfo = (object.myInfo !== undefined && object.myInfo !== null)
      ? NodeInfo.fromPartial(object.myInfo)
      : undefined;
    return message;
  },
};

function createBaseRoute(): Route {
  return {
    peerId: 0,
    ipv4Addr: undefined,
    nextHopPeerId: 0,
    cost: 0,
    pathLatency: 0,
    proxyCidrs: [],
    hostname: "",
    stunInfo: undefined,
    instId: "",
    version: "",
    featureFlag: undefined,
    nextHopPeerIdLatencyFirst: undefined,
    costLatencyFirst: undefined,
    pathLatencyLatencyFirst: undefined,
    ipv6Addr: undefined,
  };
}

export const Route: MessageFns<Route> = {
  fromJSON(object: any): Route {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      ipv4Addr: isSet(object.ipv4Addr) ? Ipv4Inet.fromJSON(object.ipv4Addr) : undefined,
      nextHopPeerId: isSet(object.nextHopPeerId) ? globalThis.Number(object.nextHopPeerId) : 0,
      cost: isSet(object.cost) ? globalThis.Number(object.cost) : 0,
      pathLatency: isSet(object.pathLatency) ? globalThis.Number(object.pathLatency) : 0,
      proxyCidrs: globalThis.Array.isArray(object?.proxyCidrs)
        ? object.proxyCidrs.map((e: any) => globalThis.String(e))
        : [],
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      stunInfo: isSet(object.stunInfo) ? StunInfo.fromJSON(object.stunInfo) : undefined,
      instId: isSet(object.instId) ? globalThis.String(object.instId) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      featureFlag: isSet(object.featureFlag) ? PeerFeatureFlag.fromJSON(object.featureFlag) : undefined,
      nextHopPeerIdLatencyFirst: isSet(object.nextHopPeerIdLatencyFirst)
        ? globalThis.Number(object.nextHopPeerIdLatencyFirst)
        : undefined,
      costLatencyFirst: isSet(object.costLatencyFirst) ? globalThis.Number(object.costLatencyFirst) : undefined,
      pathLatencyLatencyFirst: isSet(object.pathLatencyLatencyFirst)
        ? globalThis.Number(object.pathLatencyLatencyFirst)
        : undefined,
      ipv6Addr: isSet(object.ipv6Addr) ? Ipv6Inet.fromJSON(object.ipv6Addr) : undefined,
    };
  },

  toJSON(message: Route): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.ipv4Addr !== undefined) {
      obj.ipv4Addr = Ipv4Inet.toJSON(message.ipv4Addr);
    }
    if (message.nextHopPeerId !== 0) {
      obj.nextHopPeerId = Math.round(message.nextHopPeerId);
    }
    if (message.cost !== 0) {
      obj.cost = Math.round(message.cost);
    }
    if (message.pathLatency !== 0) {
      obj.pathLatency = Math.round(message.pathLatency);
    }
    if (message.proxyCidrs?.length) {
      obj.proxyCidrs = message.proxyCidrs;
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.stunInfo !== undefined) {
      obj.stunInfo = StunInfo.toJSON(message.stunInfo);
    }
    if (message.instId !== "") {
      obj.instId = message.instId;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.featureFlag !== undefined) {
      obj.featureFlag = PeerFeatureFlag.toJSON(message.featureFlag);
    }
    if (message.nextHopPeerIdLatencyFirst !== undefined) {
      obj.nextHopPeerIdLatencyFirst = Math.round(message.nextHopPeerIdLatencyFirst);
    }
    if (message.costLatencyFirst !== undefined) {
      obj.costLatencyFirst = Math.round(message.costLatencyFirst);
    }
    if (message.pathLatencyLatencyFirst !== undefined) {
      obj.pathLatencyLatencyFirst = Math.round(message.pathLatencyLatencyFirst);
    }
    if (message.ipv6Addr !== undefined) {
      obj.ipv6Addr = Ipv6Inet.toJSON(message.ipv6Addr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Route>, I>>(base?: I): Route {
    return Route.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Route>, I>>(object: I): Route {
    const message = createBaseRoute();
    message.peerId = object.peerId ?? 0;
    message.ipv4Addr = (object.ipv4Addr !== undefined && object.ipv4Addr !== null)
      ? Ipv4Inet.fromPartial(object.ipv4Addr)
      : undefined;
    message.nextHopPeerId = object.nextHopPeerId ?? 0;
    message.cost = object.cost ?? 0;
    message.pathLatency = object.pathLatency ?? 0;
    message.proxyCidrs = object.proxyCidrs?.map((e) => e) || [];
    message.hostname = object.hostname ?? "";
    message.stunInfo = (object.stunInfo !== undefined && object.stunInfo !== null)
      ? StunInfo.fromPartial(object.stunInfo)
      : undefined;
    message.instId = object.instId ?? "";
    message.version = object.version ?? "";
    message.featureFlag = (object.featureFlag !== undefined && object.featureFlag !== null)
      ? PeerFeatureFlag.fromPartial(object.featureFlag)
      : undefined;
    message.nextHopPeerIdLatencyFirst = object.nextHopPeerIdLatencyFirst ?? undefined;
    message.costLatencyFirst = object.costLatencyFirst ?? undefined;
    message.pathLatencyLatencyFirst = object.pathLatencyLatencyFirst ?? undefined;
    message.ipv6Addr = (object.ipv6Addr !== undefined && object.ipv6Addr !== null)
      ? Ipv6Inet.fromPartial(object.ipv6Addr)
      : undefined;
    return message;
  },
};

function createBasePeerRoutePair(): PeerRoutePair {
  return { route: undefined, peer: undefined };
}

export const PeerRoutePair: MessageFns<PeerRoutePair> = {
  fromJSON(object: any): PeerRoutePair {
    return {
      route: isSet(object.route) ? Route.fromJSON(object.route) : undefined,
      peer: isSet(object.peer) ? PeerInfo.fromJSON(object.peer) : undefined,
    };
  },

  toJSON(message: PeerRoutePair): unknown {
    const obj: any = {};
    if (message.route !== undefined) {
      obj.route = Route.toJSON(message.route);
    }
    if (message.peer !== undefined) {
      obj.peer = PeerInfo.toJSON(message.peer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerRoutePair>, I>>(base?: I): PeerRoutePair {
    return PeerRoutePair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerRoutePair>, I>>(object: I): PeerRoutePair {
    const message = createBasePeerRoutePair();
    message.route = (object.route !== undefined && object.route !== null) ? Route.fromPartial(object.route) : undefined;
    message.peer = (object.peer !== undefined && object.peer !== null) ? PeerInfo.fromPartial(object.peer) : undefined;
    return message;
  },
};

function createBaseNodeInfo(): NodeInfo {
  return {
    peerId: 0,
    ipv4Addr: "",
    proxyCidrs: [],
    hostname: "",
    stunInfo: undefined,
    instId: "",
    listeners: [],
    config: "",
    version: "",
    featureFlag: undefined,
    ipList: undefined,
  };
}

export const NodeInfo: MessageFns<NodeInfo> = {
  fromJSON(object: any): NodeInfo {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      ipv4Addr: isSet(object.ipv4Addr) ? globalThis.String(object.ipv4Addr) : "",
      proxyCidrs: globalThis.Array.isArray(object?.proxyCidrs)
        ? object.proxyCidrs.map((e: any) => globalThis.String(e))
        : [],
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      stunInfo: isSet(object.stunInfo) ? StunInfo.fromJSON(object.stunInfo) : undefined,
      instId: isSet(object.instId) ? globalThis.String(object.instId) : "",
      listeners: globalThis.Array.isArray(object?.listeners)
        ? object.listeners.map((e: any) => globalThis.String(e))
        : [],
      config: isSet(object.config) ? globalThis.String(object.config) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      featureFlag: isSet(object.featureFlag) ? PeerFeatureFlag.fromJSON(object.featureFlag) : undefined,
      ipList: isSet(object.ipList) ? GetIpListResponse.fromJSON(object.ipList) : undefined,
    };
  },

  toJSON(message: NodeInfo): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.ipv4Addr !== "") {
      obj.ipv4Addr = message.ipv4Addr;
    }
    if (message.proxyCidrs?.length) {
      obj.proxyCidrs = message.proxyCidrs;
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.stunInfo !== undefined) {
      obj.stunInfo = StunInfo.toJSON(message.stunInfo);
    }
    if (message.instId !== "") {
      obj.instId = message.instId;
    }
    if (message.listeners?.length) {
      obj.listeners = message.listeners;
    }
    if (message.config !== "") {
      obj.config = message.config;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.featureFlag !== undefined) {
      obj.featureFlag = PeerFeatureFlag.toJSON(message.featureFlag);
    }
    if (message.ipList !== undefined) {
      obj.ipList = GetIpListResponse.toJSON(message.ipList);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeInfo>, I>>(base?: I): NodeInfo {
    return NodeInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeInfo>, I>>(object: I): NodeInfo {
    const message = createBaseNodeInfo();
    message.peerId = object.peerId ?? 0;
    message.ipv4Addr = object.ipv4Addr ?? "";
    message.proxyCidrs = object.proxyCidrs?.map((e) => e) || [];
    message.hostname = object.hostname ?? "";
    message.stunInfo = (object.stunInfo !== undefined && object.stunInfo !== null)
      ? StunInfo.fromPartial(object.stunInfo)
      : undefined;
    message.instId = object.instId ?? "";
    message.listeners = object.listeners?.map((e) => e) || [];
    message.config = object.config ?? "";
    message.version = object.version ?? "";
    message.featureFlag = (object.featureFlag !== undefined && object.featureFlag !== null)
      ? PeerFeatureFlag.fromPartial(object.featureFlag)
      : undefined;
    message.ipList = (object.ipList !== undefined && object.ipList !== null)
      ? GetIpListResponse.fromPartial(object.ipList)
      : undefined;
    return message;
  },
};

function createBaseShowNodeInfoRequest(): ShowNodeInfoRequest {
  return { instance: undefined };
}

export const ShowNodeInfoRequest: MessageFns<ShowNodeInfoRequest> = {
  fromJSON(object: any): ShowNodeInfoRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ShowNodeInfoRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShowNodeInfoRequest>, I>>(base?: I): ShowNodeInfoRequest {
    return ShowNodeInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShowNodeInfoRequest>, I>>(object: I): ShowNodeInfoRequest {
    const message = createBaseShowNodeInfoRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseShowNodeInfoResponse(): ShowNodeInfoResponse {
  return { nodeInfo: undefined };
}

export const ShowNodeInfoResponse: MessageFns<ShowNodeInfoResponse> = {
  fromJSON(object: any): ShowNodeInfoResponse {
    return { nodeInfo: isSet(object.nodeInfo) ? NodeInfo.fromJSON(object.nodeInfo) : undefined };
  },

  toJSON(message: ShowNodeInfoResponse): unknown {
    const obj: any = {};
    if (message.nodeInfo !== undefined) {
      obj.nodeInfo = NodeInfo.toJSON(message.nodeInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShowNodeInfoResponse>, I>>(base?: I): ShowNodeInfoResponse {
    return ShowNodeInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShowNodeInfoResponse>, I>>(object: I): ShowNodeInfoResponse {
    const message = createBaseShowNodeInfoResponse();
    message.nodeInfo = (object.nodeInfo !== undefined && object.nodeInfo !== null)
      ? NodeInfo.fromPartial(object.nodeInfo)
      : undefined;
    return message;
  },
};

function createBaseListRouteRequest(): ListRouteRequest {
  return { instance: undefined };
}

export const ListRouteRequest: MessageFns<ListRouteRequest> = {
  fromJSON(object: any): ListRouteRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListRouteRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRouteRequest>, I>>(base?: I): ListRouteRequest {
    return ListRouteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRouteRequest>, I>>(object: I): ListRouteRequest {
    const message = createBaseListRouteRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListRouteResponse(): ListRouteResponse {
  return { routes: [] };
}

export const ListRouteResponse: MessageFns<ListRouteResponse> = {
  fromJSON(object: any): ListRouteResponse {
    return { routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => Route.fromJSON(e)) : [] };
  },

  toJSON(message: ListRouteResponse): unknown {
    const obj: any = {};
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Route.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRouteResponse>, I>>(base?: I): ListRouteResponse {
    return ListRouteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRouteResponse>, I>>(object: I): ListRouteResponse {
    const message = createBaseListRouteResponse();
    message.routes = object.routes?.map((e) => Route.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDumpRouteRequest(): DumpRouteRequest {
  return { instance: undefined };
}

export const DumpRouteRequest: MessageFns<DumpRouteRequest> = {
  fromJSON(object: any): DumpRouteRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: DumpRouteRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DumpRouteRequest>, I>>(base?: I): DumpRouteRequest {
    return DumpRouteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DumpRouteRequest>, I>>(object: I): DumpRouteRequest {
    const message = createBaseDumpRouteRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseDumpRouteResponse(): DumpRouteResponse {
  return { result: "" };
}

export const DumpRouteResponse: MessageFns<DumpRouteResponse> = {
  fromJSON(object: any): DumpRouteResponse {
    return { result: isSet(object.result) ? globalThis.String(object.result) : "" };
  },

  toJSON(message: DumpRouteResponse): unknown {
    const obj: any = {};
    if (message.result !== "") {
      obj.result = message.result;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DumpRouteResponse>, I>>(base?: I): DumpRouteResponse {
    return DumpRouteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DumpRouteResponse>, I>>(object: I): DumpRouteResponse {
    const message = createBaseDumpRouteResponse();
    message.result = object.result ?? "";
    return message;
  },
};

function createBaseListForeignNetworkRequest(): ListForeignNetworkRequest {
  return { instance: undefined };
}

export const ListForeignNetworkRequest: MessageFns<ListForeignNetworkRequest> = {
  fromJSON(object: any): ListForeignNetworkRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListForeignNetworkRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListForeignNetworkRequest>, I>>(base?: I): ListForeignNetworkRequest {
    return ListForeignNetworkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListForeignNetworkRequest>, I>>(object: I): ListForeignNetworkRequest {
    const message = createBaseListForeignNetworkRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseForeignNetworkEntryPb(): ForeignNetworkEntryPb {
  return { peers: [], networkSecretDigest: new Uint8Array(0), myPeerIdForThisNetwork: 0 };
}

export const ForeignNetworkEntryPb: MessageFns<ForeignNetworkEntryPb> = {
  fromJSON(object: any): ForeignNetworkEntryPb {
    return {
      peers: globalThis.Array.isArray(object?.peers) ? object.peers.map((e: any) => PeerInfo.fromJSON(e)) : [],
      networkSecretDigest: isSet(object.networkSecretDigest)
        ? bytesFromBase64(object.networkSecretDigest)
        : new Uint8Array(0),
      myPeerIdForThisNetwork: isSet(object.myPeerIdForThisNetwork)
        ? globalThis.Number(object.myPeerIdForThisNetwork)
        : 0,
    };
  },

  toJSON(message: ForeignNetworkEntryPb): unknown {
    const obj: any = {};
    if (message.peers?.length) {
      obj.peers = message.peers.map((e) => PeerInfo.toJSON(e));
    }
    if (message.networkSecretDigest.length !== 0) {
      obj.networkSecretDigest = base64FromBytes(message.networkSecretDigest);
    }
    if (message.myPeerIdForThisNetwork !== 0) {
      obj.myPeerIdForThisNetwork = Math.round(message.myPeerIdForThisNetwork);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForeignNetworkEntryPb>, I>>(base?: I): ForeignNetworkEntryPb {
    return ForeignNetworkEntryPb.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForeignNetworkEntryPb>, I>>(object: I): ForeignNetworkEntryPb {
    const message = createBaseForeignNetworkEntryPb();
    message.peers = object.peers?.map((e) => PeerInfo.fromPartial(e)) || [];
    message.networkSecretDigest = object.networkSecretDigest ?? new Uint8Array(0);
    message.myPeerIdForThisNetwork = object.myPeerIdForThisNetwork ?? 0;
    return message;
  },
};

function createBaseListForeignNetworkResponse(): ListForeignNetworkResponse {
  return { foreignNetworks: {} };
}

export const ListForeignNetworkResponse: MessageFns<ListForeignNetworkResponse> = {
  fromJSON(object: any): ListForeignNetworkResponse {
    return {
      foreignNetworks: isObject(object.foreignNetworks)
        ? Object.entries(object.foreignNetworks).reduce<{ [key: string]: ForeignNetworkEntryPb }>(
          (acc, [key, value]) => {
            acc[key] = ForeignNetworkEntryPb.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ListForeignNetworkResponse): unknown {
    const obj: any = {};
    if (message.foreignNetworks) {
      const entries = Object.entries(message.foreignNetworks);
      if (entries.length > 0) {
        obj.foreignNetworks = {};
        entries.forEach(([k, v]) => {
          obj.foreignNetworks[k] = ForeignNetworkEntryPb.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListForeignNetworkResponse>, I>>(base?: I): ListForeignNetworkResponse {
    return ListForeignNetworkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListForeignNetworkResponse>, I>>(object: I): ListForeignNetworkResponse {
    const message = createBaseListForeignNetworkResponse();
    message.foreignNetworks = Object.entries(object.foreignNetworks ?? {}).reduce<
      { [key: string]: ForeignNetworkEntryPb }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = ForeignNetworkEntryPb.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseListForeignNetworkResponse_ForeignNetworksEntry(): ListForeignNetworkResponse_ForeignNetworksEntry {
  return { key: "", value: undefined };
}

export const ListForeignNetworkResponse_ForeignNetworksEntry: MessageFns<
  ListForeignNetworkResponse_ForeignNetworksEntry
> = {
  fromJSON(object: any): ListForeignNetworkResponse_ForeignNetworksEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ForeignNetworkEntryPb.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ListForeignNetworkResponse_ForeignNetworksEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ForeignNetworkEntryPb.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListForeignNetworkResponse_ForeignNetworksEntry>, I>>(
    base?: I,
  ): ListForeignNetworkResponse_ForeignNetworksEntry {
    return ListForeignNetworkResponse_ForeignNetworksEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListForeignNetworkResponse_ForeignNetworksEntry>, I>>(
    object: I,
  ): ListForeignNetworkResponse_ForeignNetworksEntry {
    const message = createBaseListForeignNetworkResponse_ForeignNetworksEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ForeignNetworkEntryPb.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseListGlobalForeignNetworkRequest(): ListGlobalForeignNetworkRequest {
  return { instance: undefined };
}

export const ListGlobalForeignNetworkRequest: MessageFns<ListGlobalForeignNetworkRequest> = {
  fromJSON(object: any): ListGlobalForeignNetworkRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListGlobalForeignNetworkRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListGlobalForeignNetworkRequest>, I>>(base?: I): ListGlobalForeignNetworkRequest {
    return ListGlobalForeignNetworkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListGlobalForeignNetworkRequest>, I>>(
    object: I,
  ): ListGlobalForeignNetworkRequest {
    const message = createBaseListGlobalForeignNetworkRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListGlobalForeignNetworkResponse(): ListGlobalForeignNetworkResponse {
  return { foreignNetworks: {} };
}

export const ListGlobalForeignNetworkResponse: MessageFns<ListGlobalForeignNetworkResponse> = {
  fromJSON(object: any): ListGlobalForeignNetworkResponse {
    return {
      foreignNetworks: isObject(object.foreignNetworks)
        ? Object.entries(object.foreignNetworks).reduce<
          { [key: number]: ListGlobalForeignNetworkResponse_ForeignNetworks }
        >((acc, [key, value]) => {
          acc[globalThis.Number(key)] = ListGlobalForeignNetworkResponse_ForeignNetworks.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: ListGlobalForeignNetworkResponse): unknown {
    const obj: any = {};
    if (message.foreignNetworks) {
      const entries = Object.entries(message.foreignNetworks);
      if (entries.length > 0) {
        obj.foreignNetworks = {};
        entries.forEach(([k, v]) => {
          obj.foreignNetworks[k] = ListGlobalForeignNetworkResponse_ForeignNetworks.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse>, I>>(
    base?: I,
  ): ListGlobalForeignNetworkResponse {
    return ListGlobalForeignNetworkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse>, I>>(
    object: I,
  ): ListGlobalForeignNetworkResponse {
    const message = createBaseListGlobalForeignNetworkResponse();
    message.foreignNetworks = Object.entries(object.foreignNetworks ?? {}).reduce<
      { [key: number]: ListGlobalForeignNetworkResponse_ForeignNetworks }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[globalThis.Number(key)] = ListGlobalForeignNetworkResponse_ForeignNetworks.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseListGlobalForeignNetworkResponse_OneForeignNetwork(): ListGlobalForeignNetworkResponse_OneForeignNetwork {
  return { networkName: "", peerIds: [], lastUpdated: "", version: 0 };
}

export const ListGlobalForeignNetworkResponse_OneForeignNetwork: MessageFns<
  ListGlobalForeignNetworkResponse_OneForeignNetwork
> = {
  fromJSON(object: any): ListGlobalForeignNetworkResponse_OneForeignNetwork {
    return {
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : "",
      peerIds: globalThis.Array.isArray(object?.peerIds) ? object.peerIds.map((e: any) => globalThis.Number(e)) : [],
      lastUpdated: isSet(object.lastUpdated) ? globalThis.String(object.lastUpdated) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: ListGlobalForeignNetworkResponse_OneForeignNetwork): unknown {
    const obj: any = {};
    if (message.networkName !== "") {
      obj.networkName = message.networkName;
    }
    if (message.peerIds?.length) {
      obj.peerIds = message.peerIds.map((e) => Math.round(e));
    }
    if (message.lastUpdated !== "") {
      obj.lastUpdated = message.lastUpdated;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_OneForeignNetwork>, I>>(
    base?: I,
  ): ListGlobalForeignNetworkResponse_OneForeignNetwork {
    return ListGlobalForeignNetworkResponse_OneForeignNetwork.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_OneForeignNetwork>, I>>(
    object: I,
  ): ListGlobalForeignNetworkResponse_OneForeignNetwork {
    const message = createBaseListGlobalForeignNetworkResponse_OneForeignNetwork();
    message.networkName = object.networkName ?? "";
    message.peerIds = object.peerIds?.map((e) => e) || [];
    message.lastUpdated = object.lastUpdated ?? "";
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseListGlobalForeignNetworkResponse_ForeignNetworks(): ListGlobalForeignNetworkResponse_ForeignNetworks {
  return { foreignNetworks: [] };
}

export const ListGlobalForeignNetworkResponse_ForeignNetworks: MessageFns<
  ListGlobalForeignNetworkResponse_ForeignNetworks
> = {
  fromJSON(object: any): ListGlobalForeignNetworkResponse_ForeignNetworks {
    return {
      foreignNetworks: globalThis.Array.isArray(object?.foreignNetworks)
        ? object.foreignNetworks.map((e: any) => ListGlobalForeignNetworkResponse_OneForeignNetwork.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListGlobalForeignNetworkResponse_ForeignNetworks): unknown {
    const obj: any = {};
    if (message.foreignNetworks?.length) {
      obj.foreignNetworks = message.foreignNetworks.map((e) =>
        ListGlobalForeignNetworkResponse_OneForeignNetwork.toJSON(e)
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_ForeignNetworks>, I>>(
    base?: I,
  ): ListGlobalForeignNetworkResponse_ForeignNetworks {
    return ListGlobalForeignNetworkResponse_ForeignNetworks.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_ForeignNetworks>, I>>(
    object: I,
  ): ListGlobalForeignNetworkResponse_ForeignNetworks {
    const message = createBaseListGlobalForeignNetworkResponse_ForeignNetworks();
    message.foreignNetworks =
      object.foreignNetworks?.map((e) => ListGlobalForeignNetworkResponse_OneForeignNetwork.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListGlobalForeignNetworkResponse_ForeignNetworksEntry(): ListGlobalForeignNetworkResponse_ForeignNetworksEntry {
  return { key: 0, value: undefined };
}

export const ListGlobalForeignNetworkResponse_ForeignNetworksEntry: MessageFns<
  ListGlobalForeignNetworkResponse_ForeignNetworksEntry
> = {
  fromJSON(object: any): ListGlobalForeignNetworkResponse_ForeignNetworksEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? ListGlobalForeignNetworkResponse_ForeignNetworks.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ListGlobalForeignNetworkResponse_ForeignNetworksEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = ListGlobalForeignNetworkResponse_ForeignNetworks.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_ForeignNetworksEntry>, I>>(
    base?: I,
  ): ListGlobalForeignNetworkResponse_ForeignNetworksEntry {
    return ListGlobalForeignNetworkResponse_ForeignNetworksEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListGlobalForeignNetworkResponse_ForeignNetworksEntry>, I>>(
    object: I,
  ): ListGlobalForeignNetworkResponse_ForeignNetworksEntry {
    const message = createBaseListGlobalForeignNetworkResponse_ForeignNetworksEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? ListGlobalForeignNetworkResponse_ForeignNetworks.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseGetForeignNetworkSummaryRequest(): GetForeignNetworkSummaryRequest {
  return { instance: undefined };
}

export const GetForeignNetworkSummaryRequest: MessageFns<GetForeignNetworkSummaryRequest> = {
  fromJSON(object: any): GetForeignNetworkSummaryRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetForeignNetworkSummaryRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetForeignNetworkSummaryRequest>, I>>(base?: I): GetForeignNetworkSummaryRequest {
    return GetForeignNetworkSummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetForeignNetworkSummaryRequest>, I>>(
    object: I,
  ): GetForeignNetworkSummaryRequest {
    const message = createBaseGetForeignNetworkSummaryRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetForeignNetworkSummaryResponse(): GetForeignNetworkSummaryResponse {
  return { summary: undefined };
}

export const GetForeignNetworkSummaryResponse: MessageFns<GetForeignNetworkSummaryResponse> = {
  fromJSON(object: any): GetForeignNetworkSummaryResponse {
    return { summary: isSet(object.summary) ? RouteForeignNetworkSummary.fromJSON(object.summary) : undefined };
  },

  toJSON(message: GetForeignNetworkSummaryResponse): unknown {
    const obj: any = {};
    if (message.summary !== undefined) {
      obj.summary = RouteForeignNetworkSummary.toJSON(message.summary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetForeignNetworkSummaryResponse>, I>>(
    base?: I,
  ): GetForeignNetworkSummaryResponse {
    return GetForeignNetworkSummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetForeignNetworkSummaryResponse>, I>>(
    object: I,
  ): GetForeignNetworkSummaryResponse {
    const message = createBaseGetForeignNetworkSummaryResponse();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? RouteForeignNetworkSummary.fromPartial(object.summary)
      : undefined;
    return message;
  },
};

function createBaseConnector(): Connector {
  return { url: undefined, status: 0 };
}

export const Connector: MessageFns<Connector> = {
  fromJSON(object: any): Connector {
    return {
      url: isSet(object.url) ? Url.fromJSON(object.url) : undefined,
      status: isSet(object.status) ? connectorStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: Connector): unknown {
    const obj: any = {};
    if (message.url !== undefined) {
      obj.url = Url.toJSON(message.url);
    }
    if (message.status !== 0) {
      obj.status = connectorStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Connector>, I>>(base?: I): Connector {
    return Connector.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Connector>, I>>(object: I): Connector {
    const message = createBaseConnector();
    message.url = (object.url !== undefined && object.url !== null) ? Url.fromPartial(object.url) : undefined;
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseListConnectorRequest(): ListConnectorRequest {
  return { instance: undefined };
}

export const ListConnectorRequest: MessageFns<ListConnectorRequest> = {
  fromJSON(object: any): ListConnectorRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListConnectorRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConnectorRequest>, I>>(base?: I): ListConnectorRequest {
    return ListConnectorRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConnectorRequest>, I>>(object: I): ListConnectorRequest {
    const message = createBaseListConnectorRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListConnectorResponse(): ListConnectorResponse {
  return { connectors: [] };
}

export const ListConnectorResponse: MessageFns<ListConnectorResponse> = {
  fromJSON(object: any): ListConnectorResponse {
    return {
      connectors: globalThis.Array.isArray(object?.connectors)
        ? object.connectors.map((e: any) => Connector.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListConnectorResponse): unknown {
    const obj: any = {};
    if (message.connectors?.length) {
      obj.connectors = message.connectors.map((e) => Connector.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConnectorResponse>, I>>(base?: I): ListConnectorResponse {
    return ListConnectorResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConnectorResponse>, I>>(object: I): ListConnectorResponse {
    const message = createBaseListConnectorResponse();
    message.connectors = object.connectors?.map((e) => Connector.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMappedListener(): MappedListener {
  return { url: undefined };
}

export const MappedListener: MessageFns<MappedListener> = {
  fromJSON(object: any): MappedListener {
    return { url: isSet(object.url) ? Url.fromJSON(object.url) : undefined };
  },

  toJSON(message: MappedListener): unknown {
    const obj: any = {};
    if (message.url !== undefined) {
      obj.url = Url.toJSON(message.url);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MappedListener>, I>>(base?: I): MappedListener {
    return MappedListener.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MappedListener>, I>>(object: I): MappedListener {
    const message = createBaseMappedListener();
    message.url = (object.url !== undefined && object.url !== null) ? Url.fromPartial(object.url) : undefined;
    return message;
  },
};

function createBaseListMappedListenerRequest(): ListMappedListenerRequest {
  return { instance: undefined };
}

export const ListMappedListenerRequest: MessageFns<ListMappedListenerRequest> = {
  fromJSON(object: any): ListMappedListenerRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListMappedListenerRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMappedListenerRequest>, I>>(base?: I): ListMappedListenerRequest {
    return ListMappedListenerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMappedListenerRequest>, I>>(object: I): ListMappedListenerRequest {
    const message = createBaseListMappedListenerRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListMappedListenerResponse(): ListMappedListenerResponse {
  return { mappedlisteners: [] };
}

export const ListMappedListenerResponse: MessageFns<ListMappedListenerResponse> = {
  fromJSON(object: any): ListMappedListenerResponse {
    return {
      mappedlisteners: globalThis.Array.isArray(object?.mappedlisteners)
        ? object.mappedlisteners.map((e: any) => MappedListener.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListMappedListenerResponse): unknown {
    const obj: any = {};
    if (message.mappedlisteners?.length) {
      obj.mappedlisteners = message.mappedlisteners.map((e) => MappedListener.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListMappedListenerResponse>, I>>(base?: I): ListMappedListenerResponse {
    return ListMappedListenerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListMappedListenerResponse>, I>>(object: I): ListMappedListenerResponse {
    const message = createBaseListMappedListenerResponse();
    message.mappedlisteners = object.mappedlisteners?.map((e) => MappedListener.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVpnPortalInfo(): VpnPortalInfo {
  return { vpnType: "", clientConfig: "", connectedClients: [] };
}

export const VpnPortalInfo: MessageFns<VpnPortalInfo> = {
  fromJSON(object: any): VpnPortalInfo {
    return {
      vpnType: isSet(object.vpnType) ? globalThis.String(object.vpnType) : "",
      clientConfig: isSet(object.clientConfig) ? globalThis.String(object.clientConfig) : "",
      connectedClients: globalThis.Array.isArray(object?.connectedClients)
        ? object.connectedClients.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: VpnPortalInfo): unknown {
    const obj: any = {};
    if (message.vpnType !== "") {
      obj.vpnType = message.vpnType;
    }
    if (message.clientConfig !== "") {
      obj.clientConfig = message.clientConfig;
    }
    if (message.connectedClients?.length) {
      obj.connectedClients = message.connectedClients;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VpnPortalInfo>, I>>(base?: I): VpnPortalInfo {
    return VpnPortalInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VpnPortalInfo>, I>>(object: I): VpnPortalInfo {
    const message = createBaseVpnPortalInfo();
    message.vpnType = object.vpnType ?? "";
    message.clientConfig = object.clientConfig ?? "";
    message.connectedClients = object.connectedClients?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetVpnPortalInfoRequest(): GetVpnPortalInfoRequest {
  return { instance: undefined };
}

export const GetVpnPortalInfoRequest: MessageFns<GetVpnPortalInfoRequest> = {
  fromJSON(object: any): GetVpnPortalInfoRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetVpnPortalInfoRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVpnPortalInfoRequest>, I>>(base?: I): GetVpnPortalInfoRequest {
    return GetVpnPortalInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVpnPortalInfoRequest>, I>>(object: I): GetVpnPortalInfoRequest {
    const message = createBaseGetVpnPortalInfoRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetVpnPortalInfoResponse(): GetVpnPortalInfoResponse {
  return { vpnPortalInfo: undefined };
}

export const GetVpnPortalInfoResponse: MessageFns<GetVpnPortalInfoResponse> = {
  fromJSON(object: any): GetVpnPortalInfoResponse {
    return { vpnPortalInfo: isSet(object.vpnPortalInfo) ? VpnPortalInfo.fromJSON(object.vpnPortalInfo) : undefined };
  },

  toJSON(message: GetVpnPortalInfoResponse): unknown {
    const obj: any = {};
    if (message.vpnPortalInfo !== undefined) {
      obj.vpnPortalInfo = VpnPortalInfo.toJSON(message.vpnPortalInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVpnPortalInfoResponse>, I>>(base?: I): GetVpnPortalInfoResponse {
    return GetVpnPortalInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVpnPortalInfoResponse>, I>>(object: I): GetVpnPortalInfoResponse {
    const message = createBaseGetVpnPortalInfoResponse();
    message.vpnPortalInfo = (object.vpnPortalInfo !== undefined && object.vpnPortalInfo !== null)
      ? VpnPortalInfo.fromPartial(object.vpnPortalInfo)
      : undefined;
    return message;
  },
};

function createBaseTcpProxyEntry(): TcpProxyEntry {
  return { src: undefined, dst: undefined, startTime: 0, state: 0, transportType: 0 };
}

export const TcpProxyEntry: MessageFns<TcpProxyEntry> = {
  fromJSON(object: any): TcpProxyEntry {
    return {
      src: isSet(object.src) ? SocketAddr.fromJSON(object.src) : undefined,
      dst: isSet(object.dst) ? SocketAddr.fromJSON(object.dst) : undefined,
      startTime: isSet(object.startTime) ? globalThis.Number(object.startTime) : 0,
      state: isSet(object.state) ? tcpProxyEntryStateFromJSON(object.state) : 0,
      transportType: isSet(object.transportType) ? tcpProxyEntryTransportTypeFromJSON(object.transportType) : 0,
    };
  },

  toJSON(message: TcpProxyEntry): unknown {
    const obj: any = {};
    if (message.src !== undefined) {
      obj.src = SocketAddr.toJSON(message.src);
    }
    if (message.dst !== undefined) {
      obj.dst = SocketAddr.toJSON(message.dst);
    }
    if (message.startTime !== 0) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.state !== 0) {
      obj.state = tcpProxyEntryStateToJSON(message.state);
    }
    if (message.transportType !== 0) {
      obj.transportType = tcpProxyEntryTransportTypeToJSON(message.transportType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TcpProxyEntry>, I>>(base?: I): TcpProxyEntry {
    return TcpProxyEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TcpProxyEntry>, I>>(object: I): TcpProxyEntry {
    const message = createBaseTcpProxyEntry();
    message.src = (object.src !== undefined && object.src !== null) ? SocketAddr.fromPartial(object.src) : undefined;
    message.dst = (object.dst !== undefined && object.dst !== null) ? SocketAddr.fromPartial(object.dst) : undefined;
    message.startTime = object.startTime ?? 0;
    message.state = object.state ?? 0;
    message.transportType = object.transportType ?? 0;
    return message;
  },
};

function createBaseListTcpProxyEntryRequest(): ListTcpProxyEntryRequest {
  return { instance: undefined };
}

export const ListTcpProxyEntryRequest: MessageFns<ListTcpProxyEntryRequest> = {
  fromJSON(object: any): ListTcpProxyEntryRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListTcpProxyEntryRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTcpProxyEntryRequest>, I>>(base?: I): ListTcpProxyEntryRequest {
    return ListTcpProxyEntryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTcpProxyEntryRequest>, I>>(object: I): ListTcpProxyEntryRequest {
    const message = createBaseListTcpProxyEntryRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListTcpProxyEntryResponse(): ListTcpProxyEntryResponse {
  return { entries: [] };
}

export const ListTcpProxyEntryResponse: MessageFns<ListTcpProxyEntryResponse> = {
  fromJSON(object: any): ListTcpProxyEntryResponse {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => TcpProxyEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListTcpProxyEntryResponse): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => TcpProxyEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTcpProxyEntryResponse>, I>>(base?: I): ListTcpProxyEntryResponse {
    return ListTcpProxyEntryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTcpProxyEntryResponse>, I>>(object: I): ListTcpProxyEntryResponse {
    const message = createBaseListTcpProxyEntryResponse();
    message.entries = object.entries?.map((e) => TcpProxyEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetAclStatsRequest(): GetAclStatsRequest {
  return { instance: undefined };
}

export const GetAclStatsRequest: MessageFns<GetAclStatsRequest> = {
  fromJSON(object: any): GetAclStatsRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetAclStatsRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAclStatsRequest>, I>>(base?: I): GetAclStatsRequest {
    return GetAclStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAclStatsRequest>, I>>(object: I): GetAclStatsRequest {
    const message = createBaseGetAclStatsRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetAclStatsResponse(): GetAclStatsResponse {
  return { aclStats: undefined };
}

export const GetAclStatsResponse: MessageFns<GetAclStatsResponse> = {
  fromJSON(object: any): GetAclStatsResponse {
    return { aclStats: isSet(object.aclStats) ? AclStats.fromJSON(object.aclStats) : undefined };
  },

  toJSON(message: GetAclStatsResponse): unknown {
    const obj: any = {};
    if (message.aclStats !== undefined) {
      obj.aclStats = AclStats.toJSON(message.aclStats);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAclStatsResponse>, I>>(base?: I): GetAclStatsResponse {
    return GetAclStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAclStatsResponse>, I>>(object: I): GetAclStatsResponse {
    const message = createBaseGetAclStatsResponse();
    message.aclStats = (object.aclStats !== undefined && object.aclStats !== null)
      ? AclStats.fromPartial(object.aclStats)
      : undefined;
    return message;
  },
};

function createBaseGetWhitelistRequest(): GetWhitelistRequest {
  return { instance: undefined };
}

export const GetWhitelistRequest: MessageFns<GetWhitelistRequest> = {
  fromJSON(object: any): GetWhitelistRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetWhitelistRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWhitelistRequest>, I>>(base?: I): GetWhitelistRequest {
    return GetWhitelistRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWhitelistRequest>, I>>(object: I): GetWhitelistRequest {
    const message = createBaseGetWhitelistRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetWhitelistResponse(): GetWhitelistResponse {
  return { tcpPorts: [], udpPorts: [] };
}

export const GetWhitelistResponse: MessageFns<GetWhitelistResponse> = {
  fromJSON(object: any): GetWhitelistResponse {
    return {
      tcpPorts: globalThis.Array.isArray(object?.tcpPorts) ? object.tcpPorts.map((e: any) => globalThis.String(e)) : [],
      udpPorts: globalThis.Array.isArray(object?.udpPorts) ? object.udpPorts.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetWhitelistResponse): unknown {
    const obj: any = {};
    if (message.tcpPorts?.length) {
      obj.tcpPorts = message.tcpPorts;
    }
    if (message.udpPorts?.length) {
      obj.udpPorts = message.udpPorts;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWhitelistResponse>, I>>(base?: I): GetWhitelistResponse {
    return GetWhitelistResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWhitelistResponse>, I>>(object: I): GetWhitelistResponse {
    const message = createBaseGetWhitelistResponse();
    message.tcpPorts = object.tcpPorts?.map((e) => e) || [];
    message.udpPorts = object.udpPorts?.map((e) => e) || [];
    return message;
  },
};

function createBaseListPortForwardRequest(): ListPortForwardRequest {
  return { instance: undefined };
}

export const ListPortForwardRequest: MessageFns<ListPortForwardRequest> = {
  fromJSON(object: any): ListPortForwardRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: ListPortForwardRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPortForwardRequest>, I>>(base?: I): ListPortForwardRequest {
    return ListPortForwardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortForwardRequest>, I>>(object: I): ListPortForwardRequest {
    const message = createBaseListPortForwardRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseListPortForwardResponse(): ListPortForwardResponse {
  return { cfgs: [] };
}

export const ListPortForwardResponse: MessageFns<ListPortForwardResponse> = {
  fromJSON(object: any): ListPortForwardResponse {
    return {
      cfgs: globalThis.Array.isArray(object?.cfgs)
        ? object.cfgs.map((e: any) => PortForwardConfigPb.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListPortForwardResponse): unknown {
    const obj: any = {};
    if (message.cfgs?.length) {
      obj.cfgs = message.cfgs.map((e) => PortForwardConfigPb.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPortForwardResponse>, I>>(base?: I): ListPortForwardResponse {
    return ListPortForwardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortForwardResponse>, I>>(object: I): ListPortForwardResponse {
    const message = createBaseListPortForwardResponse();
    message.cfgs = object.cfgs?.map((e) => PortForwardConfigPb.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMetricSnapshot(): MetricSnapshot {
  return { name: "", value: 0, labels: {} };
}

export const MetricSnapshot: MessageFns<MetricSnapshot> = {
  fromJSON(object: any): MetricSnapshot {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      labels: isObject(object.labels)
        ? Object.entries(object.labels).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: MetricSnapshot): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.labels) {
      const entries = Object.entries(message.labels);
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetricSnapshot>, I>>(base?: I): MetricSnapshot {
    return MetricSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetricSnapshot>, I>>(object: I): MetricSnapshot {
    const message = createBaseMetricSnapshot();
    message.name = object.name ?? "";
    message.value = object.value ?? 0;
    message.labels = Object.entries(object.labels ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseMetricSnapshot_LabelsEntry(): MetricSnapshot_LabelsEntry {
  return { key: "", value: "" };
}

export const MetricSnapshot_LabelsEntry: MessageFns<MetricSnapshot_LabelsEntry> = {
  fromJSON(object: any): MetricSnapshot_LabelsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: MetricSnapshot_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetricSnapshot_LabelsEntry>, I>>(base?: I): MetricSnapshot_LabelsEntry {
    return MetricSnapshot_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetricSnapshot_LabelsEntry>, I>>(object: I): MetricSnapshot_LabelsEntry {
    const message = createBaseMetricSnapshot_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseGetStatsRequest(): GetStatsRequest {
  return { instance: undefined };
}

export const GetStatsRequest: MessageFns<GetStatsRequest> = {
  fromJSON(object: any): GetStatsRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetStatsRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatsRequest>, I>>(base?: I): GetStatsRequest {
    return GetStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatsRequest>, I>>(object: I): GetStatsRequest {
    const message = createBaseGetStatsRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetStatsResponse(): GetStatsResponse {
  return { metrics: [] };
}

export const GetStatsResponse: MessageFns<GetStatsResponse> = {
  fromJSON(object: any): GetStatsResponse {
    return {
      metrics: globalThis.Array.isArray(object?.metrics)
        ? object.metrics.map((e: any) => MetricSnapshot.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetStatsResponse): unknown {
    const obj: any = {};
    if (message.metrics?.length) {
      obj.metrics = message.metrics.map((e) => MetricSnapshot.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatsResponse>, I>>(base?: I): GetStatsResponse {
    return GetStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatsResponse>, I>>(object: I): GetStatsResponse {
    const message = createBaseGetStatsResponse();
    message.metrics = object.metrics?.map((e) => MetricSnapshot.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPrometheusStatsRequest(): GetPrometheusStatsRequest {
  return { instance: undefined };
}

export const GetPrometheusStatsRequest: MessageFns<GetPrometheusStatsRequest> = {
  fromJSON(object: any): GetPrometheusStatsRequest {
    return { instance: isSet(object.instance) ? InstanceIdentifier.fromJSON(object.instance) : undefined };
  },

  toJSON(message: GetPrometheusStatsRequest): unknown {
    const obj: any = {};
    if (message.instance !== undefined) {
      obj.instance = InstanceIdentifier.toJSON(message.instance);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPrometheusStatsRequest>, I>>(base?: I): GetPrometheusStatsRequest {
    return GetPrometheusStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPrometheusStatsRequest>, I>>(object: I): GetPrometheusStatsRequest {
    const message = createBaseGetPrometheusStatsRequest();
    message.instance = (object.instance !== undefined && object.instance !== null)
      ? InstanceIdentifier.fromPartial(object.instance)
      : undefined;
    return message;
  },
};

function createBaseGetPrometheusStatsResponse(): GetPrometheusStatsResponse {
  return { prometheusText: "" };
}

export const GetPrometheusStatsResponse: MessageFns<GetPrometheusStatsResponse> = {
  fromJSON(object: any): GetPrometheusStatsResponse {
    return { prometheusText: isSet(object.prometheusText) ? globalThis.String(object.prometheusText) : "" };
  },

  toJSON(message: GetPrometheusStatsResponse): unknown {
    const obj: any = {};
    if (message.prometheusText !== "") {
      obj.prometheusText = message.prometheusText;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPrometheusStatsResponse>, I>>(base?: I): GetPrometheusStatsResponse {
    return GetPrometheusStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPrometheusStatsResponse>, I>>(object: I): GetPrometheusStatsResponse {
    const message = createBaseGetPrometheusStatsResponse();
    message.prometheusText = object.prometheusText ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
