// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: api_manage.proto

/* eslint-disable */
import { PeerInfo, PeerRoutePair, Route } from "./api_instance";
import {
  CompressionAlgoPb,
  compressionAlgoPbFromJSON,
  compressionAlgoPbToJSON,
  Ipv4Inet,
  SecureModeConfig,
  StunInfo,
  Url,
  UUID,
} from "./common";
import { GetIpListResponse, RouteForeignNetworkSummary } from "./peer_rpc";

export const protobufPackage = "api.manage";

export enum NetworkingMethod {
  PublicServer = 0,
  Manual = 1,
  Standalone = 2,
  UNRECOGNIZED = -1,
}

export function networkingMethodFromJSON(object: any): NetworkingMethod {
  switch (object) {
    case 0:
    case "PublicServer":
      return NetworkingMethod.PublicServer;
    case 1:
    case "Manual":
      return NetworkingMethod.Manual;
    case 2:
    case "Standalone":
      return NetworkingMethod.Standalone;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NetworkingMethod.UNRECOGNIZED;
  }
}

export function networkingMethodToJSON(object: NetworkingMethod): string {
  switch (object) {
    case NetworkingMethod.PublicServer:
      return "PublicServer";
    case NetworkingMethod.Manual:
      return "Manual";
    case NetworkingMethod.Standalone:
      return "Standalone";
    case NetworkingMethod.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NetworkConfig {
  instance_id?: string | undefined;
  dhcp?: boolean | undefined;
  virtual_ipv4?: string | undefined;
  network_length?: number | undefined;
  hostname?: string | undefined;
  network_name?: string | undefined;
  network_secret?: string | undefined;
  networking_method?: NetworkingMethod | undefined;
  public_server_url?: string | undefined;
  peer_urls: string[];
  proxy_cidrs: string[];
  enable_vpn_portal?: boolean | undefined;
  vpn_portal_listen_port?: number | undefined;
  vpn_portal_client_network_addr?: string | undefined;
  vpn_portal_client_network_len?: number | undefined;
  advanced_settings?: boolean | undefined;
  listener_urls: string[];
  /** optional int32 rpc_port = 18; */
  latency_first?: boolean | undefined;
  dev_name?: string | undefined;
  use_smoltcp?: boolean | undefined;
  disable_ipv6?: boolean | undefined;
  enable_kcp_proxy?: boolean | undefined;
  disable_kcp_input?: boolean | undefined;
  disable_p2p?: boolean | undefined;
  bind_device?: boolean | undefined;
  no_tun?: boolean | undefined;
  enable_exit_node?: boolean | undefined;
  relay_all_peer_rpc?: boolean | undefined;
  multi_thread?: boolean | undefined;
  enable_relay_network_whitelist?: boolean | undefined;
  relay_network_whitelist: string[];
  enable_manual_routes?: boolean | undefined;
  routes: string[];
  exit_nodes: string[];
  proxy_forward_by_system?: boolean | undefined;
  disable_encryption?: boolean | undefined;
  enable_socks5?: boolean | undefined;
  socks5_port?: number | undefined;
  disable_udp_hole_punching?: boolean | undefined;
  mtu?: number | undefined;
  mapped_listeners: string[];
  enable_magic_dns?: boolean | undefined;
  enable_private_mode?: boolean | undefined;
  enable_quic_proxy?: boolean | undefined;
  disable_quic_input?:
    | boolean
    | undefined;
  /** @deprecated */
  quic_listen_port?: number | undefined;
  port_forwards: PortForwardConfig[];
  disable_sym_hole_punching?: boolean | undefined;
  p2p_only?: boolean | undefined;
  data_compress_algo?: CompressionAlgoPb | undefined;
  encryption_algorithm?: string | undefined;
  disable_tcp_hole_punching?: boolean | undefined;
  secure_mode: SecureModeConfig | undefined;
}

export interface PortForwardConfig {
  bind_ip: string;
  bind_port: number;
  dst_ip: string;
  dst_port: number;
  proto: string;
}

export interface MyNodeInfo {
  virtual_ipv4: Ipv4Inet | undefined;
  hostname: string;
  version: string;
  ips: GetIpListResponse | undefined;
  stun_info: StunInfo | undefined;
  listeners: Url[];
  vpn_portal_cfg?: string | undefined;
  peer_id: number;
}

export interface NetworkInstanceRunningInfo {
  dev_name: string;
  my_node_info: MyNodeInfo | undefined;
  events: string[];
  routes: Route[];
  peers: PeerInfo[];
  peer_route_pairs: PeerRoutePair[];
  running: boolean;
  error_msg?: string | undefined;
  foreign_network_summary: RouteForeignNetworkSummary | undefined;
}

export interface NetworkInstanceRunningInfoMap {
  map: { [key: string]: NetworkInstanceRunningInfo };
}

export interface NetworkInstanceRunningInfoMap_MapEntry {
  key: string;
  value: NetworkInstanceRunningInfo | undefined;
}

export interface NetworkMeta {
  inst_id: UUID | undefined;
  network_name: string;
  config_permission: number;
}

export interface ValidateConfigRequest {
  config: NetworkConfig | undefined;
}

export interface ValidateConfigResponse {
  toml_config: string;
}

export interface RunNetworkInstanceRequest {
  inst_id: UUID | undefined;
  config: NetworkConfig | undefined;
  overwrite: boolean;
}

export interface RunNetworkInstanceResponse {
  inst_id: UUID | undefined;
}

export interface RetainNetworkInstanceRequest {
  inst_ids: UUID[];
}

export interface RetainNetworkInstanceResponse {
  remain_inst_ids: UUID[];
}

export interface CollectNetworkInfoRequest {
  inst_ids: UUID[];
}

export interface CollectNetworkInfoResponse {
  info: NetworkInstanceRunningInfoMap | undefined;
}

export interface ListNetworkInstanceRequest {
}

export interface ListNetworkInstanceResponse {
  inst_ids: UUID[];
}

export interface DeleteNetworkInstanceRequest {
  inst_ids: UUID[];
}

export interface DeleteNetworkInstanceResponse {
  remain_inst_ids: UUID[];
}

export interface GetNetworkInstanceConfigRequest {
  inst_id: UUID | undefined;
}

export interface GetNetworkInstanceConfigResponse {
  config: NetworkConfig | undefined;
}

export interface ListNetworkInstanceMetaRequest {
  inst_ids: UUID[];
}

export interface ListNetworkInstanceMetaResponse {
  metas: NetworkMeta[];
}

function createBaseNetworkConfig(): NetworkConfig {
  return {
    instance_id: undefined,
    dhcp: undefined,
    virtual_ipv4: undefined,
    network_length: undefined,
    hostname: undefined,
    network_name: undefined,
    network_secret: undefined,
    networking_method: undefined,
    public_server_url: undefined,
    peer_urls: [],
    proxy_cidrs: [],
    enable_vpn_portal: undefined,
    vpn_portal_listen_port: undefined,
    vpn_portal_client_network_addr: undefined,
    vpn_portal_client_network_len: undefined,
    advanced_settings: undefined,
    listener_urls: [],
    latency_first: undefined,
    dev_name: undefined,
    use_smoltcp: undefined,
    disable_ipv6: undefined,
    enable_kcp_proxy: undefined,
    disable_kcp_input: undefined,
    disable_p2p: undefined,
    bind_device: undefined,
    no_tun: undefined,
    enable_exit_node: undefined,
    relay_all_peer_rpc: undefined,
    multi_thread: undefined,
    enable_relay_network_whitelist: undefined,
    relay_network_whitelist: [],
    enable_manual_routes: undefined,
    routes: [],
    exit_nodes: [],
    proxy_forward_by_system: undefined,
    disable_encryption: undefined,
    enable_socks5: undefined,
    socks5_port: undefined,
    disable_udp_hole_punching: undefined,
    mtu: undefined,
    mapped_listeners: [],
    enable_magic_dns: undefined,
    enable_private_mode: undefined,
    enable_quic_proxy: undefined,
    disable_quic_input: undefined,
    quic_listen_port: undefined,
    port_forwards: [],
    disable_sym_hole_punching: undefined,
    p2p_only: undefined,
    data_compress_algo: undefined,
    encryption_algorithm: undefined,
    disable_tcp_hole_punching: undefined,
    secure_mode: undefined,
  };
}

export const NetworkConfig: MessageFns<NetworkConfig> = {
  fromJSON(object: any): NetworkConfig {
    return {
      instance_id: isSet(object.instanceId)
        ? globalThis.String(object.instanceId)
        : isSet(object.instance_id)
        ? globalThis.String(object.instance_id)
        : undefined,
      dhcp: isSet(object.dhcp) ? globalThis.Boolean(object.dhcp) : undefined,
      virtual_ipv4: isSet(object.virtualIpv4)
        ? globalThis.String(object.virtualIpv4)
        : isSet(object.virtual_ipv4)
        ? globalThis.String(object.virtual_ipv4)
        : undefined,
      network_length: isSet(object.networkLength)
        ? globalThis.Number(object.networkLength)
        : isSet(object.network_length)
        ? globalThis.Number(object.network_length)
        : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : undefined,
      network_name: isSet(object.networkName)
        ? globalThis.String(object.networkName)
        : isSet(object.network_name)
        ? globalThis.String(object.network_name)
        : undefined,
      network_secret: isSet(object.networkSecret)
        ? globalThis.String(object.networkSecret)
        : isSet(object.network_secret)
        ? globalThis.String(object.network_secret)
        : undefined,
      networking_method: isSet(object.networkingMethod)
        ? networkingMethodFromJSON(object.networkingMethod)
        : isSet(object.networking_method)
        ? networkingMethodFromJSON(object.networking_method)
        : undefined,
      public_server_url: isSet(object.publicServerUrl)
        ? globalThis.String(object.publicServerUrl)
        : isSet(object.public_server_url)
        ? globalThis.String(object.public_server_url)
        : undefined,
      peer_urls: globalThis.Array.isArray(object?.peerUrls)
        ? object.peerUrls.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.peer_urls)
        ? object.peer_urls.map((e: any) => globalThis.String(e))
        : [],
      proxy_cidrs: globalThis.Array.isArray(object?.proxyCidrs)
        ? object.proxyCidrs.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.proxy_cidrs)
        ? object.proxy_cidrs.map((e: any) => globalThis.String(e))
        : [],
      enable_vpn_portal: isSet(object.enableVpnPortal)
        ? globalThis.Boolean(object.enableVpnPortal)
        : isSet(object.enable_vpn_portal)
        ? globalThis.Boolean(object.enable_vpn_portal)
        : undefined,
      vpn_portal_listen_port: isSet(object.vpnPortalListenPort)
        ? globalThis.Number(object.vpnPortalListenPort)
        : isSet(object.vpn_portal_listen_port)
        ? globalThis.Number(object.vpn_portal_listen_port)
        : undefined,
      vpn_portal_client_network_addr: isSet(object.vpnPortalClientNetworkAddr)
        ? globalThis.String(object.vpnPortalClientNetworkAddr)
        : isSet(object.vpn_portal_client_network_addr)
        ? globalThis.String(object.vpn_portal_client_network_addr)
        : undefined,
      vpn_portal_client_network_len: isSet(object.vpnPortalClientNetworkLen)
        ? globalThis.Number(object.vpnPortalClientNetworkLen)
        : isSet(object.vpn_portal_client_network_len)
        ? globalThis.Number(object.vpn_portal_client_network_len)
        : undefined,
      advanced_settings: isSet(object.advancedSettings)
        ? globalThis.Boolean(object.advancedSettings)
        : isSet(object.advanced_settings)
        ? globalThis.Boolean(object.advanced_settings)
        : undefined,
      listener_urls: globalThis.Array.isArray(object?.listenerUrls)
        ? object.listenerUrls.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.listener_urls)
        ? object.listener_urls.map((e: any) => globalThis.String(e))
        : [],
      latency_first: isSet(object.latencyFirst)
        ? globalThis.Boolean(object.latencyFirst)
        : isSet(object.latency_first)
        ? globalThis.Boolean(object.latency_first)
        : undefined,
      dev_name: isSet(object.devName)
        ? globalThis.String(object.devName)
        : isSet(object.dev_name)
        ? globalThis.String(object.dev_name)
        : undefined,
      use_smoltcp: isSet(object.useSmoltcp)
        ? globalThis.Boolean(object.useSmoltcp)
        : isSet(object.use_smoltcp)
        ? globalThis.Boolean(object.use_smoltcp)
        : undefined,
      disable_ipv6: isSet(object.disableIpv6)
        ? globalThis.Boolean(object.disableIpv6)
        : isSet(object.disable_ipv6)
        ? globalThis.Boolean(object.disable_ipv6)
        : undefined,
      enable_kcp_proxy: isSet(object.enableKcpProxy)
        ? globalThis.Boolean(object.enableKcpProxy)
        : isSet(object.enable_kcp_proxy)
        ? globalThis.Boolean(object.enable_kcp_proxy)
        : undefined,
      disable_kcp_input: isSet(object.disableKcpInput)
        ? globalThis.Boolean(object.disableKcpInput)
        : isSet(object.disable_kcp_input)
        ? globalThis.Boolean(object.disable_kcp_input)
        : undefined,
      disable_p2p: isSet(object.disableP2p)
        ? globalThis.Boolean(object.disableP2p)
        : isSet(object.disable_p2p)
        ? globalThis.Boolean(object.disable_p2p)
        : undefined,
      bind_device: isSet(object.bindDevice)
        ? globalThis.Boolean(object.bindDevice)
        : isSet(object.bind_device)
        ? globalThis.Boolean(object.bind_device)
        : undefined,
      no_tun: isSet(object.noTun)
        ? globalThis.Boolean(object.noTun)
        : isSet(object.no_tun)
        ? globalThis.Boolean(object.no_tun)
        : undefined,
      enable_exit_node: isSet(object.enableExitNode)
        ? globalThis.Boolean(object.enableExitNode)
        : isSet(object.enable_exit_node)
        ? globalThis.Boolean(object.enable_exit_node)
        : undefined,
      relay_all_peer_rpc: isSet(object.relayAllPeerRpc)
        ? globalThis.Boolean(object.relayAllPeerRpc)
        : isSet(object.relay_all_peer_rpc)
        ? globalThis.Boolean(object.relay_all_peer_rpc)
        : undefined,
      multi_thread: isSet(object.multiThread)
        ? globalThis.Boolean(object.multiThread)
        : isSet(object.multi_thread)
        ? globalThis.Boolean(object.multi_thread)
        : undefined,
      enable_relay_network_whitelist: isSet(object.enableRelayNetworkWhitelist)
        ? globalThis.Boolean(object.enableRelayNetworkWhitelist)
        : isSet(object.enable_relay_network_whitelist)
        ? globalThis.Boolean(object.enable_relay_network_whitelist)
        : undefined,
      relay_network_whitelist: globalThis.Array.isArray(object?.relayNetworkWhitelist)
        ? object.relayNetworkWhitelist.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.relay_network_whitelist)
        ? object.relay_network_whitelist.map((e: any) => globalThis.String(e))
        : [],
      enable_manual_routes: isSet(object.enableManualRoutes)
        ? globalThis.Boolean(object.enableManualRoutes)
        : isSet(object.enable_manual_routes)
        ? globalThis.Boolean(object.enable_manual_routes)
        : undefined,
      routes: globalThis.Array.isArray(object?.routes)
        ? object.routes.map((e: any) => globalThis.String(e))
        : [],
      exit_nodes: globalThis.Array.isArray(object?.exitNodes)
        ? object.exitNodes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.exit_nodes)
        ? object.exit_nodes.map((e: any) => globalThis.String(e))
        : [],
      proxy_forward_by_system: isSet(object.proxyForwardBySystem)
        ? globalThis.Boolean(object.proxyForwardBySystem)
        : isSet(object.proxy_forward_by_system)
        ? globalThis.Boolean(object.proxy_forward_by_system)
        : undefined,
      disable_encryption: isSet(object.disableEncryption)
        ? globalThis.Boolean(object.disableEncryption)
        : isSet(object.disable_encryption)
        ? globalThis.Boolean(object.disable_encryption)
        : undefined,
      enable_socks5: isSet(object.enableSocks5)
        ? globalThis.Boolean(object.enableSocks5)
        : isSet(object.enable_socks5)
        ? globalThis.Boolean(object.enable_socks5)
        : undefined,
      socks5_port: isSet(object.socks5Port)
        ? globalThis.Number(object.socks5Port)
        : isSet(object.socks5_port)
        ? globalThis.Number(object.socks5_port)
        : undefined,
      disable_udp_hole_punching: isSet(object.disableUdpHolePunching)
        ? globalThis.Boolean(object.disableUdpHolePunching)
        : isSet(object.disable_udp_hole_punching)
        ? globalThis.Boolean(object.disable_udp_hole_punching)
        : undefined,
      mtu: isSet(object.mtu) ? globalThis.Number(object.mtu) : undefined,
      mapped_listeners: globalThis.Array.isArray(object?.mappedListeners)
        ? object.mappedListeners.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.mapped_listeners)
        ? object.mapped_listeners.map((e: any) => globalThis.String(e))
        : [],
      enable_magic_dns: isSet(object.enableMagicDns)
        ? globalThis.Boolean(object.enableMagicDns)
        : isSet(object.enable_magic_dns)
        ? globalThis.Boolean(object.enable_magic_dns)
        : undefined,
      enable_private_mode: isSet(object.enablePrivateMode)
        ? globalThis.Boolean(object.enablePrivateMode)
        : isSet(object.enable_private_mode)
        ? globalThis.Boolean(object.enable_private_mode)
        : undefined,
      enable_quic_proxy: isSet(object.enableQuicProxy)
        ? globalThis.Boolean(object.enableQuicProxy)
        : isSet(object.enable_quic_proxy)
        ? globalThis.Boolean(object.enable_quic_proxy)
        : undefined,
      disable_quic_input: isSet(object.disableQuicInput)
        ? globalThis.Boolean(object.disableQuicInput)
        : isSet(object.disable_quic_input)
        ? globalThis.Boolean(object.disable_quic_input)
        : undefined,
      quic_listen_port: isSet(object.quicListenPort)
        ? globalThis.Number(object.quicListenPort)
        : isSet(object.quic_listen_port)
        ? globalThis.Number(object.quic_listen_port)
        : undefined,
      port_forwards: globalThis.Array.isArray(object?.portForwards)
        ? object.portForwards.map((e: any) => PortForwardConfig.fromJSON(e))
        : globalThis.Array.isArray(object?.port_forwards)
        ? object.port_forwards.map((e: any) => PortForwardConfig.fromJSON(e))
        : [],
      disable_sym_hole_punching: isSet(object.disableSymHolePunching)
        ? globalThis.Boolean(object.disableSymHolePunching)
        : isSet(object.disable_sym_hole_punching)
        ? globalThis.Boolean(object.disable_sym_hole_punching)
        : undefined,
      p2p_only: isSet(object.p2pOnly)
        ? globalThis.Boolean(object.p2pOnly)
        : isSet(object.p2p_only)
        ? globalThis.Boolean(object.p2p_only)
        : undefined,
      data_compress_algo: isSet(object.dataCompressAlgo)
        ? compressionAlgoPbFromJSON(object.dataCompressAlgo)
        : isSet(object.data_compress_algo)
        ? compressionAlgoPbFromJSON(object.data_compress_algo)
        : undefined,
      encryption_algorithm: isSet(object.encryptionAlgorithm)
        ? globalThis.String(object.encryptionAlgorithm)
        : isSet(object.encryption_algorithm)
        ? globalThis.String(object.encryption_algorithm)
        : undefined,
      disable_tcp_hole_punching: isSet(object.disableTcpHolePunching)
        ? globalThis.Boolean(object.disableTcpHolePunching)
        : isSet(object.disable_tcp_hole_punching)
        ? globalThis.Boolean(object.disable_tcp_hole_punching)
        : undefined,
      secure_mode: isSet(object.secureMode)
        ? SecureModeConfig.fromJSON(object.secureMode)
        : isSet(object.secure_mode)
        ? SecureModeConfig.fromJSON(object.secure_mode)
        : undefined,
    };
  },

  toJSON(message: NetworkConfig): unknown {
    const obj: any = {};
    if (message.instance_id !== undefined) {
      obj.instanceId = message.instance_id;
    }
    if (message.dhcp !== undefined) {
      obj.dhcp = message.dhcp;
    }
    if (message.virtual_ipv4 !== undefined) {
      obj.virtualIpv4 = message.virtual_ipv4;
    }
    if (message.network_length !== undefined) {
      obj.networkLength = Math.round(message.network_length);
    }
    if (message.hostname !== undefined) {
      obj.hostname = message.hostname;
    }
    if (message.network_name !== undefined) {
      obj.networkName = message.network_name;
    }
    if (message.network_secret !== undefined) {
      obj.networkSecret = message.network_secret;
    }
    if (message.networking_method !== undefined) {
      obj.networkingMethod = networkingMethodToJSON(message.networking_method);
    }
    if (message.public_server_url !== undefined) {
      obj.publicServerUrl = message.public_server_url;
    }
    if (message.peer_urls?.length) {
      obj.peerUrls = message.peer_urls;
    }
    if (message.proxy_cidrs?.length) {
      obj.proxyCidrs = message.proxy_cidrs;
    }
    if (message.enable_vpn_portal !== undefined) {
      obj.enableVpnPortal = message.enable_vpn_portal;
    }
    if (message.vpn_portal_listen_port !== undefined) {
      obj.vpnPortalListenPort = Math.round(message.vpn_portal_listen_port);
    }
    if (message.vpn_portal_client_network_addr !== undefined) {
      obj.vpnPortalClientNetworkAddr = message.vpn_portal_client_network_addr;
    }
    if (message.vpn_portal_client_network_len !== undefined) {
      obj.vpnPortalClientNetworkLen = Math.round(message.vpn_portal_client_network_len);
    }
    if (message.advanced_settings !== undefined) {
      obj.advancedSettings = message.advanced_settings;
    }
    if (message.listener_urls?.length) {
      obj.listenerUrls = message.listener_urls;
    }
    if (message.latency_first !== undefined) {
      obj.latencyFirst = message.latency_first;
    }
    if (message.dev_name !== undefined) {
      obj.devName = message.dev_name;
    }
    if (message.use_smoltcp !== undefined) {
      obj.useSmoltcp = message.use_smoltcp;
    }
    if (message.disable_ipv6 !== undefined) {
      obj.disableIpv6 = message.disable_ipv6;
    }
    if (message.enable_kcp_proxy !== undefined) {
      obj.enableKcpProxy = message.enable_kcp_proxy;
    }
    if (message.disable_kcp_input !== undefined) {
      obj.disableKcpInput = message.disable_kcp_input;
    }
    if (message.disable_p2p !== undefined) {
      obj.disableP2p = message.disable_p2p;
    }
    if (message.bind_device !== undefined) {
      obj.bindDevice = message.bind_device;
    }
    if (message.no_tun !== undefined) {
      obj.noTun = message.no_tun;
    }
    if (message.enable_exit_node !== undefined) {
      obj.enableExitNode = message.enable_exit_node;
    }
    if (message.relay_all_peer_rpc !== undefined) {
      obj.relayAllPeerRpc = message.relay_all_peer_rpc;
    }
    if (message.multi_thread !== undefined) {
      obj.multiThread = message.multi_thread;
    }
    if (message.enable_relay_network_whitelist !== undefined) {
      obj.enableRelayNetworkWhitelist = message.enable_relay_network_whitelist;
    }
    if (message.relay_network_whitelist?.length) {
      obj.relayNetworkWhitelist = message.relay_network_whitelist;
    }
    if (message.enable_manual_routes !== undefined) {
      obj.enableManualRoutes = message.enable_manual_routes;
    }
    if (message.routes?.length) {
      obj.routes = message.routes;
    }
    if (message.exit_nodes?.length) {
      obj.exitNodes = message.exit_nodes;
    }
    if (message.proxy_forward_by_system !== undefined) {
      obj.proxyForwardBySystem = message.proxy_forward_by_system;
    }
    if (message.disable_encryption !== undefined) {
      obj.disableEncryption = message.disable_encryption;
    }
    if (message.enable_socks5 !== undefined) {
      obj.enableSocks5 = message.enable_socks5;
    }
    if (message.socks5_port !== undefined) {
      obj.socks5Port = Math.round(message.socks5_port);
    }
    if (message.disable_udp_hole_punching !== undefined) {
      obj.disableUdpHolePunching = message.disable_udp_hole_punching;
    }
    if (message.mtu !== undefined) {
      obj.mtu = Math.round(message.mtu);
    }
    if (message.mapped_listeners?.length) {
      obj.mappedListeners = message.mapped_listeners;
    }
    if (message.enable_magic_dns !== undefined) {
      obj.enableMagicDns = message.enable_magic_dns;
    }
    if (message.enable_private_mode !== undefined) {
      obj.enablePrivateMode = message.enable_private_mode;
    }
    if (message.enable_quic_proxy !== undefined) {
      obj.enableQuicProxy = message.enable_quic_proxy;
    }
    if (message.disable_quic_input !== undefined) {
      obj.disableQuicInput = message.disable_quic_input;
    }
    if (message.quic_listen_port !== undefined) {
      obj.quicListenPort = Math.round(message.quic_listen_port);
    }
    if (message.port_forwards?.length) {
      obj.portForwards = message.port_forwards.map((e) => PortForwardConfig.toJSON(e));
    }
    if (message.disable_sym_hole_punching !== undefined) {
      obj.disableSymHolePunching = message.disable_sym_hole_punching;
    }
    if (message.p2p_only !== undefined) {
      obj.p2pOnly = message.p2p_only;
    }
    if (message.data_compress_algo !== undefined) {
      obj.dataCompressAlgo = compressionAlgoPbToJSON(message.data_compress_algo);
    }
    if (message.encryption_algorithm !== undefined) {
      obj.encryptionAlgorithm = message.encryption_algorithm;
    }
    if (message.disable_tcp_hole_punching !== undefined) {
      obj.disableTcpHolePunching = message.disable_tcp_hole_punching;
    }
    if (message.secure_mode !== undefined) {
      obj.secureMode = SecureModeConfig.toJSON(message.secure_mode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkConfig>, I>>(base?: I): NetworkConfig {
    return NetworkConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkConfig>, I>>(object: I): NetworkConfig {
    const message = createBaseNetworkConfig();
    message.instance_id = object.instance_id ?? undefined;
    message.dhcp = object.dhcp ?? undefined;
    message.virtual_ipv4 = object.virtual_ipv4 ?? undefined;
    message.network_length = object.network_length ?? undefined;
    message.hostname = object.hostname ?? undefined;
    message.network_name = object.network_name ?? undefined;
    message.network_secret = object.network_secret ?? undefined;
    message.networking_method = object.networking_method ?? undefined;
    message.public_server_url = object.public_server_url ?? undefined;
    message.peer_urls = object.peer_urls?.map((e) => e) || [];
    message.proxy_cidrs = object.proxy_cidrs?.map((e) => e) || [];
    message.enable_vpn_portal = object.enable_vpn_portal ?? undefined;
    message.vpn_portal_listen_port = object.vpn_portal_listen_port ?? undefined;
    message.vpn_portal_client_network_addr = object.vpn_portal_client_network_addr ?? undefined;
    message.vpn_portal_client_network_len = object.vpn_portal_client_network_len ?? undefined;
    message.advanced_settings = object.advanced_settings ?? undefined;
    message.listener_urls = object.listener_urls?.map((e) => e) || [];
    message.latency_first = object.latency_first ?? undefined;
    message.dev_name = object.dev_name ?? undefined;
    message.use_smoltcp = object.use_smoltcp ?? undefined;
    message.disable_ipv6 = object.disable_ipv6 ?? undefined;
    message.enable_kcp_proxy = object.enable_kcp_proxy ?? undefined;
    message.disable_kcp_input = object.disable_kcp_input ?? undefined;
    message.disable_p2p = object.disable_p2p ?? undefined;
    message.bind_device = object.bind_device ?? undefined;
    message.no_tun = object.no_tun ?? undefined;
    message.enable_exit_node = object.enable_exit_node ?? undefined;
    message.relay_all_peer_rpc = object.relay_all_peer_rpc ?? undefined;
    message.multi_thread = object.multi_thread ?? undefined;
    message.enable_relay_network_whitelist = object.enable_relay_network_whitelist ?? undefined;
    message.relay_network_whitelist = object.relay_network_whitelist?.map((e) => e) || [];
    message.enable_manual_routes = object.enable_manual_routes ?? undefined;
    message.routes = object.routes?.map((e) => e) || [];
    message.exit_nodes = object.exit_nodes?.map((e) => e) || [];
    message.proxy_forward_by_system = object.proxy_forward_by_system ?? undefined;
    message.disable_encryption = object.disable_encryption ?? undefined;
    message.enable_socks5 = object.enable_socks5 ?? undefined;
    message.socks5_port = object.socks5_port ?? undefined;
    message.disable_udp_hole_punching = object.disable_udp_hole_punching ?? undefined;
    message.mtu = object.mtu ?? undefined;
    message.mapped_listeners = object.mapped_listeners?.map((e) => e) || [];
    message.enable_magic_dns = object.enable_magic_dns ?? undefined;
    message.enable_private_mode = object.enable_private_mode ?? undefined;
    message.enable_quic_proxy = object.enable_quic_proxy ?? undefined;
    message.disable_quic_input = object.disable_quic_input ?? undefined;
    message.quic_listen_port = object.quic_listen_port ?? undefined;
    message.port_forwards = object.port_forwards?.map((e) => PortForwardConfig.fromPartial(e)) || [];
    message.disable_sym_hole_punching = object.disable_sym_hole_punching ?? undefined;
    message.p2p_only = object.p2p_only ?? undefined;
    message.data_compress_algo = object.data_compress_algo ?? undefined;
    message.encryption_algorithm = object.encryption_algorithm ?? undefined;
    message.disable_tcp_hole_punching = object.disable_tcp_hole_punching ?? undefined;
    message.secure_mode = (object.secure_mode !== undefined && object.secure_mode !== null)
      ? SecureModeConfig.fromPartial(object.secure_mode)
      : undefined;
    return message;
  },
};

function createBasePortForwardConfig(): PortForwardConfig {
  return { bind_ip: "", bind_port: 0, dst_ip: "", dst_port: 0, proto: "" };
}

export const PortForwardConfig: MessageFns<PortForwardConfig> = {
  fromJSON(object: any): PortForwardConfig {
    return {
      bind_ip: isSet(object.bindIp)
        ? globalThis.String(object.bindIp)
        : isSet(object.bind_ip)
        ? globalThis.String(object.bind_ip)
        : "",
      bind_port: isSet(object.bindPort)
        ? globalThis.Number(object.bindPort)
        : isSet(object.bind_port)
        ? globalThis.Number(object.bind_port)
        : 0,
      dst_ip: isSet(object.dstIp)
        ? globalThis.String(object.dstIp)
        : isSet(object.dst_ip)
        ? globalThis.String(object.dst_ip)
        : "",
      dst_port: isSet(object.dstPort)
        ? globalThis.Number(object.dstPort)
        : isSet(object.dst_port)
        ? globalThis.Number(object.dst_port)
        : 0,
      proto: isSet(object.proto) ? globalThis.String(object.proto) : "",
    };
  },

  toJSON(message: PortForwardConfig): unknown {
    const obj: any = {};
    if (message.bind_ip !== "") {
      obj.bindIp = message.bind_ip;
    }
    if (message.bind_port !== 0) {
      obj.bindPort = Math.round(message.bind_port);
    }
    if (message.dst_ip !== "") {
      obj.dstIp = message.dst_ip;
    }
    if (message.dst_port !== 0) {
      obj.dstPort = Math.round(message.dst_port);
    }
    if (message.proto !== "") {
      obj.proto = message.proto;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortForwardConfig>, I>>(base?: I): PortForwardConfig {
    return PortForwardConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortForwardConfig>, I>>(object: I): PortForwardConfig {
    const message = createBasePortForwardConfig();
    message.bind_ip = object.bind_ip ?? "";
    message.bind_port = object.bind_port ?? 0;
    message.dst_ip = object.dst_ip ?? "";
    message.dst_port = object.dst_port ?? 0;
    message.proto = object.proto ?? "";
    return message;
  },
};

function createBaseMyNodeInfo(): MyNodeInfo {
  return {
    virtual_ipv4: undefined,
    hostname: "",
    version: "",
    ips: undefined,
    stun_info: undefined,
    listeners: [],
    vpn_portal_cfg: undefined,
    peer_id: 0,
  };
}

export const MyNodeInfo: MessageFns<MyNodeInfo> = {
  fromJSON(object: any): MyNodeInfo {
    return {
      virtual_ipv4: isSet(object.virtualIpv4)
        ? Ipv4Inet.fromJSON(object.virtualIpv4)
        : isSet(object.virtual_ipv4)
        ? Ipv4Inet.fromJSON(object.virtual_ipv4)
        : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      ips: isSet(object.ips) ? GetIpListResponse.fromJSON(object.ips) : undefined,
      stun_info: isSet(object.stunInfo)
        ? StunInfo.fromJSON(object.stunInfo)
        : isSet(object.stun_info)
        ? StunInfo.fromJSON(object.stun_info)
        : undefined,
      listeners: globalThis.Array.isArray(object?.listeners)
        ? object.listeners.map((e: any) => Url.fromJSON(e))
        : [],
      vpn_portal_cfg: isSet(object.vpnPortalCfg)
        ? globalThis.String(object.vpnPortalCfg)
        : isSet(object.vpn_portal_cfg)
        ? globalThis.String(object.vpn_portal_cfg)
        : undefined,
      peer_id: isSet(object.peerId)
        ? globalThis.Number(object.peerId)
        : isSet(object.peer_id)
        ? globalThis.Number(object.peer_id)
        : 0,
    };
  },

  toJSON(message: MyNodeInfo): unknown {
    const obj: any = {};
    if (message.virtual_ipv4 !== undefined) {
      obj.virtualIpv4 = Ipv4Inet.toJSON(message.virtual_ipv4);
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.ips !== undefined) {
      obj.ips = GetIpListResponse.toJSON(message.ips);
    }
    if (message.stun_info !== undefined) {
      obj.stunInfo = StunInfo.toJSON(message.stun_info);
    }
    if (message.listeners?.length) {
      obj.listeners = message.listeners.map((e) => Url.toJSON(e));
    }
    if (message.vpn_portal_cfg !== undefined) {
      obj.vpnPortalCfg = message.vpn_portal_cfg;
    }
    if (message.peer_id !== 0) {
      obj.peerId = Math.round(message.peer_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MyNodeInfo>, I>>(base?: I): MyNodeInfo {
    return MyNodeInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MyNodeInfo>, I>>(object: I): MyNodeInfo {
    const message = createBaseMyNodeInfo();
    message.virtual_ipv4 = (object.virtual_ipv4 !== undefined && object.virtual_ipv4 !== null)
      ? Ipv4Inet.fromPartial(object.virtual_ipv4)
      : undefined;
    message.hostname = object.hostname ?? "";
    message.version = object.version ?? "";
    message.ips = (object.ips !== undefined && object.ips !== null)
      ? GetIpListResponse.fromPartial(object.ips)
      : undefined;
    message.stun_info = (object.stun_info !== undefined && object.stun_info !== null)
      ? StunInfo.fromPartial(object.stun_info)
      : undefined;
    message.listeners = object.listeners?.map((e) => Url.fromPartial(e)) || [];
    message.vpn_portal_cfg = object.vpn_portal_cfg ?? undefined;
    message.peer_id = object.peer_id ?? 0;
    return message;
  },
};

function createBaseNetworkInstanceRunningInfo(): NetworkInstanceRunningInfo {
  return {
    dev_name: "",
    my_node_info: undefined,
    events: [],
    routes: [],
    peers: [],
    peer_route_pairs: [],
    running: false,
    error_msg: undefined,
    foreign_network_summary: undefined,
  };
}

export const NetworkInstanceRunningInfo: MessageFns<NetworkInstanceRunningInfo> = {
  fromJSON(object: any): NetworkInstanceRunningInfo {
    return {
      dev_name: isSet(object.devName)
        ? globalThis.String(object.devName)
        : isSet(object.dev_name)
        ? globalThis.String(object.dev_name)
        : "",
      my_node_info: isSet(object.myNodeInfo)
        ? MyNodeInfo.fromJSON(object.myNodeInfo)
        : isSet(object.my_node_info)
        ? MyNodeInfo.fromJSON(object.my_node_info)
        : undefined,
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => globalThis.String(e))
        : [],
      routes: globalThis.Array.isArray(object?.routes)
        ? object.routes.map((e: any) => Route.fromJSON(e))
        : [],
      peers: globalThis.Array.isArray(object?.peers)
        ? object.peers.map((e: any) => PeerInfo.fromJSON(e))
        : [],
      peer_route_pairs: globalThis.Array.isArray(object?.peerRoutePairs)
        ? object.peerRoutePairs.map((e: any) => PeerRoutePair.fromJSON(e))
        : globalThis.Array.isArray(object?.peer_route_pairs)
        ? object.peer_route_pairs.map((e: any) => PeerRoutePair.fromJSON(e))
        : [],
      running: isSet(object.running) ? globalThis.Boolean(object.running) : false,
      error_msg: isSet(object.errorMsg)
        ? globalThis.String(object.errorMsg)
        : isSet(object.error_msg)
        ? globalThis.String(object.error_msg)
        : undefined,
      foreign_network_summary: isSet(object.foreignNetworkSummary)
        ? RouteForeignNetworkSummary.fromJSON(object.foreignNetworkSummary)
        : isSet(object.foreign_network_summary)
        ? RouteForeignNetworkSummary.fromJSON(object.foreign_network_summary)
        : undefined,
    };
  },

  toJSON(message: NetworkInstanceRunningInfo): unknown {
    const obj: any = {};
    if (message.dev_name !== "") {
      obj.devName = message.dev_name;
    }
    if (message.my_node_info !== undefined) {
      obj.myNodeInfo = MyNodeInfo.toJSON(message.my_node_info);
    }
    if (message.events?.length) {
      obj.events = message.events;
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Route.toJSON(e));
    }
    if (message.peers?.length) {
      obj.peers = message.peers.map((e) => PeerInfo.toJSON(e));
    }
    if (message.peer_route_pairs?.length) {
      obj.peerRoutePairs = message.peer_route_pairs.map((e) => PeerRoutePair.toJSON(e));
    }
    if (message.running !== false) {
      obj.running = message.running;
    }
    if (message.error_msg !== undefined) {
      obj.errorMsg = message.error_msg;
    }
    if (message.foreign_network_summary !== undefined) {
      obj.foreignNetworkSummary = RouteForeignNetworkSummary.toJSON(message.foreign_network_summary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfo>, I>>(base?: I): NetworkInstanceRunningInfo {
    return NetworkInstanceRunningInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfo>, I>>(object: I): NetworkInstanceRunningInfo {
    const message = createBaseNetworkInstanceRunningInfo();
    message.dev_name = object.dev_name ?? "";
    message.my_node_info = (object.my_node_info !== undefined && object.my_node_info !== null)
      ? MyNodeInfo.fromPartial(object.my_node_info)
      : undefined;
    message.events = object.events?.map((e) => e) || [];
    message.routes = object.routes?.map((e) => Route.fromPartial(e)) || [];
    message.peers = object.peers?.map((e) => PeerInfo.fromPartial(e)) || [];
    message.peer_route_pairs = object.peer_route_pairs?.map((e) => PeerRoutePair.fromPartial(e)) || [];
    message.running = object.running ?? false;
    message.error_msg = object.error_msg ?? undefined;
    message.foreign_network_summary =
      (object.foreign_network_summary !== undefined && object.foreign_network_summary !== null)
        ? RouteForeignNetworkSummary.fromPartial(object.foreign_network_summary)
        : undefined;
    return message;
  },
};

function createBaseNetworkInstanceRunningInfoMap(): NetworkInstanceRunningInfoMap {
  return { map: {} };
}

export const NetworkInstanceRunningInfoMap: MessageFns<NetworkInstanceRunningInfoMap> = {
  fromJSON(object: any): NetworkInstanceRunningInfoMap {
    return {
      map: isObject(object.map)
        ? (globalThis.Object.entries(object.map) as [string, any][]).reduce(
          (acc: { [key: string]: NetworkInstanceRunningInfo }, [key, value]: [string, any]) => {
            acc[key] = NetworkInstanceRunningInfo.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: NetworkInstanceRunningInfoMap): unknown {
    const obj: any = {};
    if (message.map) {
      const entries = globalThis.Object.entries(message.map) as [string, NetworkInstanceRunningInfo][];
      if (entries.length > 0) {
        obj.map = {};
        entries.forEach(([k, v]) => {
          obj.map[k] = NetworkInstanceRunningInfo.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap>, I>>(base?: I): NetworkInstanceRunningInfoMap {
    return NetworkInstanceRunningInfoMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap>, I>>(
    object: I,
  ): NetworkInstanceRunningInfoMap {
    const message = createBaseNetworkInstanceRunningInfoMap();
    message.map = (globalThis.Object.entries(object.map ?? {}) as [string, NetworkInstanceRunningInfo][]).reduce(
      (acc: { [key: string]: NetworkInstanceRunningInfo }, [key, value]: [string, NetworkInstanceRunningInfo]) => {
        if (value !== undefined) {
          acc[key] = NetworkInstanceRunningInfo.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseNetworkInstanceRunningInfoMap_MapEntry(): NetworkInstanceRunningInfoMap_MapEntry {
  return { key: "", value: undefined };
}

export const NetworkInstanceRunningInfoMap_MapEntry: MessageFns<NetworkInstanceRunningInfoMap_MapEntry> = {
  fromJSON(object: any): NetworkInstanceRunningInfoMap_MapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? NetworkInstanceRunningInfo.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: NetworkInstanceRunningInfoMap_MapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = NetworkInstanceRunningInfo.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap_MapEntry>, I>>(
    base?: I,
  ): NetworkInstanceRunningInfoMap_MapEntry {
    return NetworkInstanceRunningInfoMap_MapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap_MapEntry>, I>>(
    object: I,
  ): NetworkInstanceRunningInfoMap_MapEntry {
    const message = createBaseNetworkInstanceRunningInfoMap_MapEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? NetworkInstanceRunningInfo.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseNetworkMeta(): NetworkMeta {
  return { inst_id: undefined, network_name: "", config_permission: 0 };
}

export const NetworkMeta: MessageFns<NetworkMeta> = {
  fromJSON(object: any): NetworkMeta {
    return {
      inst_id: isSet(object.instId)
        ? UUID.fromJSON(object.instId)
        : isSet(object.inst_id)
        ? UUID.fromJSON(object.inst_id)
        : undefined,
      network_name: isSet(object.networkName)
        ? globalThis.String(object.networkName)
        : isSet(object.network_name)
        ? globalThis.String(object.network_name)
        : "",
      config_permission: isSet(object.configPermission)
        ? globalThis.Number(object.configPermission)
        : isSet(object.config_permission)
        ? globalThis.Number(object.config_permission)
        : 0,
    };
  },

  toJSON(message: NetworkMeta): unknown {
    const obj: any = {};
    if (message.inst_id !== undefined) {
      obj.instId = UUID.toJSON(message.inst_id);
    }
    if (message.network_name !== "") {
      obj.networkName = message.network_name;
    }
    if (message.config_permission !== 0) {
      obj.configPermission = Math.round(message.config_permission);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkMeta>, I>>(base?: I): NetworkMeta {
    return NetworkMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkMeta>, I>>(object: I): NetworkMeta {
    const message = createBaseNetworkMeta();
    message.inst_id = (object.inst_id !== undefined && object.inst_id !== null)
      ? UUID.fromPartial(object.inst_id)
      : undefined;
    message.network_name = object.network_name ?? "";
    message.config_permission = object.config_permission ?? 0;
    return message;
  },
};

function createBaseValidateConfigRequest(): ValidateConfigRequest {
  return { config: undefined };
}

export const ValidateConfigRequest: MessageFns<ValidateConfigRequest> = {
  fromJSON(object: any): ValidateConfigRequest {
    return { config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: ValidateConfigRequest): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateConfigRequest>, I>>(base?: I): ValidateConfigRequest {
    return ValidateConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateConfigRequest>, I>>(object: I): ValidateConfigRequest {
    const message = createBaseValidateConfigRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseValidateConfigResponse(): ValidateConfigResponse {
  return { toml_config: "" };
}

export const ValidateConfigResponse: MessageFns<ValidateConfigResponse> = {
  fromJSON(object: any): ValidateConfigResponse {
    return {
      toml_config: isSet(object.tomlConfig)
        ? globalThis.String(object.tomlConfig)
        : isSet(object.toml_config)
        ? globalThis.String(object.toml_config)
        : "",
    };
  },

  toJSON(message: ValidateConfigResponse): unknown {
    const obj: any = {};
    if (message.toml_config !== "") {
      obj.tomlConfig = message.toml_config;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateConfigResponse>, I>>(base?: I): ValidateConfigResponse {
    return ValidateConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateConfigResponse>, I>>(object: I): ValidateConfigResponse {
    const message = createBaseValidateConfigResponse();
    message.toml_config = object.toml_config ?? "";
    return message;
  },
};

function createBaseRunNetworkInstanceRequest(): RunNetworkInstanceRequest {
  return { inst_id: undefined, config: undefined, overwrite: false };
}

export const RunNetworkInstanceRequest: MessageFns<RunNetworkInstanceRequest> = {
  fromJSON(object: any): RunNetworkInstanceRequest {
    return {
      inst_id: isSet(object.instId)
        ? UUID.fromJSON(object.instId)
        : isSet(object.inst_id)
        ? UUID.fromJSON(object.inst_id)
        : undefined,
      config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined,
      overwrite: isSet(object.overwrite) ? globalThis.Boolean(object.overwrite) : false,
    };
  },

  toJSON(message: RunNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.inst_id !== undefined) {
      obj.instId = UUID.toJSON(message.inst_id);
    }
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    if (message.overwrite !== false) {
      obj.overwrite = message.overwrite;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunNetworkInstanceRequest>, I>>(base?: I): RunNetworkInstanceRequest {
    return RunNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunNetworkInstanceRequest>, I>>(object: I): RunNetworkInstanceRequest {
    const message = createBaseRunNetworkInstanceRequest();
    message.inst_id = (object.inst_id !== undefined && object.inst_id !== null)
      ? UUID.fromPartial(object.inst_id)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    message.overwrite = object.overwrite ?? false;
    return message;
  },
};

function createBaseRunNetworkInstanceResponse(): RunNetworkInstanceResponse {
  return { inst_id: undefined };
}

export const RunNetworkInstanceResponse: MessageFns<RunNetworkInstanceResponse> = {
  fromJSON(object: any): RunNetworkInstanceResponse {
    return {
      inst_id: isSet(object.instId)
        ? UUID.fromJSON(object.instId)
        : isSet(object.inst_id)
        ? UUID.fromJSON(object.inst_id)
        : undefined,
    };
  },

  toJSON(message: RunNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.inst_id !== undefined) {
      obj.instId = UUID.toJSON(message.inst_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunNetworkInstanceResponse>, I>>(base?: I): RunNetworkInstanceResponse {
    return RunNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunNetworkInstanceResponse>, I>>(object: I): RunNetworkInstanceResponse {
    const message = createBaseRunNetworkInstanceResponse();
    message.inst_id = (object.inst_id !== undefined && object.inst_id !== null)
      ? UUID.fromPartial(object.inst_id)
      : undefined;
    return message;
  },
};

function createBaseRetainNetworkInstanceRequest(): RetainNetworkInstanceRequest {
  return { inst_ids: [] };
}

export const RetainNetworkInstanceRequest: MessageFns<RetainNetworkInstanceRequest> = {
  fromJSON(object: any): RetainNetworkInstanceRequest {
    return {
      inst_ids: globalThis.Array.isArray(object?.instIds)
        ? object.instIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.inst_ids)
        ? object.inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: RetainNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.inst_ids?.length) {
      obj.instIds = message.inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetainNetworkInstanceRequest>, I>>(base?: I): RetainNetworkInstanceRequest {
    return RetainNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetainNetworkInstanceRequest>, I>>(object: I): RetainNetworkInstanceRequest {
    const message = createBaseRetainNetworkInstanceRequest();
    message.inst_ids = object.inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRetainNetworkInstanceResponse(): RetainNetworkInstanceResponse {
  return { remain_inst_ids: [] };
}

export const RetainNetworkInstanceResponse: MessageFns<RetainNetworkInstanceResponse> = {
  fromJSON(object: any): RetainNetworkInstanceResponse {
    return {
      remain_inst_ids: globalThis.Array.isArray(object?.remainInstIds)
        ? object.remainInstIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.remain_inst_ids)
        ? object.remain_inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: RetainNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.remain_inst_ids?.length) {
      obj.remainInstIds = message.remain_inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetainNetworkInstanceResponse>, I>>(base?: I): RetainNetworkInstanceResponse {
    return RetainNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetainNetworkInstanceResponse>, I>>(
    object: I,
  ): RetainNetworkInstanceResponse {
    const message = createBaseRetainNetworkInstanceResponse();
    message.remain_inst_ids = object.remain_inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCollectNetworkInfoRequest(): CollectNetworkInfoRequest {
  return { inst_ids: [] };
}

export const CollectNetworkInfoRequest: MessageFns<CollectNetworkInfoRequest> = {
  fromJSON(object: any): CollectNetworkInfoRequest {
    return {
      inst_ids: globalThis.Array.isArray(object?.instIds)
        ? object.instIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.inst_ids)
        ? object.inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: CollectNetworkInfoRequest): unknown {
    const obj: any = {};
    if (message.inst_ids?.length) {
      obj.instIds = message.inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectNetworkInfoRequest>, I>>(base?: I): CollectNetworkInfoRequest {
    return CollectNetworkInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectNetworkInfoRequest>, I>>(object: I): CollectNetworkInfoRequest {
    const message = createBaseCollectNetworkInfoRequest();
    message.inst_ids = object.inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCollectNetworkInfoResponse(): CollectNetworkInfoResponse {
  return { info: undefined };
}

export const CollectNetworkInfoResponse: MessageFns<CollectNetworkInfoResponse> = {
  fromJSON(object: any): CollectNetworkInfoResponse {
    return { info: isSet(object.info) ? NetworkInstanceRunningInfoMap.fromJSON(object.info) : undefined };
  },

  toJSON(message: CollectNetworkInfoResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = NetworkInstanceRunningInfoMap.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectNetworkInfoResponse>, I>>(base?: I): CollectNetworkInfoResponse {
    return CollectNetworkInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectNetworkInfoResponse>, I>>(object: I): CollectNetworkInfoResponse {
    const message = createBaseCollectNetworkInfoResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? NetworkInstanceRunningInfoMap.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseListNetworkInstanceRequest(): ListNetworkInstanceRequest {
  return {};
}

export const ListNetworkInstanceRequest: MessageFns<ListNetworkInstanceRequest> = {
  fromJSON(_: any): ListNetworkInstanceRequest {
    return {};
  },

  toJSON(_: ListNetworkInstanceRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceRequest>, I>>(base?: I): ListNetworkInstanceRequest {
    return ListNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceRequest>, I>>(_: I): ListNetworkInstanceRequest {
    const message = createBaseListNetworkInstanceRequest();
    return message;
  },
};

function createBaseListNetworkInstanceResponse(): ListNetworkInstanceResponse {
  return { inst_ids: [] };
}

export const ListNetworkInstanceResponse: MessageFns<ListNetworkInstanceResponse> = {
  fromJSON(object: any): ListNetworkInstanceResponse {
    return {
      inst_ids: globalThis.Array.isArray(object?.instIds)
        ? object.instIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.inst_ids)
        ? object.inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: ListNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.inst_ids?.length) {
      obj.instIds = message.inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceResponse>, I>>(base?: I): ListNetworkInstanceResponse {
    return ListNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceResponse>, I>>(object: I): ListNetworkInstanceResponse {
    const message = createBaseListNetworkInstanceResponse();
    message.inst_ids = object.inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteNetworkInstanceRequest(): DeleteNetworkInstanceRequest {
  return { inst_ids: [] };
}

export const DeleteNetworkInstanceRequest: MessageFns<DeleteNetworkInstanceRequest> = {
  fromJSON(object: any): DeleteNetworkInstanceRequest {
    return {
      inst_ids: globalThis.Array.isArray(object?.instIds)
        ? object.instIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.inst_ids)
        ? object.inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: DeleteNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.inst_ids?.length) {
      obj.instIds = message.inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNetworkInstanceRequest>, I>>(base?: I): DeleteNetworkInstanceRequest {
    return DeleteNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNetworkInstanceRequest>, I>>(object: I): DeleteNetworkInstanceRequest {
    const message = createBaseDeleteNetworkInstanceRequest();
    message.inst_ids = object.inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteNetworkInstanceResponse(): DeleteNetworkInstanceResponse {
  return { remain_inst_ids: [] };
}

export const DeleteNetworkInstanceResponse: MessageFns<DeleteNetworkInstanceResponse> = {
  fromJSON(object: any): DeleteNetworkInstanceResponse {
    return {
      remain_inst_ids: globalThis.Array.isArray(object?.remainInstIds)
        ? object.remainInstIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.remain_inst_ids)
        ? object.remain_inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: DeleteNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.remain_inst_ids?.length) {
      obj.remainInstIds = message.remain_inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNetworkInstanceResponse>, I>>(base?: I): DeleteNetworkInstanceResponse {
    return DeleteNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNetworkInstanceResponse>, I>>(
    object: I,
  ): DeleteNetworkInstanceResponse {
    const message = createBaseDeleteNetworkInstanceResponse();
    message.remain_inst_ids = object.remain_inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetNetworkInstanceConfigRequest(): GetNetworkInstanceConfigRequest {
  return { inst_id: undefined };
}

export const GetNetworkInstanceConfigRequest: MessageFns<GetNetworkInstanceConfigRequest> = {
  fromJSON(object: any): GetNetworkInstanceConfigRequest {
    return {
      inst_id: isSet(object.instId)
        ? UUID.fromJSON(object.instId)
        : isSet(object.inst_id)
        ? UUID.fromJSON(object.inst_id)
        : undefined,
    };
  },

  toJSON(message: GetNetworkInstanceConfigRequest): unknown {
    const obj: any = {};
    if (message.inst_id !== undefined) {
      obj.instId = UUID.toJSON(message.inst_id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworkInstanceConfigRequest>, I>>(base?: I): GetNetworkInstanceConfigRequest {
    return GetNetworkInstanceConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworkInstanceConfigRequest>, I>>(
    object: I,
  ): GetNetworkInstanceConfigRequest {
    const message = createBaseGetNetworkInstanceConfigRequest();
    message.inst_id = (object.inst_id !== undefined && object.inst_id !== null)
      ? UUID.fromPartial(object.inst_id)
      : undefined;
    return message;
  },
};

function createBaseGetNetworkInstanceConfigResponse(): GetNetworkInstanceConfigResponse {
  return { config: undefined };
}

export const GetNetworkInstanceConfigResponse: MessageFns<GetNetworkInstanceConfigResponse> = {
  fromJSON(object: any): GetNetworkInstanceConfigResponse {
    return { config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: GetNetworkInstanceConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworkInstanceConfigResponse>, I>>(
    base?: I,
  ): GetNetworkInstanceConfigResponse {
    return GetNetworkInstanceConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworkInstanceConfigResponse>, I>>(
    object: I,
  ): GetNetworkInstanceConfigResponse {
    const message = createBaseGetNetworkInstanceConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseListNetworkInstanceMetaRequest(): ListNetworkInstanceMetaRequest {
  return { inst_ids: [] };
}

export const ListNetworkInstanceMetaRequest: MessageFns<ListNetworkInstanceMetaRequest> = {
  fromJSON(object: any): ListNetworkInstanceMetaRequest {
    return {
      inst_ids: globalThis.Array.isArray(object?.instIds)
        ? object.instIds.map((e: any) => UUID.fromJSON(e))
        : globalThis.Array.isArray(object?.inst_ids)
        ? object.inst_ids.map((e: any) =>
          UUID.fromJSON(e)
        )
        : [],
    };
  },

  toJSON(message: ListNetworkInstanceMetaRequest): unknown {
    const obj: any = {};
    if (message.inst_ids?.length) {
      obj.instIds = message.inst_ids.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceMetaRequest>, I>>(base?: I): ListNetworkInstanceMetaRequest {
    return ListNetworkInstanceMetaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceMetaRequest>, I>>(
    object: I,
  ): ListNetworkInstanceMetaRequest {
    const message = createBaseListNetworkInstanceMetaRequest();
    message.inst_ids = object.inst_ids?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListNetworkInstanceMetaResponse(): ListNetworkInstanceMetaResponse {
  return { metas: [] };
}

export const ListNetworkInstanceMetaResponse: MessageFns<ListNetworkInstanceMetaResponse> = {
  fromJSON(object: any): ListNetworkInstanceMetaResponse {
    return {
      metas: globalThis.Array.isArray(object?.metas)
        ? object.metas.map((e: any) => NetworkMeta.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListNetworkInstanceMetaResponse): unknown {
    const obj: any = {};
    if (message.metas?.length) {
      obj.metas = message.metas.map((e) => NetworkMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceMetaResponse>, I>>(base?: I): ListNetworkInstanceMetaResponse {
    return ListNetworkInstanceMetaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceMetaResponse>, I>>(
    object: I,
  ): ListNetworkInstanceMetaResponse {
    const message = createBaseListNetworkInstanceMetaResponse();
    message.metas = object.metas?.map((e) => NetworkMeta.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
