// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api_manage.proto

/* eslint-disable */
import { PeerInfo, PeerRoutePair, Route } from "./api_instance";
import { Ipv4Inet, StunInfo, Url, UUID } from "./common";
import { GetIpListResponse, RouteForeignNetworkSummary } from "./peer_rpc";

export const protobufPackage = "api.manage";

export enum NetworkingMethod {
  PublicServer = 0,
  Manual = 1,
  Standalone = 2,
  UNRECOGNIZED = -1,
}

export function networkingMethodFromJSON(object: any): NetworkingMethod {
  switch (object) {
    case 0:
    case "PublicServer":
      return NetworkingMethod.PublicServer;
    case 1:
    case "Manual":
      return NetworkingMethod.Manual;
    case 2:
    case "Standalone":
      return NetworkingMethod.Standalone;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NetworkingMethod.UNRECOGNIZED;
  }
}

export function networkingMethodToJSON(object: NetworkingMethod): string {
  switch (object) {
    case NetworkingMethod.PublicServer:
      return "PublicServer";
    case NetworkingMethod.Manual:
      return "Manual";
    case NetworkingMethod.Standalone:
      return "Standalone";
    case NetworkingMethod.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NetworkConfig {
  instanceId?: string | undefined;
  dhcp?: boolean | undefined;
  virtualIpv4?: string | undefined;
  networkLength?: number | undefined;
  hostname?: string | undefined;
  networkName?: string | undefined;
  networkSecret?: string | undefined;
  networkingMethod?: NetworkingMethod | undefined;
  publicServerUrl?: string | undefined;
  peerUrls: string[];
  proxyCidrs: string[];
  enableVpnPortal?: boolean | undefined;
  vpnPortalListenPort?: number | undefined;
  vpnPortalClientNetworkAddr?: string | undefined;
  vpnPortalClientNetworkLen?: number | undefined;
  advancedSettings?: boolean | undefined;
  listenerUrls: string[];
  /** optional int32 rpc_port = 18; */
  latencyFirst?: boolean | undefined;
  devName?: string | undefined;
  useSmoltcp?: boolean | undefined;
  disableIpv6?: boolean | undefined;
  enableKcpProxy?: boolean | undefined;
  disableKcpInput?: boolean | undefined;
  disableP2p?: boolean | undefined;
  bindDevice?: boolean | undefined;
  noTun?: boolean | undefined;
  enableExitNode?: boolean | undefined;
  relayAllPeerRpc?: boolean | undefined;
  multiThread?: boolean | undefined;
  enableRelayNetworkWhitelist?: boolean | undefined;
  relayNetworkWhitelist: string[];
  enableManualRoutes?: boolean | undefined;
  routes: string[];
  exitNodes: string[];
  proxyForwardBySystem?: boolean | undefined;
  disableEncryption?: boolean | undefined;
  enableSocks5?: boolean | undefined;
  socks5Port?: number | undefined;
  disableUdpHolePunching?: boolean | undefined;
  mtu?: number | undefined;
  mappedListeners: string[];
  enableMagicDns?: boolean | undefined;
  enablePrivateMode?: boolean | undefined;
  enableQuicProxy?: boolean | undefined;
  disableQuicInput?: boolean | undefined;
  quicListenPort?: number | undefined;
  portForwards: PortForwardConfig[];
  disableSymHolePunching?: boolean | undefined;
}

export interface PortForwardConfig {
  bindIp: string;
  bindPort: number;
  dstIp: string;
  dstPort: number;
  proto: string;
}

export interface MyNodeInfo {
  virtualIpv4: Ipv4Inet | undefined;
  hostname: string;
  version: string;
  ips: GetIpListResponse | undefined;
  stunInfo: StunInfo | undefined;
  listeners: Url[];
  vpnPortalCfg?: string | undefined;
}

export interface NetworkInstanceRunningInfo {
  devName: string;
  myNodeInfo: MyNodeInfo | undefined;
  events: string[];
  routes: Route[];
  peers: PeerInfo[];
  peerRoutePairs: PeerRoutePair[];
  running: boolean;
  errorMsg?: string | undefined;
  foreignNetworkSummary: RouteForeignNetworkSummary | undefined;
}

export interface NetworkInstanceRunningInfoMap {
  map: { [key: string]: NetworkInstanceRunningInfo };
}

export interface NetworkInstanceRunningInfoMap_MapEntry {
  key: string;
  value: NetworkInstanceRunningInfo | undefined;
}

export interface NetworkMeta {
  instId: UUID | undefined;
  networkName: string;
  configPermission: number;
}

export interface ValidateConfigRequest {
  config: NetworkConfig | undefined;
}

export interface ValidateConfigResponse {
  tomlConfig: string;
}

export interface RunNetworkInstanceRequest {
  instId: UUID | undefined;
  config: NetworkConfig | undefined;
  overwrite: boolean;
}

export interface RunNetworkInstanceResponse {
  instId: UUID | undefined;
}

export interface RetainNetworkInstanceRequest {
  instIds: UUID[];
}

export interface RetainNetworkInstanceResponse {
  remainInstIds: UUID[];
}

export interface CollectNetworkInfoRequest {
  instIds: UUID[];
}

export interface CollectNetworkInfoResponse {
  info: NetworkInstanceRunningInfoMap | undefined;
}

export interface ListNetworkInstanceRequest {
}

export interface ListNetworkInstanceResponse {
  instIds: UUID[];
}

export interface DeleteNetworkInstanceRequest {
  instIds: UUID[];
}

export interface DeleteNetworkInstanceResponse {
  remainInstIds: UUID[];
}

export interface GetNetworkInstanceConfigRequest {
  instId: UUID | undefined;
}

export interface GetNetworkInstanceConfigResponse {
  config: NetworkConfig | undefined;
}

export interface ListNetworkInstanceMetaRequest {
  instIds: UUID[];
}

export interface ListNetworkInstanceMetaResponse {
  metas: NetworkMeta[];
}

function createBaseNetworkConfig(): NetworkConfig {
  return {
    instanceId: undefined,
    dhcp: undefined,
    virtualIpv4: undefined,
    networkLength: undefined,
    hostname: undefined,
    networkName: undefined,
    networkSecret: undefined,
    networkingMethod: undefined,
    publicServerUrl: undefined,
    peerUrls: [],
    proxyCidrs: [],
    enableVpnPortal: undefined,
    vpnPortalListenPort: undefined,
    vpnPortalClientNetworkAddr: undefined,
    vpnPortalClientNetworkLen: undefined,
    advancedSettings: undefined,
    listenerUrls: [],
    latencyFirst: undefined,
    devName: undefined,
    useSmoltcp: undefined,
    disableIpv6: undefined,
    enableKcpProxy: undefined,
    disableKcpInput: undefined,
    disableP2p: undefined,
    bindDevice: undefined,
    noTun: undefined,
    enableExitNode: undefined,
    relayAllPeerRpc: undefined,
    multiThread: undefined,
    enableRelayNetworkWhitelist: undefined,
    relayNetworkWhitelist: [],
    enableManualRoutes: undefined,
    routes: [],
    exitNodes: [],
    proxyForwardBySystem: undefined,
    disableEncryption: undefined,
    enableSocks5: undefined,
    socks5Port: undefined,
    disableUdpHolePunching: undefined,
    mtu: undefined,
    mappedListeners: [],
    enableMagicDns: undefined,
    enablePrivateMode: undefined,
    enableQuicProxy: undefined,
    disableQuicInput: undefined,
    quicListenPort: undefined,
    portForwards: [],
    disableSymHolePunching: undefined,
  };
}

export const NetworkConfig: MessageFns<NetworkConfig> = {
  fromJSON(object: any): NetworkConfig {
    return {
      instanceId: isSet(object.instanceId) ? globalThis.String(object.instanceId) : undefined,
      dhcp: isSet(object.dhcp) ? globalThis.Boolean(object.dhcp) : undefined,
      virtualIpv4: isSet(object.virtualIpv4) ? globalThis.String(object.virtualIpv4) : undefined,
      networkLength: isSet(object.networkLength) ? globalThis.Number(object.networkLength) : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : undefined,
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : undefined,
      networkSecret: isSet(object.networkSecret) ? globalThis.String(object.networkSecret) : undefined,
      networkingMethod: isSet(object.networkingMethod) ? networkingMethodFromJSON(object.networkingMethod) : undefined,
      publicServerUrl: isSet(object.publicServerUrl) ? globalThis.String(object.publicServerUrl) : undefined,
      peerUrls: globalThis.Array.isArray(object?.peerUrls) ? object.peerUrls.map((e: any) => globalThis.String(e)) : [],
      proxyCidrs: globalThis.Array.isArray(object?.proxyCidrs)
        ? object.proxyCidrs.map((e: any) => globalThis.String(e))
        : [],
      enableVpnPortal: isSet(object.enableVpnPortal) ? globalThis.Boolean(object.enableVpnPortal) : undefined,
      vpnPortalListenPort: isSet(object.vpnPortalListenPort)
        ? globalThis.Number(object.vpnPortalListenPort)
        : undefined,
      vpnPortalClientNetworkAddr: isSet(object.vpnPortalClientNetworkAddr)
        ? globalThis.String(object.vpnPortalClientNetworkAddr)
        : undefined,
      vpnPortalClientNetworkLen: isSet(object.vpnPortalClientNetworkLen)
        ? globalThis.Number(object.vpnPortalClientNetworkLen)
        : undefined,
      advancedSettings: isSet(object.advancedSettings) ? globalThis.Boolean(object.advancedSettings) : undefined,
      listenerUrls: globalThis.Array.isArray(object?.listenerUrls)
        ? object.listenerUrls.map((e: any) => globalThis.String(e))
        : [],
      latencyFirst: isSet(object.latencyFirst) ? globalThis.Boolean(object.latencyFirst) : undefined,
      devName: isSet(object.devName) ? globalThis.String(object.devName) : undefined,
      useSmoltcp: isSet(object.useSmoltcp) ? globalThis.Boolean(object.useSmoltcp) : undefined,
      disableIpv6: isSet(object.disableIpv6) ? globalThis.Boolean(object.disableIpv6) : undefined,
      enableKcpProxy: isSet(object.enableKcpProxy) ? globalThis.Boolean(object.enableKcpProxy) : undefined,
      disableKcpInput: isSet(object.disableKcpInput) ? globalThis.Boolean(object.disableKcpInput) : undefined,
      disableP2p: isSet(object.disableP2p) ? globalThis.Boolean(object.disableP2p) : undefined,
      bindDevice: isSet(object.bindDevice) ? globalThis.Boolean(object.bindDevice) : undefined,
      noTun: isSet(object.noTun) ? globalThis.Boolean(object.noTun) : undefined,
      enableExitNode: isSet(object.enableExitNode) ? globalThis.Boolean(object.enableExitNode) : undefined,
      relayAllPeerRpc: isSet(object.relayAllPeerRpc) ? globalThis.Boolean(object.relayAllPeerRpc) : undefined,
      multiThread: isSet(object.multiThread) ? globalThis.Boolean(object.multiThread) : undefined,
      enableRelayNetworkWhitelist: isSet(object.enableRelayNetworkWhitelist)
        ? globalThis.Boolean(object.enableRelayNetworkWhitelist)
        : undefined,
      relayNetworkWhitelist: globalThis.Array.isArray(object?.relayNetworkWhitelist)
        ? object.relayNetworkWhitelist.map((e: any) => globalThis.String(e))
        : [],
      enableManualRoutes: isSet(object.enableManualRoutes) ? globalThis.Boolean(object.enableManualRoutes) : undefined,
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => globalThis.String(e)) : [],
      exitNodes: globalThis.Array.isArray(object?.exitNodes)
        ? object.exitNodes.map((e: any) => globalThis.String(e))
        : [],
      proxyForwardBySystem: isSet(object.proxyForwardBySystem)
        ? globalThis.Boolean(object.proxyForwardBySystem)
        : undefined,
      disableEncryption: isSet(object.disableEncryption) ? globalThis.Boolean(object.disableEncryption) : undefined,
      enableSocks5: isSet(object.enableSocks5) ? globalThis.Boolean(object.enableSocks5) : undefined,
      socks5Port: isSet(object.socks5Port) ? globalThis.Number(object.socks5Port) : undefined,
      disableUdpHolePunching: isSet(object.disableUdpHolePunching)
        ? globalThis.Boolean(object.disableUdpHolePunching)
        : undefined,
      mtu: isSet(object.mtu) ? globalThis.Number(object.mtu) : undefined,
      mappedListeners: globalThis.Array.isArray(object?.mappedListeners)
        ? object.mappedListeners.map((e: any) => globalThis.String(e))
        : [],
      enableMagicDns: isSet(object.enableMagicDns) ? globalThis.Boolean(object.enableMagicDns) : undefined,
      enablePrivateMode: isSet(object.enablePrivateMode) ? globalThis.Boolean(object.enablePrivateMode) : undefined,
      enableQuicProxy: isSet(object.enableQuicProxy) ? globalThis.Boolean(object.enableQuicProxy) : undefined,
      disableQuicInput: isSet(object.disableQuicInput) ? globalThis.Boolean(object.disableQuicInput) : undefined,
      quicListenPort: isSet(object.quicListenPort) ? globalThis.Number(object.quicListenPort) : undefined,
      portForwards: globalThis.Array.isArray(object?.portForwards)
        ? object.portForwards.map((e: any) => PortForwardConfig.fromJSON(e))
        : [],
      disableSymHolePunching: isSet(object.disableSymHolePunching)
        ? globalThis.Boolean(object.disableSymHolePunching)
        : undefined,
    };
  },

  toJSON(message: NetworkConfig): unknown {
    const obj: any = {};
    if (message.instanceId !== undefined) {
      obj.instanceId = message.instanceId;
    }
    if (message.dhcp !== undefined) {
      obj.dhcp = message.dhcp;
    }
    if (message.virtualIpv4 !== undefined) {
      obj.virtualIpv4 = message.virtualIpv4;
    }
    if (message.networkLength !== undefined) {
      obj.networkLength = Math.round(message.networkLength);
    }
    if (message.hostname !== undefined) {
      obj.hostname = message.hostname;
    }
    if (message.networkName !== undefined) {
      obj.networkName = message.networkName;
    }
    if (message.networkSecret !== undefined) {
      obj.networkSecret = message.networkSecret;
    }
    if (message.networkingMethod !== undefined) {
      obj.networkingMethod = networkingMethodToJSON(message.networkingMethod);
    }
    if (message.publicServerUrl !== undefined) {
      obj.publicServerUrl = message.publicServerUrl;
    }
    if (message.peerUrls?.length) {
      obj.peerUrls = message.peerUrls;
    }
    if (message.proxyCidrs?.length) {
      obj.proxyCidrs = message.proxyCidrs;
    }
    if (message.enableVpnPortal !== undefined) {
      obj.enableVpnPortal = message.enableVpnPortal;
    }
    if (message.vpnPortalListenPort !== undefined) {
      obj.vpnPortalListenPort = Math.round(message.vpnPortalListenPort);
    }
    if (message.vpnPortalClientNetworkAddr !== undefined) {
      obj.vpnPortalClientNetworkAddr = message.vpnPortalClientNetworkAddr;
    }
    if (message.vpnPortalClientNetworkLen !== undefined) {
      obj.vpnPortalClientNetworkLen = Math.round(message.vpnPortalClientNetworkLen);
    }
    if (message.advancedSettings !== undefined) {
      obj.advancedSettings = message.advancedSettings;
    }
    if (message.listenerUrls?.length) {
      obj.listenerUrls = message.listenerUrls;
    }
    if (message.latencyFirst !== undefined) {
      obj.latencyFirst = message.latencyFirst;
    }
    if (message.devName !== undefined) {
      obj.devName = message.devName;
    }
    if (message.useSmoltcp !== undefined) {
      obj.useSmoltcp = message.useSmoltcp;
    }
    if (message.disableIpv6 !== undefined) {
      obj.disableIpv6 = message.disableIpv6;
    }
    if (message.enableKcpProxy !== undefined) {
      obj.enableKcpProxy = message.enableKcpProxy;
    }
    if (message.disableKcpInput !== undefined) {
      obj.disableKcpInput = message.disableKcpInput;
    }
    if (message.disableP2p !== undefined) {
      obj.disableP2p = message.disableP2p;
    }
    if (message.bindDevice !== undefined) {
      obj.bindDevice = message.bindDevice;
    }
    if (message.noTun !== undefined) {
      obj.noTun = message.noTun;
    }
    if (message.enableExitNode !== undefined) {
      obj.enableExitNode = message.enableExitNode;
    }
    if (message.relayAllPeerRpc !== undefined) {
      obj.relayAllPeerRpc = message.relayAllPeerRpc;
    }
    if (message.multiThread !== undefined) {
      obj.multiThread = message.multiThread;
    }
    if (message.enableRelayNetworkWhitelist !== undefined) {
      obj.enableRelayNetworkWhitelist = message.enableRelayNetworkWhitelist;
    }
    if (message.relayNetworkWhitelist?.length) {
      obj.relayNetworkWhitelist = message.relayNetworkWhitelist;
    }
    if (message.enableManualRoutes !== undefined) {
      obj.enableManualRoutes = message.enableManualRoutes;
    }
    if (message.routes?.length) {
      obj.routes = message.routes;
    }
    if (message.exitNodes?.length) {
      obj.exitNodes = message.exitNodes;
    }
    if (message.proxyForwardBySystem !== undefined) {
      obj.proxyForwardBySystem = message.proxyForwardBySystem;
    }
    if (message.disableEncryption !== undefined) {
      obj.disableEncryption = message.disableEncryption;
    }
    if (message.enableSocks5 !== undefined) {
      obj.enableSocks5 = message.enableSocks5;
    }
    if (message.socks5Port !== undefined) {
      obj.socks5Port = Math.round(message.socks5Port);
    }
    if (message.disableUdpHolePunching !== undefined) {
      obj.disableUdpHolePunching = message.disableUdpHolePunching;
    }
    if (message.mtu !== undefined) {
      obj.mtu = Math.round(message.mtu);
    }
    if (message.mappedListeners?.length) {
      obj.mappedListeners = message.mappedListeners;
    }
    if (message.enableMagicDns !== undefined) {
      obj.enableMagicDns = message.enableMagicDns;
    }
    if (message.enablePrivateMode !== undefined) {
      obj.enablePrivateMode = message.enablePrivateMode;
    }
    if (message.enableQuicProxy !== undefined) {
      obj.enableQuicProxy = message.enableQuicProxy;
    }
    if (message.disableQuicInput !== undefined) {
      obj.disableQuicInput = message.disableQuicInput;
    }
    if (message.quicListenPort !== undefined) {
      obj.quicListenPort = Math.round(message.quicListenPort);
    }
    if (message.portForwards?.length) {
      obj.portForwards = message.portForwards.map((e) => PortForwardConfig.toJSON(e));
    }
    if (message.disableSymHolePunching !== undefined) {
      obj.disableSymHolePunching = message.disableSymHolePunching;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkConfig>, I>>(base?: I): NetworkConfig {
    return NetworkConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkConfig>, I>>(object: I): NetworkConfig {
    const message = createBaseNetworkConfig();
    message.instanceId = object.instanceId ?? undefined;
    message.dhcp = object.dhcp ?? undefined;
    message.virtualIpv4 = object.virtualIpv4 ?? undefined;
    message.networkLength = object.networkLength ?? undefined;
    message.hostname = object.hostname ?? undefined;
    message.networkName = object.networkName ?? undefined;
    message.networkSecret = object.networkSecret ?? undefined;
    message.networkingMethod = object.networkingMethod ?? undefined;
    message.publicServerUrl = object.publicServerUrl ?? undefined;
    message.peerUrls = object.peerUrls?.map((e) => e) || [];
    message.proxyCidrs = object.proxyCidrs?.map((e) => e) || [];
    message.enableVpnPortal = object.enableVpnPortal ?? undefined;
    message.vpnPortalListenPort = object.vpnPortalListenPort ?? undefined;
    message.vpnPortalClientNetworkAddr = object.vpnPortalClientNetworkAddr ?? undefined;
    message.vpnPortalClientNetworkLen = object.vpnPortalClientNetworkLen ?? undefined;
    message.advancedSettings = object.advancedSettings ?? undefined;
    message.listenerUrls = object.listenerUrls?.map((e) => e) || [];
    message.latencyFirst = object.latencyFirst ?? undefined;
    message.devName = object.devName ?? undefined;
    message.useSmoltcp = object.useSmoltcp ?? undefined;
    message.disableIpv6 = object.disableIpv6 ?? undefined;
    message.enableKcpProxy = object.enableKcpProxy ?? undefined;
    message.disableKcpInput = object.disableKcpInput ?? undefined;
    message.disableP2p = object.disableP2p ?? undefined;
    message.bindDevice = object.bindDevice ?? undefined;
    message.noTun = object.noTun ?? undefined;
    message.enableExitNode = object.enableExitNode ?? undefined;
    message.relayAllPeerRpc = object.relayAllPeerRpc ?? undefined;
    message.multiThread = object.multiThread ?? undefined;
    message.enableRelayNetworkWhitelist = object.enableRelayNetworkWhitelist ?? undefined;
    message.relayNetworkWhitelist = object.relayNetworkWhitelist?.map((e) => e) || [];
    message.enableManualRoutes = object.enableManualRoutes ?? undefined;
    message.routes = object.routes?.map((e) => e) || [];
    message.exitNodes = object.exitNodes?.map((e) => e) || [];
    message.proxyForwardBySystem = object.proxyForwardBySystem ?? undefined;
    message.disableEncryption = object.disableEncryption ?? undefined;
    message.enableSocks5 = object.enableSocks5 ?? undefined;
    message.socks5Port = object.socks5Port ?? undefined;
    message.disableUdpHolePunching = object.disableUdpHolePunching ?? undefined;
    message.mtu = object.mtu ?? undefined;
    message.mappedListeners = object.mappedListeners?.map((e) => e) || [];
    message.enableMagicDns = object.enableMagicDns ?? undefined;
    message.enablePrivateMode = object.enablePrivateMode ?? undefined;
    message.enableQuicProxy = object.enableQuicProxy ?? undefined;
    message.disableQuicInput = object.disableQuicInput ?? undefined;
    message.quicListenPort = object.quicListenPort ?? undefined;
    message.portForwards = object.portForwards?.map((e) => PortForwardConfig.fromPartial(e)) || [];
    message.disableSymHolePunching = object.disableSymHolePunching ?? undefined;
    return message;
  },
};

function createBasePortForwardConfig(): PortForwardConfig {
  return { bindIp: "", bindPort: 0, dstIp: "", dstPort: 0, proto: "" };
}

export const PortForwardConfig: MessageFns<PortForwardConfig> = {
  fromJSON(object: any): PortForwardConfig {
    return {
      bindIp: isSet(object.bindIp) ? globalThis.String(object.bindIp) : "",
      bindPort: isSet(object.bindPort) ? globalThis.Number(object.bindPort) : 0,
      dstIp: isSet(object.dstIp) ? globalThis.String(object.dstIp) : "",
      dstPort: isSet(object.dstPort) ? globalThis.Number(object.dstPort) : 0,
      proto: isSet(object.proto) ? globalThis.String(object.proto) : "",
    };
  },

  toJSON(message: PortForwardConfig): unknown {
    const obj: any = {};
    if (message.bindIp !== "") {
      obj.bindIp = message.bindIp;
    }
    if (message.bindPort !== 0) {
      obj.bindPort = Math.round(message.bindPort);
    }
    if (message.dstIp !== "") {
      obj.dstIp = message.dstIp;
    }
    if (message.dstPort !== 0) {
      obj.dstPort = Math.round(message.dstPort);
    }
    if (message.proto !== "") {
      obj.proto = message.proto;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortForwardConfig>, I>>(base?: I): PortForwardConfig {
    return PortForwardConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortForwardConfig>, I>>(object: I): PortForwardConfig {
    const message = createBasePortForwardConfig();
    message.bindIp = object.bindIp ?? "";
    message.bindPort = object.bindPort ?? 0;
    message.dstIp = object.dstIp ?? "";
    message.dstPort = object.dstPort ?? 0;
    message.proto = object.proto ?? "";
    return message;
  },
};

function createBaseMyNodeInfo(): MyNodeInfo {
  return {
    virtualIpv4: undefined,
    hostname: "",
    version: "",
    ips: undefined,
    stunInfo: undefined,
    listeners: [],
    vpnPortalCfg: undefined,
  };
}

export const MyNodeInfo: MessageFns<MyNodeInfo> = {
  fromJSON(object: any): MyNodeInfo {
    return {
      virtualIpv4: isSet(object.virtualIpv4) ? Ipv4Inet.fromJSON(object.virtualIpv4) : undefined,
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      ips: isSet(object.ips) ? GetIpListResponse.fromJSON(object.ips) : undefined,
      stunInfo: isSet(object.stunInfo) ? StunInfo.fromJSON(object.stunInfo) : undefined,
      listeners: globalThis.Array.isArray(object?.listeners) ? object.listeners.map((e: any) => Url.fromJSON(e)) : [],
      vpnPortalCfg: isSet(object.vpnPortalCfg) ? globalThis.String(object.vpnPortalCfg) : undefined,
    };
  },

  toJSON(message: MyNodeInfo): unknown {
    const obj: any = {};
    if (message.virtualIpv4 !== undefined) {
      obj.virtualIpv4 = Ipv4Inet.toJSON(message.virtualIpv4);
    }
    if (message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.ips !== undefined) {
      obj.ips = GetIpListResponse.toJSON(message.ips);
    }
    if (message.stunInfo !== undefined) {
      obj.stunInfo = StunInfo.toJSON(message.stunInfo);
    }
    if (message.listeners?.length) {
      obj.listeners = message.listeners.map((e) => Url.toJSON(e));
    }
    if (message.vpnPortalCfg !== undefined) {
      obj.vpnPortalCfg = message.vpnPortalCfg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MyNodeInfo>, I>>(base?: I): MyNodeInfo {
    return MyNodeInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MyNodeInfo>, I>>(object: I): MyNodeInfo {
    const message = createBaseMyNodeInfo();
    message.virtualIpv4 = (object.virtualIpv4 !== undefined && object.virtualIpv4 !== null)
      ? Ipv4Inet.fromPartial(object.virtualIpv4)
      : undefined;
    message.hostname = object.hostname ?? "";
    message.version = object.version ?? "";
    message.ips = (object.ips !== undefined && object.ips !== null)
      ? GetIpListResponse.fromPartial(object.ips)
      : undefined;
    message.stunInfo = (object.stunInfo !== undefined && object.stunInfo !== null)
      ? StunInfo.fromPartial(object.stunInfo)
      : undefined;
    message.listeners = object.listeners?.map((e) => Url.fromPartial(e)) || [];
    message.vpnPortalCfg = object.vpnPortalCfg ?? undefined;
    return message;
  },
};

function createBaseNetworkInstanceRunningInfo(): NetworkInstanceRunningInfo {
  return {
    devName: "",
    myNodeInfo: undefined,
    events: [],
    routes: [],
    peers: [],
    peerRoutePairs: [],
    running: false,
    errorMsg: undefined,
    foreignNetworkSummary: undefined,
  };
}

export const NetworkInstanceRunningInfo: MessageFns<NetworkInstanceRunningInfo> = {
  fromJSON(object: any): NetworkInstanceRunningInfo {
    return {
      devName: isSet(object.devName) ? globalThis.String(object.devName) : "",
      myNodeInfo: isSet(object.myNodeInfo) ? MyNodeInfo.fromJSON(object.myNodeInfo) : undefined,
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => globalThis.String(e))
        : [],
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => Route.fromJSON(e)) : [],
      peers: globalThis.Array.isArray(object?.peers) ? object.peers.map((e: any) => PeerInfo.fromJSON(e)) : [],
      peerRoutePairs: globalThis.Array.isArray(object?.peerRoutePairs)
        ? object.peerRoutePairs.map((e: any) => PeerRoutePair.fromJSON(e))
        : [],
      running: isSet(object.running) ? globalThis.Boolean(object.running) : false,
      errorMsg: isSet(object.errorMsg) ? globalThis.String(object.errorMsg) : undefined,
      foreignNetworkSummary: isSet(object.foreignNetworkSummary)
        ? RouteForeignNetworkSummary.fromJSON(object.foreignNetworkSummary)
        : undefined,
    };
  },

  toJSON(message: NetworkInstanceRunningInfo): unknown {
    const obj: any = {};
    if (message.devName !== "") {
      obj.devName = message.devName;
    }
    if (message.myNodeInfo !== undefined) {
      obj.myNodeInfo = MyNodeInfo.toJSON(message.myNodeInfo);
    }
    if (message.events?.length) {
      obj.events = message.events;
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => Route.toJSON(e));
    }
    if (message.peers?.length) {
      obj.peers = message.peers.map((e) => PeerInfo.toJSON(e));
    }
    if (message.peerRoutePairs?.length) {
      obj.peerRoutePairs = message.peerRoutePairs.map((e) => PeerRoutePair.toJSON(e));
    }
    if (message.running !== false) {
      obj.running = message.running;
    }
    if (message.errorMsg !== undefined) {
      obj.errorMsg = message.errorMsg;
    }
    if (message.foreignNetworkSummary !== undefined) {
      obj.foreignNetworkSummary = RouteForeignNetworkSummary.toJSON(message.foreignNetworkSummary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfo>, I>>(base?: I): NetworkInstanceRunningInfo {
    return NetworkInstanceRunningInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfo>, I>>(object: I): NetworkInstanceRunningInfo {
    const message = createBaseNetworkInstanceRunningInfo();
    message.devName = object.devName ?? "";
    message.myNodeInfo = (object.myNodeInfo !== undefined && object.myNodeInfo !== null)
      ? MyNodeInfo.fromPartial(object.myNodeInfo)
      : undefined;
    message.events = object.events?.map((e) => e) || [];
    message.routes = object.routes?.map((e) => Route.fromPartial(e)) || [];
    message.peers = object.peers?.map((e) => PeerInfo.fromPartial(e)) || [];
    message.peerRoutePairs = object.peerRoutePairs?.map((e) => PeerRoutePair.fromPartial(e)) || [];
    message.running = object.running ?? false;
    message.errorMsg = object.errorMsg ?? undefined;
    message.foreignNetworkSummary =
      (object.foreignNetworkSummary !== undefined && object.foreignNetworkSummary !== null)
        ? RouteForeignNetworkSummary.fromPartial(object.foreignNetworkSummary)
        : undefined;
    return message;
  },
};

function createBaseNetworkInstanceRunningInfoMap(): NetworkInstanceRunningInfoMap {
  return { map: {} };
}

export const NetworkInstanceRunningInfoMap: MessageFns<NetworkInstanceRunningInfoMap> = {
  fromJSON(object: any): NetworkInstanceRunningInfoMap {
    return {
      map: isObject(object.map)
        ? Object.entries(object.map).reduce<{ [key: string]: NetworkInstanceRunningInfo }>((acc, [key, value]) => {
          acc[key] = NetworkInstanceRunningInfo.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: NetworkInstanceRunningInfoMap): unknown {
    const obj: any = {};
    if (message.map) {
      const entries = Object.entries(message.map);
      if (entries.length > 0) {
        obj.map = {};
        entries.forEach(([k, v]) => {
          obj.map[k] = NetworkInstanceRunningInfo.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap>, I>>(base?: I): NetworkInstanceRunningInfoMap {
    return NetworkInstanceRunningInfoMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap>, I>>(
    object: I,
  ): NetworkInstanceRunningInfoMap {
    const message = createBaseNetworkInstanceRunningInfoMap();
    message.map = Object.entries(object.map ?? {}).reduce<{ [key: string]: NetworkInstanceRunningInfo }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = NetworkInstanceRunningInfo.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseNetworkInstanceRunningInfoMap_MapEntry(): NetworkInstanceRunningInfoMap_MapEntry {
  return { key: "", value: undefined };
}

export const NetworkInstanceRunningInfoMap_MapEntry: MessageFns<NetworkInstanceRunningInfoMap_MapEntry> = {
  fromJSON(object: any): NetworkInstanceRunningInfoMap_MapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? NetworkInstanceRunningInfo.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: NetworkInstanceRunningInfoMap_MapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = NetworkInstanceRunningInfo.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap_MapEntry>, I>>(
    base?: I,
  ): NetworkInstanceRunningInfoMap_MapEntry {
    return NetworkInstanceRunningInfoMap_MapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInstanceRunningInfoMap_MapEntry>, I>>(
    object: I,
  ): NetworkInstanceRunningInfoMap_MapEntry {
    const message = createBaseNetworkInstanceRunningInfoMap_MapEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? NetworkInstanceRunningInfo.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseNetworkMeta(): NetworkMeta {
  return { instId: undefined, networkName: "", configPermission: 0 };
}

export const NetworkMeta: MessageFns<NetworkMeta> = {
  fromJSON(object: any): NetworkMeta {
    return {
      instId: isSet(object.instId) ? UUID.fromJSON(object.instId) : undefined,
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : "",
      configPermission: isSet(object.configPermission) ? globalThis.Number(object.configPermission) : 0,
    };
  },

  toJSON(message: NetworkMeta): unknown {
    const obj: any = {};
    if (message.instId !== undefined) {
      obj.instId = UUID.toJSON(message.instId);
    }
    if (message.networkName !== "") {
      obj.networkName = message.networkName;
    }
    if (message.configPermission !== 0) {
      obj.configPermission = Math.round(message.configPermission);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkMeta>, I>>(base?: I): NetworkMeta {
    return NetworkMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkMeta>, I>>(object: I): NetworkMeta {
    const message = createBaseNetworkMeta();
    message.instId = (object.instId !== undefined && object.instId !== null)
      ? UUID.fromPartial(object.instId)
      : undefined;
    message.networkName = object.networkName ?? "";
    message.configPermission = object.configPermission ?? 0;
    return message;
  },
};

function createBaseValidateConfigRequest(): ValidateConfigRequest {
  return { config: undefined };
}

export const ValidateConfigRequest: MessageFns<ValidateConfigRequest> = {
  fromJSON(object: any): ValidateConfigRequest {
    return { config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: ValidateConfigRequest): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateConfigRequest>, I>>(base?: I): ValidateConfigRequest {
    return ValidateConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateConfigRequest>, I>>(object: I): ValidateConfigRequest {
    const message = createBaseValidateConfigRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseValidateConfigResponse(): ValidateConfigResponse {
  return { tomlConfig: "" };
}

export const ValidateConfigResponse: MessageFns<ValidateConfigResponse> = {
  fromJSON(object: any): ValidateConfigResponse {
    return { tomlConfig: isSet(object.tomlConfig) ? globalThis.String(object.tomlConfig) : "" };
  },

  toJSON(message: ValidateConfigResponse): unknown {
    const obj: any = {};
    if (message.tomlConfig !== "") {
      obj.tomlConfig = message.tomlConfig;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateConfigResponse>, I>>(base?: I): ValidateConfigResponse {
    return ValidateConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateConfigResponse>, I>>(object: I): ValidateConfigResponse {
    const message = createBaseValidateConfigResponse();
    message.tomlConfig = object.tomlConfig ?? "";
    return message;
  },
};

function createBaseRunNetworkInstanceRequest(): RunNetworkInstanceRequest {
  return { instId: undefined, config: undefined, overwrite: false };
}

export const RunNetworkInstanceRequest: MessageFns<RunNetworkInstanceRequest> = {
  fromJSON(object: any): RunNetworkInstanceRequest {
    return {
      instId: isSet(object.instId) ? UUID.fromJSON(object.instId) : undefined,
      config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined,
      overwrite: isSet(object.overwrite) ? globalThis.Boolean(object.overwrite) : false,
    };
  },

  toJSON(message: RunNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.instId !== undefined) {
      obj.instId = UUID.toJSON(message.instId);
    }
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    if (message.overwrite !== false) {
      obj.overwrite = message.overwrite;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunNetworkInstanceRequest>, I>>(base?: I): RunNetworkInstanceRequest {
    return RunNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunNetworkInstanceRequest>, I>>(object: I): RunNetworkInstanceRequest {
    const message = createBaseRunNetworkInstanceRequest();
    message.instId = (object.instId !== undefined && object.instId !== null)
      ? UUID.fromPartial(object.instId)
      : undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    message.overwrite = object.overwrite ?? false;
    return message;
  },
};

function createBaseRunNetworkInstanceResponse(): RunNetworkInstanceResponse {
  return { instId: undefined };
}

export const RunNetworkInstanceResponse: MessageFns<RunNetworkInstanceResponse> = {
  fromJSON(object: any): RunNetworkInstanceResponse {
    return { instId: isSet(object.instId) ? UUID.fromJSON(object.instId) : undefined };
  },

  toJSON(message: RunNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.instId !== undefined) {
      obj.instId = UUID.toJSON(message.instId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RunNetworkInstanceResponse>, I>>(base?: I): RunNetworkInstanceResponse {
    return RunNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunNetworkInstanceResponse>, I>>(object: I): RunNetworkInstanceResponse {
    const message = createBaseRunNetworkInstanceResponse();
    message.instId = (object.instId !== undefined && object.instId !== null)
      ? UUID.fromPartial(object.instId)
      : undefined;
    return message;
  },
};

function createBaseRetainNetworkInstanceRequest(): RetainNetworkInstanceRequest {
  return { instIds: [] };
}

export const RetainNetworkInstanceRequest: MessageFns<RetainNetworkInstanceRequest> = {
  fromJSON(object: any): RetainNetworkInstanceRequest {
    return {
      instIds: globalThis.Array.isArray(object?.instIds) ? object.instIds.map((e: any) => UUID.fromJSON(e)) : [],
    };
  },

  toJSON(message: RetainNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.instIds?.length) {
      obj.instIds = message.instIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetainNetworkInstanceRequest>, I>>(base?: I): RetainNetworkInstanceRequest {
    return RetainNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetainNetworkInstanceRequest>, I>>(object: I): RetainNetworkInstanceRequest {
    const message = createBaseRetainNetworkInstanceRequest();
    message.instIds = object.instIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRetainNetworkInstanceResponse(): RetainNetworkInstanceResponse {
  return { remainInstIds: [] };
}

export const RetainNetworkInstanceResponse: MessageFns<RetainNetworkInstanceResponse> = {
  fromJSON(object: any): RetainNetworkInstanceResponse {
    return {
      remainInstIds: globalThis.Array.isArray(object?.remainInstIds)
        ? object.remainInstIds.map((e: any) => UUID.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RetainNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.remainInstIds?.length) {
      obj.remainInstIds = message.remainInstIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RetainNetworkInstanceResponse>, I>>(base?: I): RetainNetworkInstanceResponse {
    return RetainNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetainNetworkInstanceResponse>, I>>(
    object: I,
  ): RetainNetworkInstanceResponse {
    const message = createBaseRetainNetworkInstanceResponse();
    message.remainInstIds = object.remainInstIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCollectNetworkInfoRequest(): CollectNetworkInfoRequest {
  return { instIds: [] };
}

export const CollectNetworkInfoRequest: MessageFns<CollectNetworkInfoRequest> = {
  fromJSON(object: any): CollectNetworkInfoRequest {
    return {
      instIds: globalThis.Array.isArray(object?.instIds) ? object.instIds.map((e: any) => UUID.fromJSON(e)) : [],
    };
  },

  toJSON(message: CollectNetworkInfoRequest): unknown {
    const obj: any = {};
    if (message.instIds?.length) {
      obj.instIds = message.instIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectNetworkInfoRequest>, I>>(base?: I): CollectNetworkInfoRequest {
    return CollectNetworkInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectNetworkInfoRequest>, I>>(object: I): CollectNetworkInfoRequest {
    const message = createBaseCollectNetworkInfoRequest();
    message.instIds = object.instIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCollectNetworkInfoResponse(): CollectNetworkInfoResponse {
  return { info: undefined };
}

export const CollectNetworkInfoResponse: MessageFns<CollectNetworkInfoResponse> = {
  fromJSON(object: any): CollectNetworkInfoResponse {
    return { info: isSet(object.info) ? NetworkInstanceRunningInfoMap.fromJSON(object.info) : undefined };
  },

  toJSON(message: CollectNetworkInfoResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = NetworkInstanceRunningInfoMap.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectNetworkInfoResponse>, I>>(base?: I): CollectNetworkInfoResponse {
    return CollectNetworkInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectNetworkInfoResponse>, I>>(object: I): CollectNetworkInfoResponse {
    const message = createBaseCollectNetworkInfoResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? NetworkInstanceRunningInfoMap.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseListNetworkInstanceRequest(): ListNetworkInstanceRequest {
  return {};
}

export const ListNetworkInstanceRequest: MessageFns<ListNetworkInstanceRequest> = {
  fromJSON(_: any): ListNetworkInstanceRequest {
    return {};
  },

  toJSON(_: ListNetworkInstanceRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceRequest>, I>>(base?: I): ListNetworkInstanceRequest {
    return ListNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceRequest>, I>>(_: I): ListNetworkInstanceRequest {
    const message = createBaseListNetworkInstanceRequest();
    return message;
  },
};

function createBaseListNetworkInstanceResponse(): ListNetworkInstanceResponse {
  return { instIds: [] };
}

export const ListNetworkInstanceResponse: MessageFns<ListNetworkInstanceResponse> = {
  fromJSON(object: any): ListNetworkInstanceResponse {
    return {
      instIds: globalThis.Array.isArray(object?.instIds) ? object.instIds.map((e: any) => UUID.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.instIds?.length) {
      obj.instIds = message.instIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceResponse>, I>>(base?: I): ListNetworkInstanceResponse {
    return ListNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceResponse>, I>>(object: I): ListNetworkInstanceResponse {
    const message = createBaseListNetworkInstanceResponse();
    message.instIds = object.instIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteNetworkInstanceRequest(): DeleteNetworkInstanceRequest {
  return { instIds: [] };
}

export const DeleteNetworkInstanceRequest: MessageFns<DeleteNetworkInstanceRequest> = {
  fromJSON(object: any): DeleteNetworkInstanceRequest {
    return {
      instIds: globalThis.Array.isArray(object?.instIds) ? object.instIds.map((e: any) => UUID.fromJSON(e)) : [],
    };
  },

  toJSON(message: DeleteNetworkInstanceRequest): unknown {
    const obj: any = {};
    if (message.instIds?.length) {
      obj.instIds = message.instIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNetworkInstanceRequest>, I>>(base?: I): DeleteNetworkInstanceRequest {
    return DeleteNetworkInstanceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNetworkInstanceRequest>, I>>(object: I): DeleteNetworkInstanceRequest {
    const message = createBaseDeleteNetworkInstanceRequest();
    message.instIds = object.instIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteNetworkInstanceResponse(): DeleteNetworkInstanceResponse {
  return { remainInstIds: [] };
}

export const DeleteNetworkInstanceResponse: MessageFns<DeleteNetworkInstanceResponse> = {
  fromJSON(object: any): DeleteNetworkInstanceResponse {
    return {
      remainInstIds: globalThis.Array.isArray(object?.remainInstIds)
        ? object.remainInstIds.map((e: any) => UUID.fromJSON(e))
        : [],
    };
  },

  toJSON(message: DeleteNetworkInstanceResponse): unknown {
    const obj: any = {};
    if (message.remainInstIds?.length) {
      obj.remainInstIds = message.remainInstIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNetworkInstanceResponse>, I>>(base?: I): DeleteNetworkInstanceResponse {
    return DeleteNetworkInstanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNetworkInstanceResponse>, I>>(
    object: I,
  ): DeleteNetworkInstanceResponse {
    const message = createBaseDeleteNetworkInstanceResponse();
    message.remainInstIds = object.remainInstIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetNetworkInstanceConfigRequest(): GetNetworkInstanceConfigRequest {
  return { instId: undefined };
}

export const GetNetworkInstanceConfigRequest: MessageFns<GetNetworkInstanceConfigRequest> = {
  fromJSON(object: any): GetNetworkInstanceConfigRequest {
    return { instId: isSet(object.instId) ? UUID.fromJSON(object.instId) : undefined };
  },

  toJSON(message: GetNetworkInstanceConfigRequest): unknown {
    const obj: any = {};
    if (message.instId !== undefined) {
      obj.instId = UUID.toJSON(message.instId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworkInstanceConfigRequest>, I>>(base?: I): GetNetworkInstanceConfigRequest {
    return GetNetworkInstanceConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworkInstanceConfigRequest>, I>>(
    object: I,
  ): GetNetworkInstanceConfigRequest {
    const message = createBaseGetNetworkInstanceConfigRequest();
    message.instId = (object.instId !== undefined && object.instId !== null)
      ? UUID.fromPartial(object.instId)
      : undefined;
    return message;
  },
};

function createBaseGetNetworkInstanceConfigResponse(): GetNetworkInstanceConfigResponse {
  return { config: undefined };
}

export const GetNetworkInstanceConfigResponse: MessageFns<GetNetworkInstanceConfigResponse> = {
  fromJSON(object: any): GetNetworkInstanceConfigResponse {
    return { config: isSet(object.config) ? NetworkConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: GetNetworkInstanceConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = NetworkConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetNetworkInstanceConfigResponse>, I>>(
    base?: I,
  ): GetNetworkInstanceConfigResponse {
    return GetNetworkInstanceConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetNetworkInstanceConfigResponse>, I>>(
    object: I,
  ): GetNetworkInstanceConfigResponse {
    const message = createBaseGetNetworkInstanceConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? NetworkConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseListNetworkInstanceMetaRequest(): ListNetworkInstanceMetaRequest {
  return { instIds: [] };
}

export const ListNetworkInstanceMetaRequest: MessageFns<ListNetworkInstanceMetaRequest> = {
  fromJSON(object: any): ListNetworkInstanceMetaRequest {
    return {
      instIds: globalThis.Array.isArray(object?.instIds) ? object.instIds.map((e: any) => UUID.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListNetworkInstanceMetaRequest): unknown {
    const obj: any = {};
    if (message.instIds?.length) {
      obj.instIds = message.instIds.map((e) => UUID.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceMetaRequest>, I>>(base?: I): ListNetworkInstanceMetaRequest {
    return ListNetworkInstanceMetaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceMetaRequest>, I>>(
    object: I,
  ): ListNetworkInstanceMetaRequest {
    const message = createBaseListNetworkInstanceMetaRequest();
    message.instIds = object.instIds?.map((e) => UUID.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListNetworkInstanceMetaResponse(): ListNetworkInstanceMetaResponse {
  return { metas: [] };
}

export const ListNetworkInstanceMetaResponse: MessageFns<ListNetworkInstanceMetaResponse> = {
  fromJSON(object: any): ListNetworkInstanceMetaResponse {
    return {
      metas: globalThis.Array.isArray(object?.metas)
        ? object.metas.map((e: any) => NetworkMeta.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListNetworkInstanceMetaResponse): unknown {
    const obj: any = {};
    if (message.metas?.length) {
      obj.metas = message.metas.map((e) => NetworkMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNetworkInstanceMetaResponse>, I>>(base?: I): ListNetworkInstanceMetaResponse {
    return ListNetworkInstanceMetaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNetworkInstanceMetaResponse>, I>>(
    object: I,
  ): ListNetworkInstanceMetaResponse {
    const message = createBaseListNetworkInstanceMetaResponse();
    message.metas = object.metas?.map((e) => NetworkMeta.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
