// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: common.proto

/* eslint-disable */
import { Error } from "./error";

export const protobufPackage = "common";

export enum CompressionAlgoPb {
  Invalid = 0,
  None = 1,
  Zstd = 2,
  UNRECOGNIZED = -1,
}

export function compressionAlgoPbFromJSON(object: any): CompressionAlgoPb {
  switch (object) {
    case 0:
    case "Invalid":
      return CompressionAlgoPb.Invalid;
    case 1:
    case "None":
      return CompressionAlgoPb.None;
    case 2:
    case "Zstd":
      return CompressionAlgoPb.Zstd;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CompressionAlgoPb.UNRECOGNIZED;
  }
}

export function compressionAlgoPbToJSON(object: CompressionAlgoPb): string {
  switch (object) {
    case CompressionAlgoPb.Invalid:
      return "Invalid";
    case CompressionAlgoPb.None:
      return "None";
    case CompressionAlgoPb.Zstd:
      return "Zstd";
    case CompressionAlgoPb.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum NatType {
  /** Unknown - has NAT; but own a single public IP, port is not changed */
  Unknown = 0,
  OpenInternet = 1,
  NoPAT = 2,
  FullCone = 3,
  Restricted = 4,
  PortRestricted = 5,
  Symmetric = 6,
  SymUdpFirewall = 7,
  SymmetricEasyInc = 8,
  SymmetricEasyDec = 9,
  UNRECOGNIZED = -1,
}

export function natTypeFromJSON(object: any): NatType {
  switch (object) {
    case 0:
    case "Unknown":
      return NatType.Unknown;
    case 1:
    case "OpenInternet":
      return NatType.OpenInternet;
    case 2:
    case "NoPAT":
      return NatType.NoPAT;
    case 3:
    case "FullCone":
      return NatType.FullCone;
    case 4:
    case "Restricted":
      return NatType.Restricted;
    case 5:
    case "PortRestricted":
      return NatType.PortRestricted;
    case 6:
    case "Symmetric":
      return NatType.Symmetric;
    case 7:
    case "SymUdpFirewall":
      return NatType.SymUdpFirewall;
    case 8:
    case "SymmetricEasyInc":
      return NatType.SymmetricEasyInc;
    case 9:
    case "SymmetricEasyDec":
      return NatType.SymmetricEasyDec;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NatType.UNRECOGNIZED;
  }
}

export function natTypeToJSON(object: NatType): string {
  switch (object) {
    case NatType.Unknown:
      return "Unknown";
    case NatType.OpenInternet:
      return "OpenInternet";
    case NatType.NoPAT:
      return "NoPAT";
    case NatType.FullCone:
      return "FullCone";
    case NatType.Restricted:
      return "Restricted";
    case NatType.PortRestricted:
      return "PortRestricted";
    case NatType.Symmetric:
      return "Symmetric";
    case NatType.SymUdpFirewall:
      return "SymUdpFirewall";
    case NatType.SymmetricEasyInc:
      return "SymmetricEasyInc";
    case NatType.SymmetricEasyDec:
      return "SymmetricEasyDec";
    case NatType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SocketType {
  TCP = 0,
  UDP = 1,
  UNRECOGNIZED = -1,
}

export function socketTypeFromJSON(object: any): SocketType {
  switch (object) {
    case 0:
    case "TCP":
      return SocketType.TCP;
    case 1:
    case "UDP":
      return SocketType.UDP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SocketType.UNRECOGNIZED;
  }
}

export function socketTypeToJSON(object: SocketType): string {
  switch (object) {
    case SocketType.TCP:
      return "TCP";
    case SocketType.UDP:
      return "UDP";
    case SocketType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FlagsInConfig {
  default_protocol: string;
  dev_name: string;
  enable_encryption: boolean;
  enable_ipv6: boolean;
  mtu: number;
  latency_first: boolean;
  enable_exit_node: boolean;
  no_tun: boolean;
  use_smoltcp: boolean;
  relay_network_whitelist: string;
  disable_p2p: boolean;
  relay_all_peer_rpc: boolean;
  disable_udp_hole_punching: boolean;
  /**
   * string ipv6_listener = 14; [deprecated = true]; use -l udp://[::]:12345
   * instead
   */
  multi_thread: boolean;
  data_compress_algo: CompressionAlgoPb;
  bind_device: boolean;
  /** should we convert all tcp streams into kcp streams */
  enable_kcp_proxy: boolean;
  /** does this peer allow kcp input */
  disable_kcp_input: boolean;
  /** disable relay local network kcp packets */
  disable_relay_kcp: boolean;
  proxy_forward_by_system: boolean;
  /** enable magic dns or not */
  accept_dns: boolean;
  /** enable private mode */
  private_mode: boolean;
  /** should we convert all tcp streams into quic streams */
  enable_quic_proxy: boolean;
  /** does this peer allow quic input */
  disable_quic_input: boolean;
  /** disable relay local network quic packets */
  disable_relay_quic: boolean;
  /**
   * quic listen port
   *
   * @deprecated
   */
  quic_listen_port: number;
  /** a global relay limit, only work for foreign network */
  foreign_relay_bps_limit: number;
  multi_thread_count: number;
  /** enable relay foreign network kcp packets */
  enable_relay_foreign_network_kcp: boolean;
  /** enable relay foreign network quic packets */
  enable_relay_foreign_network_quic: boolean;
  /** encryption algorithm to use, empty string means default (aes-gcm) */
  encryption_algorithm: string;
  /** disable symmetric nat hole punching, treat symmetric as cone when enabled */
  disable_sym_hole_punching: boolean;
  /** tld dns zone for magic dns */
  tld_dns_zone: string;
  p2p_only: boolean;
  disable_tcp_hole_punching: boolean;
}

export interface RpcDescriptor {
  /** allow same service registered multiple times in different domain */
  domain_name: string;
  proto_name: string;
  service_name: string;
  method_index: number;
}

export interface RpcRequest {
  /** @deprecated */
  descriptor: RpcDescriptor | undefined;
  request: Uint8Array;
  timeout_ms: number;
}

export interface RpcResponse {
  response: Uint8Array;
  error: Error | undefined;
  runtime_us: number;
}

export interface RpcCompressionInfo {
  /** use this to compress the content */
  algo: CompressionAlgoPb;
  /**
   * tell the peer which compression algo is used to compress the next
   * response/request
   */
  accepted_algo: CompressionAlgoPb;
}

export interface RpcPacket {
  from_peer: number;
  to_peer: number;
  transaction_id: number;
  descriptor: RpcDescriptor | undefined;
  body: Uint8Array;
  is_request: boolean;
  total_pieces: number;
  piece_idx: number;
  trace_id: number;
  compression_info: RpcCompressionInfo | undefined;
}

export interface Void {
}

export interface UUID {
  part1: number;
  part2: number;
  part3: number;
  part4: number;
}

export interface Ipv4Addr {
  addr: number;
}

export interface Ipv6Addr {
  part1: number;
  part2: number;
  part3: number;
  part4: number;
}

export interface IpAddr {
  ipv4?: Ipv4Addr | undefined;
  ipv6?: Ipv6Addr | undefined;
}

export interface Ipv4Inet {
  address: Ipv4Addr | undefined;
  network_length: number;
}

export interface Ipv6Inet {
  address: Ipv6Addr | undefined;
  network_length: number;
}

export interface IpInet {
  ipv4?: Ipv4Inet | undefined;
  ipv6?: Ipv6Inet | undefined;
}

export interface Url {
  url: string;
}

export interface SocketAddr {
  ipv4?: Ipv4Addr | undefined;
  ipv6?: Ipv6Addr | undefined;
  port: number;
}

export interface TunnelInfo {
  tunnel_type: string;
  local_addr: Url | undefined;
  remote_addr: Url | undefined;
}

export interface StunInfo {
  udp_nat_type: NatType;
  tcp_nat_type: NatType;
  last_update_time: number;
  public_ip: string[];
  min_port: number;
  max_port: number;
}

export interface PeerFeatureFlag {
  is_public_server: boolean;
  avoid_relay_data: boolean;
  kcp_input: boolean;
  no_relay_kcp: boolean;
  support_conn_list_sync: boolean;
  quic_input: boolean;
  no_relay_quic: boolean;
}

export interface PortForwardConfigPb {
  bind_addr: SocketAddr | undefined;
  dst_addr: SocketAddr | undefined;
  socket_type: SocketType;
}

export interface ProxyDstInfo {
  dst_addr: SocketAddr | undefined;
}

export interface LimiterConfig {
  /** default 1 means no burst (capacity is same with bps) */
  burst_rate?:
    | number
    | undefined;
  /** default 0 means no limit (unit is B/s) */
  bps?:
    | number
    | undefined;
  /** default 10ms, the period to fill the bucket */
  fill_duration_ms?: number | undefined;
}

export interface SecureModeConfig {
  enabled: boolean;
  /** base64(X25519 private key), used by shared node to present a stable identity */
  local_private_key?:
    | string
    | undefined;
  /** base64(X25519 public key), required if local_private_key is set */
  local_public_key?: string | undefined;
}

function createBaseFlagsInConfig(): FlagsInConfig {
  return {
    default_protocol: "",
    dev_name: "",
    enable_encryption: false,
    enable_ipv6: false,
    mtu: 0,
    latency_first: false,
    enable_exit_node: false,
    no_tun: false,
    use_smoltcp: false,
    relay_network_whitelist: "",
    disable_p2p: false,
    relay_all_peer_rpc: false,
    disable_udp_hole_punching: false,
    multi_thread: false,
    data_compress_algo: 0,
    bind_device: false,
    enable_kcp_proxy: false,
    disable_kcp_input: false,
    disable_relay_kcp: false,
    proxy_forward_by_system: false,
    accept_dns: false,
    private_mode: false,
    enable_quic_proxy: false,
    disable_quic_input: false,
    disable_relay_quic: false,
    quic_listen_port: 0,
    foreign_relay_bps_limit: 0,
    multi_thread_count: 0,
    enable_relay_foreign_network_kcp: false,
    enable_relay_foreign_network_quic: false,
    encryption_algorithm: "",
    disable_sym_hole_punching: false,
    tld_dns_zone: "",
    p2p_only: false,
    disable_tcp_hole_punching: false,
  };
}

export const FlagsInConfig: MessageFns<FlagsInConfig> = {
  fromJSON(object: any): FlagsInConfig {
    return {
      default_protocol: isSet(object.defaultProtocol)
        ? globalThis.String(object.defaultProtocol)
        : isSet(object.default_protocol)
        ? globalThis.String(object.default_protocol)
        : "",
      dev_name: isSet(object.devName)
        ? globalThis.String(object.devName)
        : isSet(object.dev_name)
        ? globalThis.String(object.dev_name)
        : "",
      enable_encryption: isSet(object.enableEncryption)
        ? globalThis.Boolean(object.enableEncryption)
        : isSet(object.enable_encryption)
        ? globalThis.Boolean(object.enable_encryption)
        : false,
      enable_ipv6: isSet(object.enableIpv6)
        ? globalThis.Boolean(object.enableIpv6)
        : isSet(object.enable_ipv6)
        ? globalThis.Boolean(object.enable_ipv6)
        : false,
      mtu: isSet(object.mtu) ? globalThis.Number(object.mtu) : 0,
      latency_first: isSet(object.latencyFirst)
        ? globalThis.Boolean(object.latencyFirst)
        : isSet(object.latency_first)
        ? globalThis.Boolean(object.latency_first)
        : false,
      enable_exit_node: isSet(object.enableExitNode)
        ? globalThis.Boolean(object.enableExitNode)
        : isSet(object.enable_exit_node)
        ? globalThis.Boolean(object.enable_exit_node)
        : false,
      no_tun: isSet(object.noTun)
        ? globalThis.Boolean(object.noTun)
        : isSet(object.no_tun)
        ? globalThis.Boolean(object.no_tun)
        : false,
      use_smoltcp: isSet(object.useSmoltcp)
        ? globalThis.Boolean(object.useSmoltcp)
        : isSet(object.use_smoltcp)
        ? globalThis.Boolean(object.use_smoltcp)
        : false,
      relay_network_whitelist: isSet(object.relayNetworkWhitelist)
        ? globalThis.String(object.relayNetworkWhitelist)
        : isSet(object.relay_network_whitelist)
        ? globalThis.String(object.relay_network_whitelist)
        : "",
      disable_p2p: isSet(object.disableP2p)
        ? globalThis.Boolean(object.disableP2p)
        : isSet(object.disable_p2p)
        ? globalThis.Boolean(object.disable_p2p)
        : false,
      relay_all_peer_rpc: isSet(object.relayAllPeerRpc)
        ? globalThis.Boolean(object.relayAllPeerRpc)
        : isSet(object.relay_all_peer_rpc)
        ? globalThis.Boolean(object.relay_all_peer_rpc)
        : false,
      disable_udp_hole_punching: isSet(object.disableUdpHolePunching)
        ? globalThis.Boolean(object.disableUdpHolePunching)
        : isSet(object.disable_udp_hole_punching)
        ? globalThis.Boolean(object.disable_udp_hole_punching)
        : false,
      multi_thread: isSet(object.multiThread)
        ? globalThis.Boolean(object.multiThread)
        : isSet(object.multi_thread)
        ? globalThis.Boolean(object.multi_thread)
        : false,
      data_compress_algo: isSet(object.dataCompressAlgo)
        ? compressionAlgoPbFromJSON(object.dataCompressAlgo)
        : isSet(object.data_compress_algo)
        ? compressionAlgoPbFromJSON(object.data_compress_algo)
        : 0,
      bind_device: isSet(object.bindDevice)
        ? globalThis.Boolean(object.bindDevice)
        : isSet(object.bind_device)
        ? globalThis.Boolean(object.bind_device)
        : false,
      enable_kcp_proxy: isSet(object.enableKcpProxy)
        ? globalThis.Boolean(object.enableKcpProxy)
        : isSet(object.enable_kcp_proxy)
        ? globalThis.Boolean(object.enable_kcp_proxy)
        : false,
      disable_kcp_input: isSet(object.disableKcpInput)
        ? globalThis.Boolean(object.disableKcpInput)
        : isSet(object.disable_kcp_input)
        ? globalThis.Boolean(object.disable_kcp_input)
        : false,
      disable_relay_kcp: isSet(object.disableRelayKcp)
        ? globalThis.Boolean(object.disableRelayKcp)
        : isSet(object.disable_relay_kcp)
        ? globalThis.Boolean(object.disable_relay_kcp)
        : false,
      proxy_forward_by_system: isSet(object.proxyForwardBySystem)
        ? globalThis.Boolean(object.proxyForwardBySystem)
        : isSet(object.proxy_forward_by_system)
        ? globalThis.Boolean(object.proxy_forward_by_system)
        : false,
      accept_dns: isSet(object.acceptDns)
        ? globalThis.Boolean(object.acceptDns)
        : isSet(object.accept_dns)
        ? globalThis.Boolean(object.accept_dns)
        : false,
      private_mode: isSet(object.privateMode)
        ? globalThis.Boolean(object.privateMode)
        : isSet(object.private_mode)
        ? globalThis.Boolean(object.private_mode)
        : false,
      enable_quic_proxy: isSet(object.enableQuicProxy)
        ? globalThis.Boolean(object.enableQuicProxy)
        : isSet(object.enable_quic_proxy)
        ? globalThis.Boolean(object.enable_quic_proxy)
        : false,
      disable_quic_input: isSet(object.disableQuicInput)
        ? globalThis.Boolean(object.disableQuicInput)
        : isSet(object.disable_quic_input)
        ? globalThis.Boolean(object.disable_quic_input)
        : false,
      disable_relay_quic: isSet(object.disableRelayQuic)
        ? globalThis.Boolean(object.disableRelayQuic)
        : isSet(object.disable_relay_quic)
        ? globalThis.Boolean(object.disable_relay_quic)
        : false,
      quic_listen_port: isSet(object.quicListenPort)
        ? globalThis.Number(object.quicListenPort)
        : isSet(object.quic_listen_port)
        ? globalThis.Number(object.quic_listen_port)
        : 0,
      foreign_relay_bps_limit: isSet(object.foreignRelayBpsLimit)
        ? globalThis.Number(object.foreignRelayBpsLimit)
        : isSet(object.foreign_relay_bps_limit)
        ? globalThis.Number(object.foreign_relay_bps_limit)
        : 0,
      multi_thread_count: isSet(object.multiThreadCount)
        ? globalThis.Number(object.multiThreadCount)
        : isSet(object.multi_thread_count)
        ? globalThis.Number(object.multi_thread_count)
        : 0,
      enable_relay_foreign_network_kcp: isSet(object.enableRelayForeignNetworkKcp)
        ? globalThis.Boolean(object.enableRelayForeignNetworkKcp)
        : isSet(object.enable_relay_foreign_network_kcp)
        ? globalThis.Boolean(object.enable_relay_foreign_network_kcp)
        : false,
      enable_relay_foreign_network_quic: isSet(object.enableRelayForeignNetworkQuic)
        ? globalThis.Boolean(object.enableRelayForeignNetworkQuic)
        : isSet(object.enable_relay_foreign_network_quic)
        ? globalThis.Boolean(object.enable_relay_foreign_network_quic)
        : false,
      encryption_algorithm: isSet(object.encryptionAlgorithm)
        ? globalThis.String(object.encryptionAlgorithm)
        : isSet(object.encryption_algorithm)
        ? globalThis.String(object.encryption_algorithm)
        : "",
      disable_sym_hole_punching: isSet(object.disableSymHolePunching)
        ? globalThis.Boolean(object.disableSymHolePunching)
        : isSet(object.disable_sym_hole_punching)
        ? globalThis.Boolean(object.disable_sym_hole_punching)
        : false,
      tld_dns_zone: isSet(object.tldDnsZone)
        ? globalThis.String(object.tldDnsZone)
        : isSet(object.tld_dns_zone)
        ? globalThis.String(object.tld_dns_zone)
        : "",
      p2p_only: isSet(object.p2pOnly)
        ? globalThis.Boolean(object.p2pOnly)
        : isSet(object.p2p_only)
        ? globalThis.Boolean(object.p2p_only)
        : false,
      disable_tcp_hole_punching: isSet(object.disableTcpHolePunching)
        ? globalThis.Boolean(object.disableTcpHolePunching)
        : isSet(object.disable_tcp_hole_punching)
        ? globalThis.Boolean(object.disable_tcp_hole_punching)
        : false,
    };
  },

  toJSON(message: FlagsInConfig): unknown {
    const obj: any = {};
    if (message.default_protocol !== "") {
      obj.defaultProtocol = message.default_protocol;
    }
    if (message.dev_name !== "") {
      obj.devName = message.dev_name;
    }
    if (message.enable_encryption !== false) {
      obj.enableEncryption = message.enable_encryption;
    }
    if (message.enable_ipv6 !== false) {
      obj.enableIpv6 = message.enable_ipv6;
    }
    if (message.mtu !== 0) {
      obj.mtu = Math.round(message.mtu);
    }
    if (message.latency_first !== false) {
      obj.latencyFirst = message.latency_first;
    }
    if (message.enable_exit_node !== false) {
      obj.enableExitNode = message.enable_exit_node;
    }
    if (message.no_tun !== false) {
      obj.noTun = message.no_tun;
    }
    if (message.use_smoltcp !== false) {
      obj.useSmoltcp = message.use_smoltcp;
    }
    if (message.relay_network_whitelist !== "") {
      obj.relayNetworkWhitelist = message.relay_network_whitelist;
    }
    if (message.disable_p2p !== false) {
      obj.disableP2p = message.disable_p2p;
    }
    if (message.relay_all_peer_rpc !== false) {
      obj.relayAllPeerRpc = message.relay_all_peer_rpc;
    }
    if (message.disable_udp_hole_punching !== false) {
      obj.disableUdpHolePunching = message.disable_udp_hole_punching;
    }
    if (message.multi_thread !== false) {
      obj.multiThread = message.multi_thread;
    }
    if (message.data_compress_algo !== 0) {
      obj.dataCompressAlgo = compressionAlgoPbToJSON(message.data_compress_algo);
    }
    if (message.bind_device !== false) {
      obj.bindDevice = message.bind_device;
    }
    if (message.enable_kcp_proxy !== false) {
      obj.enableKcpProxy = message.enable_kcp_proxy;
    }
    if (message.disable_kcp_input !== false) {
      obj.disableKcpInput = message.disable_kcp_input;
    }
    if (message.disable_relay_kcp !== false) {
      obj.disableRelayKcp = message.disable_relay_kcp;
    }
    if (message.proxy_forward_by_system !== false) {
      obj.proxyForwardBySystem = message.proxy_forward_by_system;
    }
    if (message.accept_dns !== false) {
      obj.acceptDns = message.accept_dns;
    }
    if (message.private_mode !== false) {
      obj.privateMode = message.private_mode;
    }
    if (message.enable_quic_proxy !== false) {
      obj.enableQuicProxy = message.enable_quic_proxy;
    }
    if (message.disable_quic_input !== false) {
      obj.disableQuicInput = message.disable_quic_input;
    }
    if (message.disable_relay_quic !== false) {
      obj.disableRelayQuic = message.disable_relay_quic;
    }
    if (message.quic_listen_port !== 0) {
      obj.quicListenPort = Math.round(message.quic_listen_port);
    }
    if (message.foreign_relay_bps_limit !== 0) {
      obj.foreignRelayBpsLimit = Math.round(message.foreign_relay_bps_limit);
    }
    if (message.multi_thread_count !== 0) {
      obj.multiThreadCount = Math.round(message.multi_thread_count);
    }
    if (message.enable_relay_foreign_network_kcp !== false) {
      obj.enableRelayForeignNetworkKcp = message.enable_relay_foreign_network_kcp;
    }
    if (message.enable_relay_foreign_network_quic !== false) {
      obj.enableRelayForeignNetworkQuic = message.enable_relay_foreign_network_quic;
    }
    if (message.encryption_algorithm !== "") {
      obj.encryptionAlgorithm = message.encryption_algorithm;
    }
    if (message.disable_sym_hole_punching !== false) {
      obj.disableSymHolePunching = message.disable_sym_hole_punching;
    }
    if (message.tld_dns_zone !== "") {
      obj.tldDnsZone = message.tld_dns_zone;
    }
    if (message.p2p_only !== false) {
      obj.p2pOnly = message.p2p_only;
    }
    if (message.disable_tcp_hole_punching !== false) {
      obj.disableTcpHolePunching = message.disable_tcp_hole_punching;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlagsInConfig>, I>>(base?: I): FlagsInConfig {
    return FlagsInConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlagsInConfig>, I>>(object: I): FlagsInConfig {
    const message = createBaseFlagsInConfig();
    message.default_protocol = object.default_protocol ?? "";
    message.dev_name = object.dev_name ?? "";
    message.enable_encryption = object.enable_encryption ?? false;
    message.enable_ipv6 = object.enable_ipv6 ?? false;
    message.mtu = object.mtu ?? 0;
    message.latency_first = object.latency_first ?? false;
    message.enable_exit_node = object.enable_exit_node ?? false;
    message.no_tun = object.no_tun ?? false;
    message.use_smoltcp = object.use_smoltcp ?? false;
    message.relay_network_whitelist = object.relay_network_whitelist ?? "";
    message.disable_p2p = object.disable_p2p ?? false;
    message.relay_all_peer_rpc = object.relay_all_peer_rpc ?? false;
    message.disable_udp_hole_punching = object.disable_udp_hole_punching ?? false;
    message.multi_thread = object.multi_thread ?? false;
    message.data_compress_algo = object.data_compress_algo ?? 0;
    message.bind_device = object.bind_device ?? false;
    message.enable_kcp_proxy = object.enable_kcp_proxy ?? false;
    message.disable_kcp_input = object.disable_kcp_input ?? false;
    message.disable_relay_kcp = object.disable_relay_kcp ?? false;
    message.proxy_forward_by_system = object.proxy_forward_by_system ?? false;
    message.accept_dns = object.accept_dns ?? false;
    message.private_mode = object.private_mode ?? false;
    message.enable_quic_proxy = object.enable_quic_proxy ?? false;
    message.disable_quic_input = object.disable_quic_input ?? false;
    message.disable_relay_quic = object.disable_relay_quic ?? false;
    message.quic_listen_port = object.quic_listen_port ?? 0;
    message.foreign_relay_bps_limit = object.foreign_relay_bps_limit ?? 0;
    message.multi_thread_count = object.multi_thread_count ?? 0;
    message.enable_relay_foreign_network_kcp = object.enable_relay_foreign_network_kcp ?? false;
    message.enable_relay_foreign_network_quic = object.enable_relay_foreign_network_quic ?? false;
    message.encryption_algorithm = object.encryption_algorithm ?? "";
    message.disable_sym_hole_punching = object.disable_sym_hole_punching ?? false;
    message.tld_dns_zone = object.tld_dns_zone ?? "";
    message.p2p_only = object.p2p_only ?? false;
    message.disable_tcp_hole_punching = object.disable_tcp_hole_punching ?? false;
    return message;
  },
};

function createBaseRpcDescriptor(): RpcDescriptor {
  return { domain_name: "", proto_name: "", service_name: "", method_index: 0 };
}

export const RpcDescriptor: MessageFns<RpcDescriptor> = {
  fromJSON(object: any): RpcDescriptor {
    return {
      domain_name: isSet(object.domainName)
        ? globalThis.String(object.domainName)
        : isSet(object.domain_name)
        ? globalThis.String(object.domain_name)
        : "",
      proto_name: isSet(object.protoName)
        ? globalThis.String(object.protoName)
        : isSet(object.proto_name)
        ? globalThis.String(object.proto_name)
        : "",
      service_name: isSet(object.serviceName)
        ? globalThis.String(object.serviceName)
        : isSet(object.service_name)
        ? globalThis.String(object.service_name)
        : "",
      method_index: isSet(object.methodIndex)
        ? globalThis.Number(object.methodIndex)
        : isSet(object.method_index)
        ? globalThis.Number(object.method_index)
        : 0,
    };
  },

  toJSON(message: RpcDescriptor): unknown {
    const obj: any = {};
    if (message.domain_name !== "") {
      obj.domainName = message.domain_name;
    }
    if (message.proto_name !== "") {
      obj.protoName = message.proto_name;
    }
    if (message.service_name !== "") {
      obj.serviceName = message.service_name;
    }
    if (message.method_index !== 0) {
      obj.methodIndex = Math.round(message.method_index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcDescriptor>, I>>(base?: I): RpcDescriptor {
    return RpcDescriptor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcDescriptor>, I>>(object: I): RpcDescriptor {
    const message = createBaseRpcDescriptor();
    message.domain_name = object.domain_name ?? "";
    message.proto_name = object.proto_name ?? "";
    message.service_name = object.service_name ?? "";
    message.method_index = object.method_index ?? 0;
    return message;
  },
};

function createBaseRpcRequest(): RpcRequest {
  return { descriptor: undefined, request: new Uint8Array(0), timeout_ms: 0 };
}

export const RpcRequest: MessageFns<RpcRequest> = {
  fromJSON(object: any): RpcRequest {
    return {
      descriptor: isSet(object.descriptor) ? RpcDescriptor.fromJSON(object.descriptor) : undefined,
      request: isSet(object.request) ? bytesFromBase64(object.request) : new Uint8Array(0),
      timeout_ms: isSet(object.timeoutMs)
        ? globalThis.Number(object.timeoutMs)
        : isSet(object.timeout_ms)
        ? globalThis.Number(object.timeout_ms)
        : 0,
    };
  },

  toJSON(message: RpcRequest): unknown {
    const obj: any = {};
    if (message.descriptor !== undefined) {
      obj.descriptor = RpcDescriptor.toJSON(message.descriptor);
    }
    if (message.request.length !== 0) {
      obj.request = base64FromBytes(message.request);
    }
    if (message.timeout_ms !== 0) {
      obj.timeoutMs = Math.round(message.timeout_ms);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcRequest>, I>>(base?: I): RpcRequest {
    return RpcRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcRequest>, I>>(object: I): RpcRequest {
    const message = createBaseRpcRequest();
    message.descriptor = (object.descriptor !== undefined && object.descriptor !== null)
      ? RpcDescriptor.fromPartial(object.descriptor)
      : undefined;
    message.request = object.request ?? new Uint8Array(0);
    message.timeout_ms = object.timeout_ms ?? 0;
    return message;
  },
};

function createBaseRpcResponse(): RpcResponse {
  return { response: new Uint8Array(0), error: undefined, runtime_us: 0 };
}

export const RpcResponse: MessageFns<RpcResponse> = {
  fromJSON(object: any): RpcResponse {
    return {
      response: isSet(object.response) ? bytesFromBase64(object.response) : new Uint8Array(0),
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      runtime_us: isSet(object.runtimeUs)
        ? globalThis.Number(object.runtimeUs)
        : isSet(object.runtime_us)
        ? globalThis.Number(object.runtime_us)
        : 0,
    };
  },

  toJSON(message: RpcResponse): unknown {
    const obj: any = {};
    if (message.response.length !== 0) {
      obj.response = base64FromBytes(message.response);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.runtime_us !== 0) {
      obj.runtimeUs = Math.round(message.runtime_us);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcResponse>, I>>(base?: I): RpcResponse {
    return RpcResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcResponse>, I>>(object: I): RpcResponse {
    const message = createBaseRpcResponse();
    message.response = object.response ?? new Uint8Array(0);
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.runtime_us = object.runtime_us ?? 0;
    return message;
  },
};

function createBaseRpcCompressionInfo(): RpcCompressionInfo {
  return { algo: 0, accepted_algo: 0 };
}

export const RpcCompressionInfo: MessageFns<RpcCompressionInfo> = {
  fromJSON(object: any): RpcCompressionInfo {
    return {
      algo: isSet(object.algo) ? compressionAlgoPbFromJSON(object.algo) : 0,
      accepted_algo: isSet(object.acceptedAlgo)
        ? compressionAlgoPbFromJSON(object.acceptedAlgo)
        : isSet(object.accepted_algo)
        ? compressionAlgoPbFromJSON(object.accepted_algo)
        : 0,
    };
  },

  toJSON(message: RpcCompressionInfo): unknown {
    const obj: any = {};
    if (message.algo !== 0) {
      obj.algo = compressionAlgoPbToJSON(message.algo);
    }
    if (message.accepted_algo !== 0) {
      obj.acceptedAlgo = compressionAlgoPbToJSON(message.accepted_algo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcCompressionInfo>, I>>(base?: I): RpcCompressionInfo {
    return RpcCompressionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcCompressionInfo>, I>>(object: I): RpcCompressionInfo {
    const message = createBaseRpcCompressionInfo();
    message.algo = object.algo ?? 0;
    message.accepted_algo = object.accepted_algo ?? 0;
    return message;
  },
};

function createBaseRpcPacket(): RpcPacket {
  return {
    from_peer: 0,
    to_peer: 0,
    transaction_id: 0,
    descriptor: undefined,
    body: new Uint8Array(0),
    is_request: false,
    total_pieces: 0,
    piece_idx: 0,
    trace_id: 0,
    compression_info: undefined,
  };
}

export const RpcPacket: MessageFns<RpcPacket> = {
  fromJSON(object: any): RpcPacket {
    return {
      from_peer: isSet(object.fromPeer)
        ? globalThis.Number(object.fromPeer)
        : isSet(object.from_peer)
        ? globalThis.Number(object.from_peer)
        : 0,
      to_peer: isSet(object.toPeer)
        ? globalThis.Number(object.toPeer)
        : isSet(object.to_peer)
        ? globalThis.Number(object.to_peer)
        : 0,
      transaction_id: isSet(object.transactionId)
        ? globalThis.Number(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.Number(object.transaction_id)
        : 0,
      descriptor: isSet(object.descriptor) ? RpcDescriptor.fromJSON(object.descriptor) : undefined,
      body: isSet(object.body) ? bytesFromBase64(object.body) : new Uint8Array(0),
      is_request: isSet(object.isRequest)
        ? globalThis.Boolean(object.isRequest)
        : isSet(object.is_request)
        ? globalThis.Boolean(object.is_request)
        : false,
      total_pieces: isSet(object.totalPieces)
        ? globalThis.Number(object.totalPieces)
        : isSet(object.total_pieces)
        ? globalThis.Number(object.total_pieces)
        : 0,
      piece_idx: isSet(object.pieceIdx)
        ? globalThis.Number(object.pieceIdx)
        : isSet(object.piece_idx)
        ? globalThis.Number(object.piece_idx)
        : 0,
      trace_id: isSet(object.traceId)
        ? globalThis.Number(object.traceId)
        : isSet(object.trace_id)
        ? globalThis.Number(object.trace_id)
        : 0,
      compression_info: isSet(object.compressionInfo)
        ? RpcCompressionInfo.fromJSON(object.compressionInfo)
        : isSet(object.compression_info)
        ? RpcCompressionInfo.fromJSON(object.compression_info)
        : undefined,
    };
  },

  toJSON(message: RpcPacket): unknown {
    const obj: any = {};
    if (message.from_peer !== 0) {
      obj.fromPeer = Math.round(message.from_peer);
    }
    if (message.to_peer !== 0) {
      obj.toPeer = Math.round(message.to_peer);
    }
    if (message.transaction_id !== 0) {
      obj.transactionId = Math.round(message.transaction_id);
    }
    if (message.descriptor !== undefined) {
      obj.descriptor = RpcDescriptor.toJSON(message.descriptor);
    }
    if (message.body.length !== 0) {
      obj.body = base64FromBytes(message.body);
    }
    if (message.is_request !== false) {
      obj.isRequest = message.is_request;
    }
    if (message.total_pieces !== 0) {
      obj.totalPieces = Math.round(message.total_pieces);
    }
    if (message.piece_idx !== 0) {
      obj.pieceIdx = Math.round(message.piece_idx);
    }
    if (message.trace_id !== 0) {
      obj.traceId = Math.round(message.trace_id);
    }
    if (message.compression_info !== undefined) {
      obj.compressionInfo = RpcCompressionInfo.toJSON(message.compression_info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcPacket>, I>>(base?: I): RpcPacket {
    return RpcPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcPacket>, I>>(object: I): RpcPacket {
    const message = createBaseRpcPacket();
    message.from_peer = object.from_peer ?? 0;
    message.to_peer = object.to_peer ?? 0;
    message.transaction_id = object.transaction_id ?? 0;
    message.descriptor = (object.descriptor !== undefined && object.descriptor !== null)
      ? RpcDescriptor.fromPartial(object.descriptor)
      : undefined;
    message.body = object.body ?? new Uint8Array(0);
    message.is_request = object.is_request ?? false;
    message.total_pieces = object.total_pieces ?? 0;
    message.piece_idx = object.piece_idx ?? 0;
    message.trace_id = object.trace_id ?? 0;
    message.compression_info = (object.compression_info !== undefined && object.compression_info !== null)
      ? RpcCompressionInfo.fromPartial(object.compression_info)
      : undefined;
    return message;
  },
};

function createBaseVoid(): Void {
  return {};
}

export const Void: MessageFns<Void> = {
  fromJSON(_: any): Void {
    return {};
  },

  toJSON(_: Void): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Void>, I>>(base?: I): Void {
    return Void.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Void>, I>>(_: I): Void {
    const message = createBaseVoid();
    return message;
  },
};

function createBaseUUID(): UUID {
  return { part1: 0, part2: 0, part3: 0, part4: 0 };
}

export const UUID: MessageFns<UUID> = {
  fromJSON(object: any): UUID {
    return {
      part1: isSet(object.part1) ? globalThis.Number(object.part1) : 0,
      part2: isSet(object.part2) ? globalThis.Number(object.part2) : 0,
      part3: isSet(object.part3) ? globalThis.Number(object.part3) : 0,
      part4: isSet(object.part4) ? globalThis.Number(object.part4) : 0,
    };
  },

  toJSON(message: UUID): unknown {
    const obj: any = {};
    if (message.part1 !== 0) {
      obj.part1 = Math.round(message.part1);
    }
    if (message.part2 !== 0) {
      obj.part2 = Math.round(message.part2);
    }
    if (message.part3 !== 0) {
      obj.part3 = Math.round(message.part3);
    }
    if (message.part4 !== 0) {
      obj.part4 = Math.round(message.part4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UUID>, I>>(base?: I): UUID {
    return UUID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UUID>, I>>(object: I): UUID {
    const message = createBaseUUID();
    message.part1 = object.part1 ?? 0;
    message.part2 = object.part2 ?? 0;
    message.part3 = object.part3 ?? 0;
    message.part4 = object.part4 ?? 0;
    return message;
  },
};

function createBaseIpv4Addr(): Ipv4Addr {
  return { addr: 0 };
}

export const Ipv4Addr: MessageFns<Ipv4Addr> = {
  fromJSON(object: any): Ipv4Addr {
    return { addr: isSet(object.addr) ? globalThis.Number(object.addr) : 0 };
  },

  toJSON(message: Ipv4Addr): unknown {
    const obj: any = {};
    if (message.addr !== 0) {
      obj.addr = Math.round(message.addr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv4Addr>, I>>(base?: I): Ipv4Addr {
    return Ipv4Addr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv4Addr>, I>>(object: I): Ipv4Addr {
    const message = createBaseIpv4Addr();
    message.addr = object.addr ?? 0;
    return message;
  },
};

function createBaseIpv6Addr(): Ipv6Addr {
  return { part1: 0, part2: 0, part3: 0, part4: 0 };
}

export const Ipv6Addr: MessageFns<Ipv6Addr> = {
  fromJSON(object: any): Ipv6Addr {
    return {
      part1: isSet(object.part1) ? globalThis.Number(object.part1) : 0,
      part2: isSet(object.part2) ? globalThis.Number(object.part2) : 0,
      part3: isSet(object.part3) ? globalThis.Number(object.part3) : 0,
      part4: isSet(object.part4) ? globalThis.Number(object.part4) : 0,
    };
  },

  toJSON(message: Ipv6Addr): unknown {
    const obj: any = {};
    if (message.part1 !== 0) {
      obj.part1 = Math.round(message.part1);
    }
    if (message.part2 !== 0) {
      obj.part2 = Math.round(message.part2);
    }
    if (message.part3 !== 0) {
      obj.part3 = Math.round(message.part3);
    }
    if (message.part4 !== 0) {
      obj.part4 = Math.round(message.part4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv6Addr>, I>>(base?: I): Ipv6Addr {
    return Ipv6Addr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv6Addr>, I>>(object: I): Ipv6Addr {
    const message = createBaseIpv6Addr();
    message.part1 = object.part1 ?? 0;
    message.part2 = object.part2 ?? 0;
    message.part3 = object.part3 ?? 0;
    message.part4 = object.part4 ?? 0;
    return message;
  },
};

function createBaseIpAddr(): IpAddr {
  return { ipv4: undefined, ipv6: undefined };
}

export const IpAddr: MessageFns<IpAddr> = {
  fromJSON(object: any): IpAddr {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Addr.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Addr.fromJSON(object.ipv6) : undefined,
    };
  },

  toJSON(message: IpAddr): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Addr.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Addr.toJSON(message.ipv6);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IpAddr>, I>>(base?: I): IpAddr {
    return IpAddr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IpAddr>, I>>(object: I): IpAddr {
    const message = createBaseIpAddr();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Addr.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Addr.fromPartial(object.ipv6) : undefined;
    return message;
  },
};

function createBaseIpv4Inet(): Ipv4Inet {
  return { address: undefined, network_length: 0 };
}

export const Ipv4Inet: MessageFns<Ipv4Inet> = {
  fromJSON(object: any): Ipv4Inet {
    return {
      address: isSet(object.address) ? Ipv4Addr.fromJSON(object.address) : undefined,
      network_length: isSet(object.networkLength)
        ? globalThis.Number(object.networkLength)
        : isSet(object.network_length)
        ? globalThis.Number(object.network_length)
        : 0,
    };
  },

  toJSON(message: Ipv4Inet): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = Ipv4Addr.toJSON(message.address);
    }
    if (message.network_length !== 0) {
      obj.networkLength = Math.round(message.network_length);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv4Inet>, I>>(base?: I): Ipv4Inet {
    return Ipv4Inet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv4Inet>, I>>(object: I): Ipv4Inet {
    const message = createBaseIpv4Inet();
    message.address = (object.address !== undefined && object.address !== null)
      ? Ipv4Addr.fromPartial(object.address)
      : undefined;
    message.network_length = object.network_length ?? 0;
    return message;
  },
};

function createBaseIpv6Inet(): Ipv6Inet {
  return { address: undefined, network_length: 0 };
}

export const Ipv6Inet: MessageFns<Ipv6Inet> = {
  fromJSON(object: any): Ipv6Inet {
    return {
      address: isSet(object.address) ? Ipv6Addr.fromJSON(object.address) : undefined,
      network_length: isSet(object.networkLength)
        ? globalThis.Number(object.networkLength)
        : isSet(object.network_length)
        ? globalThis.Number(object.network_length)
        : 0,
    };
  },

  toJSON(message: Ipv6Inet): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = Ipv6Addr.toJSON(message.address);
    }
    if (message.network_length !== 0) {
      obj.networkLength = Math.round(message.network_length);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv6Inet>, I>>(base?: I): Ipv6Inet {
    return Ipv6Inet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv6Inet>, I>>(object: I): Ipv6Inet {
    const message = createBaseIpv6Inet();
    message.address = (object.address !== undefined && object.address !== null)
      ? Ipv6Addr.fromPartial(object.address)
      : undefined;
    message.network_length = object.network_length ?? 0;
    return message;
  },
};

function createBaseIpInet(): IpInet {
  return { ipv4: undefined, ipv6: undefined };
}

export const IpInet: MessageFns<IpInet> = {
  fromJSON(object: any): IpInet {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Inet.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Inet.fromJSON(object.ipv6) : undefined,
    };
  },

  toJSON(message: IpInet): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Inet.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Inet.toJSON(message.ipv6);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IpInet>, I>>(base?: I): IpInet {
    return IpInet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IpInet>, I>>(object: I): IpInet {
    const message = createBaseIpInet();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Inet.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Inet.fromPartial(object.ipv6) : undefined;
    return message;
  },
};

function createBaseUrl(): Url {
  return { url: "" };
}

export const Url: MessageFns<Url> = {
  fromJSON(object: any): Url {
    return { url: isSet(object.url) ? globalThis.String(object.url) : "" };
  },

  toJSON(message: Url): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Url>, I>>(base?: I): Url {
    return Url.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Url>, I>>(object: I): Url {
    const message = createBaseUrl();
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseSocketAddr(): SocketAddr {
  return { ipv4: undefined, ipv6: undefined, port: 0 };
}

export const SocketAddr: MessageFns<SocketAddr> = {
  fromJSON(object: any): SocketAddr {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Addr.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Addr.fromJSON(object.ipv6) : undefined,
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
    };
  },

  toJSON(message: SocketAddr): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Addr.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Addr.toJSON(message.ipv6);
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketAddr>, I>>(base?: I): SocketAddr {
    return SocketAddr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketAddr>, I>>(object: I): SocketAddr {
    const message = createBaseSocketAddr();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Addr.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Addr.fromPartial(object.ipv6) : undefined;
    message.port = object.port ?? 0;
    return message;
  },
};

function createBaseTunnelInfo(): TunnelInfo {
  return { tunnel_type: "", local_addr: undefined, remote_addr: undefined };
}

export const TunnelInfo: MessageFns<TunnelInfo> = {
  fromJSON(object: any): TunnelInfo {
    return {
      tunnel_type: isSet(object.tunnelType)
        ? globalThis.String(object.tunnelType)
        : isSet(object.tunnel_type)
        ? globalThis.String(object.tunnel_type)
        : "",
      local_addr: isSet(object.localAddr)
        ? Url.fromJSON(object.localAddr)
        : isSet(object.local_addr)
        ? Url.fromJSON(object.local_addr)
        : undefined,
      remote_addr: isSet(object.remoteAddr)
        ? Url.fromJSON(object.remoteAddr)
        : isSet(object.remote_addr)
        ? Url.fromJSON(object.remote_addr)
        : undefined,
    };
  },

  toJSON(message: TunnelInfo): unknown {
    const obj: any = {};
    if (message.tunnel_type !== "") {
      obj.tunnelType = message.tunnel_type;
    }
    if (message.local_addr !== undefined) {
      obj.localAddr = Url.toJSON(message.local_addr);
    }
    if (message.remote_addr !== undefined) {
      obj.remoteAddr = Url.toJSON(message.remote_addr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelInfo>, I>>(base?: I): TunnelInfo {
    return TunnelInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelInfo>, I>>(object: I): TunnelInfo {
    const message = createBaseTunnelInfo();
    message.tunnel_type = object.tunnel_type ?? "";
    message.local_addr = (object.local_addr !== undefined && object.local_addr !== null)
      ? Url.fromPartial(object.local_addr)
      : undefined;
    message.remote_addr = (object.remote_addr !== undefined && object.remote_addr !== null)
      ? Url.fromPartial(object.remote_addr)
      : undefined;
    return message;
  },
};

function createBaseStunInfo(): StunInfo {
  return { udp_nat_type: 0, tcp_nat_type: 0, last_update_time: 0, public_ip: [], min_port: 0, max_port: 0 };
}

export const StunInfo: MessageFns<StunInfo> = {
  fromJSON(object: any): StunInfo {
    return {
      udp_nat_type: isSet(object.udpNatType)
        ? natTypeFromJSON(object.udpNatType)
        : isSet(object.udp_nat_type)
        ? natTypeFromJSON(object.udp_nat_type)
        : 0,
      tcp_nat_type: isSet(object.tcpNatType)
        ? natTypeFromJSON(object.tcpNatType)
        : isSet(object.tcp_nat_type)
        ? natTypeFromJSON(object.tcp_nat_type)
        : 0,
      last_update_time: isSet(object.lastUpdateTime)
        ? globalThis.Number(object.lastUpdateTime)
        : isSet(object.last_update_time)
        ? globalThis.Number(object.last_update_time)
        : 0,
      public_ip: globalThis.Array.isArray(object?.publicIp)
        ? object.publicIp.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.public_ip)
        ? object.public_ip.map((e: any) => globalThis.String(e))
        : [],
      min_port: isSet(object.minPort)
        ? globalThis.Number(object.minPort)
        : isSet(object.min_port)
        ? globalThis.Number(object.min_port)
        : 0,
      max_port: isSet(object.maxPort)
        ? globalThis.Number(object.maxPort)
        : isSet(object.max_port)
        ? globalThis.Number(object.max_port)
        : 0,
    };
  },

  toJSON(message: StunInfo): unknown {
    const obj: any = {};
    if (message.udp_nat_type !== 0) {
      obj.udpNatType = natTypeToJSON(message.udp_nat_type);
    }
    if (message.tcp_nat_type !== 0) {
      obj.tcpNatType = natTypeToJSON(message.tcp_nat_type);
    }
    if (message.last_update_time !== 0) {
      obj.lastUpdateTime = Math.round(message.last_update_time);
    }
    if (message.public_ip?.length) {
      obj.publicIp = message.public_ip;
    }
    if (message.min_port !== 0) {
      obj.minPort = Math.round(message.min_port);
    }
    if (message.max_port !== 0) {
      obj.maxPort = Math.round(message.max_port);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StunInfo>, I>>(base?: I): StunInfo {
    return StunInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StunInfo>, I>>(object: I): StunInfo {
    const message = createBaseStunInfo();
    message.udp_nat_type = object.udp_nat_type ?? 0;
    message.tcp_nat_type = object.tcp_nat_type ?? 0;
    message.last_update_time = object.last_update_time ?? 0;
    message.public_ip = object.public_ip?.map((e) => e) || [];
    message.min_port = object.min_port ?? 0;
    message.max_port = object.max_port ?? 0;
    return message;
  },
};

function createBasePeerFeatureFlag(): PeerFeatureFlag {
  return {
    is_public_server: false,
    avoid_relay_data: false,
    kcp_input: false,
    no_relay_kcp: false,
    support_conn_list_sync: false,
    quic_input: false,
    no_relay_quic: false,
  };
}

export const PeerFeatureFlag: MessageFns<PeerFeatureFlag> = {
  fromJSON(object: any): PeerFeatureFlag {
    return {
      is_public_server: isSet(object.isPublicServer)
        ? globalThis.Boolean(object.isPublicServer)
        : isSet(object.is_public_server)
        ? globalThis.Boolean(object.is_public_server)
        : false,
      avoid_relay_data: isSet(object.avoidRelayData)
        ? globalThis.Boolean(object.avoidRelayData)
        : isSet(object.avoid_relay_data)
        ? globalThis.Boolean(object.avoid_relay_data)
        : false,
      kcp_input: isSet(object.kcpInput)
        ? globalThis.Boolean(object.kcpInput)
        : isSet(object.kcp_input)
        ? globalThis.Boolean(object.kcp_input)
        : false,
      no_relay_kcp: isSet(object.noRelayKcp)
        ? globalThis.Boolean(object.noRelayKcp)
        : isSet(object.no_relay_kcp)
        ? globalThis.Boolean(object.no_relay_kcp)
        : false,
      support_conn_list_sync: isSet(object.supportConnListSync)
        ? globalThis.Boolean(object.supportConnListSync)
        : isSet(object.support_conn_list_sync)
        ? globalThis.Boolean(object.support_conn_list_sync)
        : false,
      quic_input: isSet(object.quicInput)
        ? globalThis.Boolean(object.quicInput)
        : isSet(object.quic_input)
        ? globalThis.Boolean(object.quic_input)
        : false,
      no_relay_quic: isSet(object.noRelayQuic)
        ? globalThis.Boolean(object.noRelayQuic)
        : isSet(object.no_relay_quic)
        ? globalThis.Boolean(object.no_relay_quic)
        : false,
    };
  },

  toJSON(message: PeerFeatureFlag): unknown {
    const obj: any = {};
    if (message.is_public_server !== false) {
      obj.isPublicServer = message.is_public_server;
    }
    if (message.avoid_relay_data !== false) {
      obj.avoidRelayData = message.avoid_relay_data;
    }
    if (message.kcp_input !== false) {
      obj.kcpInput = message.kcp_input;
    }
    if (message.no_relay_kcp !== false) {
      obj.noRelayKcp = message.no_relay_kcp;
    }
    if (message.support_conn_list_sync !== false) {
      obj.supportConnListSync = message.support_conn_list_sync;
    }
    if (message.quic_input !== false) {
      obj.quicInput = message.quic_input;
    }
    if (message.no_relay_quic !== false) {
      obj.noRelayQuic = message.no_relay_quic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerFeatureFlag>, I>>(base?: I): PeerFeatureFlag {
    return PeerFeatureFlag.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerFeatureFlag>, I>>(object: I): PeerFeatureFlag {
    const message = createBasePeerFeatureFlag();
    message.is_public_server = object.is_public_server ?? false;
    message.avoid_relay_data = object.avoid_relay_data ?? false;
    message.kcp_input = object.kcp_input ?? false;
    message.no_relay_kcp = object.no_relay_kcp ?? false;
    message.support_conn_list_sync = object.support_conn_list_sync ?? false;
    message.quic_input = object.quic_input ?? false;
    message.no_relay_quic = object.no_relay_quic ?? false;
    return message;
  },
};

function createBasePortForwardConfigPb(): PortForwardConfigPb {
  return { bind_addr: undefined, dst_addr: undefined, socket_type: 0 };
}

export const PortForwardConfigPb: MessageFns<PortForwardConfigPb> = {
  fromJSON(object: any): PortForwardConfigPb {
    return {
      bind_addr: isSet(object.bindAddr)
        ? SocketAddr.fromJSON(object.bindAddr)
        : isSet(object.bind_addr)
        ? SocketAddr.fromJSON(object.bind_addr)
        : undefined,
      dst_addr: isSet(object.dstAddr)
        ? SocketAddr.fromJSON(object.dstAddr)
        : isSet(object.dst_addr)
        ? SocketAddr.fromJSON(object.dst_addr)
        : undefined,
      socket_type: isSet(object.socketType)
        ? socketTypeFromJSON(object.socketType)
        : isSet(object.socket_type)
        ? socketTypeFromJSON(object.socket_type)
        : 0,
    };
  },

  toJSON(message: PortForwardConfigPb): unknown {
    const obj: any = {};
    if (message.bind_addr !== undefined) {
      obj.bindAddr = SocketAddr.toJSON(message.bind_addr);
    }
    if (message.dst_addr !== undefined) {
      obj.dstAddr = SocketAddr.toJSON(message.dst_addr);
    }
    if (message.socket_type !== 0) {
      obj.socketType = socketTypeToJSON(message.socket_type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortForwardConfigPb>, I>>(base?: I): PortForwardConfigPb {
    return PortForwardConfigPb.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortForwardConfigPb>, I>>(object: I): PortForwardConfigPb {
    const message = createBasePortForwardConfigPb();
    message.bind_addr = (object.bind_addr !== undefined && object.bind_addr !== null)
      ? SocketAddr.fromPartial(object.bind_addr)
      : undefined;
    message.dst_addr = (object.dst_addr !== undefined && object.dst_addr !== null)
      ? SocketAddr.fromPartial(object.dst_addr)
      : undefined;
    message.socket_type = object.socket_type ?? 0;
    return message;
  },
};

function createBaseProxyDstInfo(): ProxyDstInfo {
  return { dst_addr: undefined };
}

export const ProxyDstInfo: MessageFns<ProxyDstInfo> = {
  fromJSON(object: any): ProxyDstInfo {
    return {
      dst_addr: isSet(object.dstAddr)
        ? SocketAddr.fromJSON(object.dstAddr)
        : isSet(object.dst_addr)
        ? SocketAddr.fromJSON(object.dst_addr)
        : undefined,
    };
  },

  toJSON(message: ProxyDstInfo): unknown {
    const obj: any = {};
    if (message.dst_addr !== undefined) {
      obj.dstAddr = SocketAddr.toJSON(message.dst_addr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxyDstInfo>, I>>(base?: I): ProxyDstInfo {
    return ProxyDstInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxyDstInfo>, I>>(object: I): ProxyDstInfo {
    const message = createBaseProxyDstInfo();
    message.dst_addr = (object.dst_addr !== undefined && object.dst_addr !== null)
      ? SocketAddr.fromPartial(object.dst_addr)
      : undefined;
    return message;
  },
};

function createBaseLimiterConfig(): LimiterConfig {
  return { burst_rate: undefined, bps: undefined, fill_duration_ms: undefined };
}

export const LimiterConfig: MessageFns<LimiterConfig> = {
  fromJSON(object: any): LimiterConfig {
    return {
      burst_rate: isSet(object.burstRate)
        ? globalThis.Number(object.burstRate)
        : isSet(object.burst_rate)
        ? globalThis.Number(object.burst_rate)
        : undefined,
      bps: isSet(object.bps) ? globalThis.Number(object.bps) : undefined,
      fill_duration_ms: isSet(object.fillDurationMs)
        ? globalThis.Number(object.fillDurationMs)
        : isSet(object.fill_duration_ms)
        ? globalThis.Number(object.fill_duration_ms)
        : undefined,
    };
  },

  toJSON(message: LimiterConfig): unknown {
    const obj: any = {};
    if (message.burst_rate !== undefined) {
      obj.burstRate = Math.round(message.burst_rate);
    }
    if (message.bps !== undefined) {
      obj.bps = Math.round(message.bps);
    }
    if (message.fill_duration_ms !== undefined) {
      obj.fillDurationMs = Math.round(message.fill_duration_ms);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimiterConfig>, I>>(base?: I): LimiterConfig {
    return LimiterConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimiterConfig>, I>>(object: I): LimiterConfig {
    const message = createBaseLimiterConfig();
    message.burst_rate = object.burst_rate ?? undefined;
    message.bps = object.bps ?? undefined;
    message.fill_duration_ms = object.fill_duration_ms ?? undefined;
    return message;
  },
};

function createBaseSecureModeConfig(): SecureModeConfig {
  return { enabled: false, local_private_key: undefined, local_public_key: undefined };
}

export const SecureModeConfig: MessageFns<SecureModeConfig> = {
  fromJSON(object: any): SecureModeConfig {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      local_private_key: isSet(object.localPrivateKey)
        ? globalThis.String(object.localPrivateKey)
        : isSet(object.local_private_key)
        ? globalThis.String(object.local_private_key)
        : undefined,
      local_public_key: isSet(object.localPublicKey)
        ? globalThis.String(object.localPublicKey)
        : isSet(object.local_public_key)
        ? globalThis.String(object.local_public_key)
        : undefined,
    };
  },

  toJSON(message: SecureModeConfig): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.local_private_key !== undefined) {
      obj.localPrivateKey = message.local_private_key;
    }
    if (message.local_public_key !== undefined) {
      obj.localPublicKey = message.local_public_key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SecureModeConfig>, I>>(base?: I): SecureModeConfig {
    return SecureModeConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SecureModeConfig>, I>>(object: I): SecureModeConfig {
    const message = createBaseSecureModeConfig();
    message.enabled = object.enabled ?? false;
    message.local_private_key = object.local_private_key ?? undefined;
    message.local_public_key = object.local_public_key ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
