// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: common.proto

/* eslint-disable */
import { Error } from "./error";

export const protobufPackage = "common";

export enum CompressionAlgoPb {
  Invalid = 0,
  None = 1,
  Zstd = 2,
  UNRECOGNIZED = -1,
}

export function compressionAlgoPbFromJSON(object: any): CompressionAlgoPb {
  switch (object) {
    case 0:
    case "Invalid":
      return CompressionAlgoPb.Invalid;
    case 1:
    case "None":
      return CompressionAlgoPb.None;
    case 2:
    case "Zstd":
      return CompressionAlgoPb.Zstd;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CompressionAlgoPb.UNRECOGNIZED;
  }
}

export function compressionAlgoPbToJSON(object: CompressionAlgoPb): string {
  switch (object) {
    case CompressionAlgoPb.Invalid:
      return "Invalid";
    case CompressionAlgoPb.None:
      return "None";
    case CompressionAlgoPb.Zstd:
      return "Zstd";
    case CompressionAlgoPb.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum NatType {
  /** Unknown - has NAT; but own a single public IP, port is not changed */
  Unknown = 0,
  OpenInternet = 1,
  NoPAT = 2,
  FullCone = 3,
  Restricted = 4,
  PortRestricted = 5,
  Symmetric = 6,
  SymUdpFirewall = 7,
  SymmetricEasyInc = 8,
  SymmetricEasyDec = 9,
  UNRECOGNIZED = -1,
}

export function natTypeFromJSON(object: any): NatType {
  switch (object) {
    case 0:
    case "Unknown":
      return NatType.Unknown;
    case 1:
    case "OpenInternet":
      return NatType.OpenInternet;
    case 2:
    case "NoPAT":
      return NatType.NoPAT;
    case 3:
    case "FullCone":
      return NatType.FullCone;
    case 4:
    case "Restricted":
      return NatType.Restricted;
    case 5:
    case "PortRestricted":
      return NatType.PortRestricted;
    case 6:
    case "Symmetric":
      return NatType.Symmetric;
    case 7:
    case "SymUdpFirewall":
      return NatType.SymUdpFirewall;
    case 8:
    case "SymmetricEasyInc":
      return NatType.SymmetricEasyInc;
    case 9:
    case "SymmetricEasyDec":
      return NatType.SymmetricEasyDec;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NatType.UNRECOGNIZED;
  }
}

export function natTypeToJSON(object: NatType): string {
  switch (object) {
    case NatType.Unknown:
      return "Unknown";
    case NatType.OpenInternet:
      return "OpenInternet";
    case NatType.NoPAT:
      return "NoPAT";
    case NatType.FullCone:
      return "FullCone";
    case NatType.Restricted:
      return "Restricted";
    case NatType.PortRestricted:
      return "PortRestricted";
    case NatType.Symmetric:
      return "Symmetric";
    case NatType.SymUdpFirewall:
      return "SymUdpFirewall";
    case NatType.SymmetricEasyInc:
      return "SymmetricEasyInc";
    case NatType.SymmetricEasyDec:
      return "SymmetricEasyDec";
    case NatType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SocketType {
  TCP = 0,
  UDP = 1,
  UNRECOGNIZED = -1,
}

export function socketTypeFromJSON(object: any): SocketType {
  switch (object) {
    case 0:
    case "TCP":
      return SocketType.TCP;
    case 1:
    case "UDP":
      return SocketType.UDP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SocketType.UNRECOGNIZED;
  }
}

export function socketTypeToJSON(object: SocketType): string {
  switch (object) {
    case SocketType.TCP:
      return "TCP";
    case SocketType.UDP:
      return "UDP";
    case SocketType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FlagsInConfig {
  defaultProtocol: string;
  devName: string;
  enableEncryption: boolean;
  enableIpv6: boolean;
  mtu: number;
  latencyFirst: boolean;
  enableExitNode: boolean;
  noTun: boolean;
  useSmoltcp: boolean;
  relayNetworkWhitelist: string;
  disableP2p: boolean;
  relayAllPeerRpc: boolean;
  disableUdpHolePunching: boolean;
  /**
   * string ipv6_listener = 14; [deprecated = true]; use -l udp://[::]:12345
   * instead
   */
  multiThread: boolean;
  dataCompressAlgo: CompressionAlgoPb;
  bindDevice: boolean;
  /** should we convert all tcp streams into kcp streams */
  enableKcpProxy: boolean;
  /** does this peer allow kcp input */
  disableKcpInput: boolean;
  /** disable relay local network kcp packets */
  disableRelayKcp: boolean;
  proxyForwardBySystem: boolean;
  /** enable magic dns or not */
  acceptDns: boolean;
  /** enable private mode */
  privateMode: boolean;
  /** should we convert all tcp streams into quic streams */
  enableQuicProxy: boolean;
  /** does this peer allow quic input */
  disableQuicInput: boolean;
  /** quic listen port */
  quicListenPort: number;
  /** a global relay limit, only work for foreign network */
  foreignRelayBpsLimit: number;
  multiThreadCount: number;
  /** enable relay foreign network kcp packets */
  enableRelayForeignNetworkKcp: boolean;
  /** encryption algorithm to use, empty string means default (aes-gcm) */
  encryptionAlgorithm: string;
  /** disable symmetric nat hole punching, treat symmetric as cone when enabled */
  disableSymHolePunching: boolean;
  /** tld dns zone for magic dns */
  tldDnsZone: string;
}

export interface RpcDescriptor {
  /** allow same service registered multiple times in different domain */
  domainName: string;
  protoName: string;
  serviceName: string;
  methodIndex: number;
}

export interface RpcRequest {
  /** @deprecated */
  descriptor: RpcDescriptor | undefined;
  request: Uint8Array;
  timeoutMs: number;
}

export interface RpcResponse {
  response: Uint8Array;
  error: Error | undefined;
  runtimeUs: number;
}

export interface RpcCompressionInfo {
  /** use this to compress the content */
  algo: CompressionAlgoPb;
  /**
   * tell the peer which compression algo is used to compress the next
   * response/request
   */
  acceptedAlgo: CompressionAlgoPb;
}

export interface RpcPacket {
  fromPeer: number;
  toPeer: number;
  transactionId: number;
  descriptor: RpcDescriptor | undefined;
  body: Uint8Array;
  isRequest: boolean;
  totalPieces: number;
  pieceIdx: number;
  traceId: number;
  compressionInfo: RpcCompressionInfo | undefined;
}

export interface Void {
}

export interface UUID {
  part1: number;
  part2: number;
  part3: number;
  part4: number;
}

export interface Ipv4Addr {
  addr: number;
}

export interface Ipv6Addr {
  part1: number;
  part2: number;
  part3: number;
  part4: number;
}

export interface IpAddr {
  ipv4?: Ipv4Addr | undefined;
  ipv6?: Ipv6Addr | undefined;
}

export interface Ipv4Inet {
  address: Ipv4Addr | undefined;
  networkLength: number;
}

export interface Ipv6Inet {
  address: Ipv6Addr | undefined;
  networkLength: number;
}

export interface IpInet {
  ipv4?: Ipv4Inet | undefined;
  ipv6?: Ipv6Inet | undefined;
}

export interface Url {
  url: string;
}

export interface SocketAddr {
  ipv4?: Ipv4Addr | undefined;
  ipv6?: Ipv6Addr | undefined;
  port: number;
}

export interface TunnelInfo {
  tunnelType: string;
  localAddr: Url | undefined;
  remoteAddr: Url | undefined;
}

export interface StunInfo {
  udpNatType: NatType;
  tcpNatType: NatType;
  lastUpdateTime: number;
  publicIp: string[];
  minPort: number;
  maxPort: number;
}

export interface PeerFeatureFlag {
  isPublicServer: boolean;
  avoidRelayData: boolean;
  kcpInput: boolean;
  noRelayKcp: boolean;
  supportConnListSync: boolean;
}

export interface PortForwardConfigPb {
  bindAddr: SocketAddr | undefined;
  dstAddr: SocketAddr | undefined;
  socketType: SocketType;
}

export interface ProxyDstInfo {
  dstAddr: SocketAddr | undefined;
}

export interface LimiterConfig {
  /** default 1 means no burst (capacity is same with bps) */
  burstRate?:
    | number
    | undefined;
  /** default 0 means no limit (unit is B/s) */
  bps?:
    | number
    | undefined;
  /** default 10ms, the period to fill the bucket */
  fillDurationMs?: number | undefined;
}

function createBaseFlagsInConfig(): FlagsInConfig {
  return {
    defaultProtocol: "",
    devName: "",
    enableEncryption: false,
    enableIpv6: false,
    mtu: 0,
    latencyFirst: false,
    enableExitNode: false,
    noTun: false,
    useSmoltcp: false,
    relayNetworkWhitelist: "",
    disableP2p: false,
    relayAllPeerRpc: false,
    disableUdpHolePunching: false,
    multiThread: false,
    dataCompressAlgo: 0,
    bindDevice: false,
    enableKcpProxy: false,
    disableKcpInput: false,
    disableRelayKcp: false,
    proxyForwardBySystem: false,
    acceptDns: false,
    privateMode: false,
    enableQuicProxy: false,
    disableQuicInput: false,
    quicListenPort: 0,
    foreignRelayBpsLimit: 0,
    multiThreadCount: 0,
    enableRelayForeignNetworkKcp: false,
    encryptionAlgorithm: "",
    disableSymHolePunching: false,
    tldDnsZone: "",
  };
}

export const FlagsInConfig: MessageFns<FlagsInConfig> = {
  fromJSON(object: any): FlagsInConfig {
    return {
      defaultProtocol: isSet(object.defaultProtocol) ? globalThis.String(object.defaultProtocol) : "",
      devName: isSet(object.devName) ? globalThis.String(object.devName) : "",
      enableEncryption: isSet(object.enableEncryption) ? globalThis.Boolean(object.enableEncryption) : false,
      enableIpv6: isSet(object.enableIpv6) ? globalThis.Boolean(object.enableIpv6) : false,
      mtu: isSet(object.mtu) ? globalThis.Number(object.mtu) : 0,
      latencyFirst: isSet(object.latencyFirst) ? globalThis.Boolean(object.latencyFirst) : false,
      enableExitNode: isSet(object.enableExitNode) ? globalThis.Boolean(object.enableExitNode) : false,
      noTun: isSet(object.noTun) ? globalThis.Boolean(object.noTun) : false,
      useSmoltcp: isSet(object.useSmoltcp) ? globalThis.Boolean(object.useSmoltcp) : false,
      relayNetworkWhitelist: isSet(object.relayNetworkWhitelist) ? globalThis.String(object.relayNetworkWhitelist) : "",
      disableP2p: isSet(object.disableP2p) ? globalThis.Boolean(object.disableP2p) : false,
      relayAllPeerRpc: isSet(object.relayAllPeerRpc) ? globalThis.Boolean(object.relayAllPeerRpc) : false,
      disableUdpHolePunching: isSet(object.disableUdpHolePunching)
        ? globalThis.Boolean(object.disableUdpHolePunching)
        : false,
      multiThread: isSet(object.multiThread) ? globalThis.Boolean(object.multiThread) : false,
      dataCompressAlgo: isSet(object.dataCompressAlgo) ? compressionAlgoPbFromJSON(object.dataCompressAlgo) : 0,
      bindDevice: isSet(object.bindDevice) ? globalThis.Boolean(object.bindDevice) : false,
      enableKcpProxy: isSet(object.enableKcpProxy) ? globalThis.Boolean(object.enableKcpProxy) : false,
      disableKcpInput: isSet(object.disableKcpInput) ? globalThis.Boolean(object.disableKcpInput) : false,
      disableRelayKcp: isSet(object.disableRelayKcp) ? globalThis.Boolean(object.disableRelayKcp) : false,
      proxyForwardBySystem: isSet(object.proxyForwardBySystem)
        ? globalThis.Boolean(object.proxyForwardBySystem)
        : false,
      acceptDns: isSet(object.acceptDns) ? globalThis.Boolean(object.acceptDns) : false,
      privateMode: isSet(object.privateMode) ? globalThis.Boolean(object.privateMode) : false,
      enableQuicProxy: isSet(object.enableQuicProxy) ? globalThis.Boolean(object.enableQuicProxy) : false,
      disableQuicInput: isSet(object.disableQuicInput) ? globalThis.Boolean(object.disableQuicInput) : false,
      quicListenPort: isSet(object.quicListenPort) ? globalThis.Number(object.quicListenPort) : 0,
      foreignRelayBpsLimit: isSet(object.foreignRelayBpsLimit) ? globalThis.Number(object.foreignRelayBpsLimit) : 0,
      multiThreadCount: isSet(object.multiThreadCount) ? globalThis.Number(object.multiThreadCount) : 0,
      enableRelayForeignNetworkKcp: isSet(object.enableRelayForeignNetworkKcp)
        ? globalThis.Boolean(object.enableRelayForeignNetworkKcp)
        : false,
      encryptionAlgorithm: isSet(object.encryptionAlgorithm) ? globalThis.String(object.encryptionAlgorithm) : "",
      disableSymHolePunching: isSet(object.disableSymHolePunching)
        ? globalThis.Boolean(object.disableSymHolePunching)
        : false,
      tldDnsZone: isSet(object.tldDnsZone) ? globalThis.String(object.tldDnsZone) : "",
    };
  },

  toJSON(message: FlagsInConfig): unknown {
    const obj: any = {};
    if (message.defaultProtocol !== "") {
      obj.defaultProtocol = message.defaultProtocol;
    }
    if (message.devName !== "") {
      obj.devName = message.devName;
    }
    if (message.enableEncryption !== false) {
      obj.enableEncryption = message.enableEncryption;
    }
    if (message.enableIpv6 !== false) {
      obj.enableIpv6 = message.enableIpv6;
    }
    if (message.mtu !== 0) {
      obj.mtu = Math.round(message.mtu);
    }
    if (message.latencyFirst !== false) {
      obj.latencyFirst = message.latencyFirst;
    }
    if (message.enableExitNode !== false) {
      obj.enableExitNode = message.enableExitNode;
    }
    if (message.noTun !== false) {
      obj.noTun = message.noTun;
    }
    if (message.useSmoltcp !== false) {
      obj.useSmoltcp = message.useSmoltcp;
    }
    if (message.relayNetworkWhitelist !== "") {
      obj.relayNetworkWhitelist = message.relayNetworkWhitelist;
    }
    if (message.disableP2p !== false) {
      obj.disableP2p = message.disableP2p;
    }
    if (message.relayAllPeerRpc !== false) {
      obj.relayAllPeerRpc = message.relayAllPeerRpc;
    }
    if (message.disableUdpHolePunching !== false) {
      obj.disableUdpHolePunching = message.disableUdpHolePunching;
    }
    if (message.multiThread !== false) {
      obj.multiThread = message.multiThread;
    }
    if (message.dataCompressAlgo !== 0) {
      obj.dataCompressAlgo = compressionAlgoPbToJSON(message.dataCompressAlgo);
    }
    if (message.bindDevice !== false) {
      obj.bindDevice = message.bindDevice;
    }
    if (message.enableKcpProxy !== false) {
      obj.enableKcpProxy = message.enableKcpProxy;
    }
    if (message.disableKcpInput !== false) {
      obj.disableKcpInput = message.disableKcpInput;
    }
    if (message.disableRelayKcp !== false) {
      obj.disableRelayKcp = message.disableRelayKcp;
    }
    if (message.proxyForwardBySystem !== false) {
      obj.proxyForwardBySystem = message.proxyForwardBySystem;
    }
    if (message.acceptDns !== false) {
      obj.acceptDns = message.acceptDns;
    }
    if (message.privateMode !== false) {
      obj.privateMode = message.privateMode;
    }
    if (message.enableQuicProxy !== false) {
      obj.enableQuicProxy = message.enableQuicProxy;
    }
    if (message.disableQuicInput !== false) {
      obj.disableQuicInput = message.disableQuicInput;
    }
    if (message.quicListenPort !== 0) {
      obj.quicListenPort = Math.round(message.quicListenPort);
    }
    if (message.foreignRelayBpsLimit !== 0) {
      obj.foreignRelayBpsLimit = Math.round(message.foreignRelayBpsLimit);
    }
    if (message.multiThreadCount !== 0) {
      obj.multiThreadCount = Math.round(message.multiThreadCount);
    }
    if (message.enableRelayForeignNetworkKcp !== false) {
      obj.enableRelayForeignNetworkKcp = message.enableRelayForeignNetworkKcp;
    }
    if (message.encryptionAlgorithm !== "") {
      obj.encryptionAlgorithm = message.encryptionAlgorithm;
    }
    if (message.disableSymHolePunching !== false) {
      obj.disableSymHolePunching = message.disableSymHolePunching;
    }
    if (message.tldDnsZone !== "") {
      obj.tldDnsZone = message.tldDnsZone;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlagsInConfig>, I>>(base?: I): FlagsInConfig {
    return FlagsInConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlagsInConfig>, I>>(object: I): FlagsInConfig {
    const message = createBaseFlagsInConfig();
    message.defaultProtocol = object.defaultProtocol ?? "";
    message.devName = object.devName ?? "";
    message.enableEncryption = object.enableEncryption ?? false;
    message.enableIpv6 = object.enableIpv6 ?? false;
    message.mtu = object.mtu ?? 0;
    message.latencyFirst = object.latencyFirst ?? false;
    message.enableExitNode = object.enableExitNode ?? false;
    message.noTun = object.noTun ?? false;
    message.useSmoltcp = object.useSmoltcp ?? false;
    message.relayNetworkWhitelist = object.relayNetworkWhitelist ?? "";
    message.disableP2p = object.disableP2p ?? false;
    message.relayAllPeerRpc = object.relayAllPeerRpc ?? false;
    message.disableUdpHolePunching = object.disableUdpHolePunching ?? false;
    message.multiThread = object.multiThread ?? false;
    message.dataCompressAlgo = object.dataCompressAlgo ?? 0;
    message.bindDevice = object.bindDevice ?? false;
    message.enableKcpProxy = object.enableKcpProxy ?? false;
    message.disableKcpInput = object.disableKcpInput ?? false;
    message.disableRelayKcp = object.disableRelayKcp ?? false;
    message.proxyForwardBySystem = object.proxyForwardBySystem ?? false;
    message.acceptDns = object.acceptDns ?? false;
    message.privateMode = object.privateMode ?? false;
    message.enableQuicProxy = object.enableQuicProxy ?? false;
    message.disableQuicInput = object.disableQuicInput ?? false;
    message.quicListenPort = object.quicListenPort ?? 0;
    message.foreignRelayBpsLimit = object.foreignRelayBpsLimit ?? 0;
    message.multiThreadCount = object.multiThreadCount ?? 0;
    message.enableRelayForeignNetworkKcp = object.enableRelayForeignNetworkKcp ?? false;
    message.encryptionAlgorithm = object.encryptionAlgorithm ?? "";
    message.disableSymHolePunching = object.disableSymHolePunching ?? false;
    message.tldDnsZone = object.tldDnsZone ?? "";
    return message;
  },
};

function createBaseRpcDescriptor(): RpcDescriptor {
  return { domainName: "", protoName: "", serviceName: "", methodIndex: 0 };
}

export const RpcDescriptor: MessageFns<RpcDescriptor> = {
  fromJSON(object: any): RpcDescriptor {
    return {
      domainName: isSet(object.domainName) ? globalThis.String(object.domainName) : "",
      protoName: isSet(object.protoName) ? globalThis.String(object.protoName) : "",
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      methodIndex: isSet(object.methodIndex) ? globalThis.Number(object.methodIndex) : 0,
    };
  },

  toJSON(message: RpcDescriptor): unknown {
    const obj: any = {};
    if (message.domainName !== "") {
      obj.domainName = message.domainName;
    }
    if (message.protoName !== "") {
      obj.protoName = message.protoName;
    }
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.methodIndex !== 0) {
      obj.methodIndex = Math.round(message.methodIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcDescriptor>, I>>(base?: I): RpcDescriptor {
    return RpcDescriptor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcDescriptor>, I>>(object: I): RpcDescriptor {
    const message = createBaseRpcDescriptor();
    message.domainName = object.domainName ?? "";
    message.protoName = object.protoName ?? "";
    message.serviceName = object.serviceName ?? "";
    message.methodIndex = object.methodIndex ?? 0;
    return message;
  },
};

function createBaseRpcRequest(): RpcRequest {
  return { descriptor: undefined, request: new Uint8Array(0), timeoutMs: 0 };
}

export const RpcRequest: MessageFns<RpcRequest> = {
  fromJSON(object: any): RpcRequest {
    return {
      descriptor: isSet(object.descriptor) ? RpcDescriptor.fromJSON(object.descriptor) : undefined,
      request: isSet(object.request) ? bytesFromBase64(object.request) : new Uint8Array(0),
      timeoutMs: isSet(object.timeoutMs) ? globalThis.Number(object.timeoutMs) : 0,
    };
  },

  toJSON(message: RpcRequest): unknown {
    const obj: any = {};
    if (message.descriptor !== undefined) {
      obj.descriptor = RpcDescriptor.toJSON(message.descriptor);
    }
    if (message.request.length !== 0) {
      obj.request = base64FromBytes(message.request);
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcRequest>, I>>(base?: I): RpcRequest {
    return RpcRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcRequest>, I>>(object: I): RpcRequest {
    const message = createBaseRpcRequest();
    message.descriptor = (object.descriptor !== undefined && object.descriptor !== null)
      ? RpcDescriptor.fromPartial(object.descriptor)
      : undefined;
    message.request = object.request ?? new Uint8Array(0);
    message.timeoutMs = object.timeoutMs ?? 0;
    return message;
  },
};

function createBaseRpcResponse(): RpcResponse {
  return { response: new Uint8Array(0), error: undefined, runtimeUs: 0 };
}

export const RpcResponse: MessageFns<RpcResponse> = {
  fromJSON(object: any): RpcResponse {
    return {
      response: isSet(object.response) ? bytesFromBase64(object.response) : new Uint8Array(0),
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      runtimeUs: isSet(object.runtimeUs) ? globalThis.Number(object.runtimeUs) : 0,
    };
  },

  toJSON(message: RpcResponse): unknown {
    const obj: any = {};
    if (message.response.length !== 0) {
      obj.response = base64FromBytes(message.response);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.runtimeUs !== 0) {
      obj.runtimeUs = Math.round(message.runtimeUs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcResponse>, I>>(base?: I): RpcResponse {
    return RpcResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcResponse>, I>>(object: I): RpcResponse {
    const message = createBaseRpcResponse();
    message.response = object.response ?? new Uint8Array(0);
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.runtimeUs = object.runtimeUs ?? 0;
    return message;
  },
};

function createBaseRpcCompressionInfo(): RpcCompressionInfo {
  return { algo: 0, acceptedAlgo: 0 };
}

export const RpcCompressionInfo: MessageFns<RpcCompressionInfo> = {
  fromJSON(object: any): RpcCompressionInfo {
    return {
      algo: isSet(object.algo) ? compressionAlgoPbFromJSON(object.algo) : 0,
      acceptedAlgo: isSet(object.acceptedAlgo) ? compressionAlgoPbFromJSON(object.acceptedAlgo) : 0,
    };
  },

  toJSON(message: RpcCompressionInfo): unknown {
    const obj: any = {};
    if (message.algo !== 0) {
      obj.algo = compressionAlgoPbToJSON(message.algo);
    }
    if (message.acceptedAlgo !== 0) {
      obj.acceptedAlgo = compressionAlgoPbToJSON(message.acceptedAlgo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcCompressionInfo>, I>>(base?: I): RpcCompressionInfo {
    return RpcCompressionInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcCompressionInfo>, I>>(object: I): RpcCompressionInfo {
    const message = createBaseRpcCompressionInfo();
    message.algo = object.algo ?? 0;
    message.acceptedAlgo = object.acceptedAlgo ?? 0;
    return message;
  },
};

function createBaseRpcPacket(): RpcPacket {
  return {
    fromPeer: 0,
    toPeer: 0,
    transactionId: 0,
    descriptor: undefined,
    body: new Uint8Array(0),
    isRequest: false,
    totalPieces: 0,
    pieceIdx: 0,
    traceId: 0,
    compressionInfo: undefined,
  };
}

export const RpcPacket: MessageFns<RpcPacket> = {
  fromJSON(object: any): RpcPacket {
    return {
      fromPeer: isSet(object.fromPeer) ? globalThis.Number(object.fromPeer) : 0,
      toPeer: isSet(object.toPeer) ? globalThis.Number(object.toPeer) : 0,
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      descriptor: isSet(object.descriptor) ? RpcDescriptor.fromJSON(object.descriptor) : undefined,
      body: isSet(object.body) ? bytesFromBase64(object.body) : new Uint8Array(0),
      isRequest: isSet(object.isRequest) ? globalThis.Boolean(object.isRequest) : false,
      totalPieces: isSet(object.totalPieces) ? globalThis.Number(object.totalPieces) : 0,
      pieceIdx: isSet(object.pieceIdx) ? globalThis.Number(object.pieceIdx) : 0,
      traceId: isSet(object.traceId) ? globalThis.Number(object.traceId) : 0,
      compressionInfo: isSet(object.compressionInfo) ? RpcCompressionInfo.fromJSON(object.compressionInfo) : undefined,
    };
  },

  toJSON(message: RpcPacket): unknown {
    const obj: any = {};
    if (message.fromPeer !== 0) {
      obj.fromPeer = Math.round(message.fromPeer);
    }
    if (message.toPeer !== 0) {
      obj.toPeer = Math.round(message.toPeer);
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.descriptor !== undefined) {
      obj.descriptor = RpcDescriptor.toJSON(message.descriptor);
    }
    if (message.body.length !== 0) {
      obj.body = base64FromBytes(message.body);
    }
    if (message.isRequest !== false) {
      obj.isRequest = message.isRequest;
    }
    if (message.totalPieces !== 0) {
      obj.totalPieces = Math.round(message.totalPieces);
    }
    if (message.pieceIdx !== 0) {
      obj.pieceIdx = Math.round(message.pieceIdx);
    }
    if (message.traceId !== 0) {
      obj.traceId = Math.round(message.traceId);
    }
    if (message.compressionInfo !== undefined) {
      obj.compressionInfo = RpcCompressionInfo.toJSON(message.compressionInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RpcPacket>, I>>(base?: I): RpcPacket {
    return RpcPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RpcPacket>, I>>(object: I): RpcPacket {
    const message = createBaseRpcPacket();
    message.fromPeer = object.fromPeer ?? 0;
    message.toPeer = object.toPeer ?? 0;
    message.transactionId = object.transactionId ?? 0;
    message.descriptor = (object.descriptor !== undefined && object.descriptor !== null)
      ? RpcDescriptor.fromPartial(object.descriptor)
      : undefined;
    message.body = object.body ?? new Uint8Array(0);
    message.isRequest = object.isRequest ?? false;
    message.totalPieces = object.totalPieces ?? 0;
    message.pieceIdx = object.pieceIdx ?? 0;
    message.traceId = object.traceId ?? 0;
    message.compressionInfo = (object.compressionInfo !== undefined && object.compressionInfo !== null)
      ? RpcCompressionInfo.fromPartial(object.compressionInfo)
      : undefined;
    return message;
  },
};

function createBaseVoid(): Void {
  return {};
}

export const Void: MessageFns<Void> = {
  fromJSON(_: any): Void {
    return {};
  },

  toJSON(_: Void): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Void>, I>>(base?: I): Void {
    return Void.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Void>, I>>(_: I): Void {
    const message = createBaseVoid();
    return message;
  },
};

function createBaseUUID(): UUID {
  return { part1: 0, part2: 0, part3: 0, part4: 0 };
}

export const UUID: MessageFns<UUID> = {
  fromJSON(object: any): UUID {
    return {
      part1: isSet(object.part1) ? globalThis.Number(object.part1) : 0,
      part2: isSet(object.part2) ? globalThis.Number(object.part2) : 0,
      part3: isSet(object.part3) ? globalThis.Number(object.part3) : 0,
      part4: isSet(object.part4) ? globalThis.Number(object.part4) : 0,
    };
  },

  toJSON(message: UUID): unknown {
    const obj: any = {};
    if (message.part1 !== 0) {
      obj.part1 = Math.round(message.part1);
    }
    if (message.part2 !== 0) {
      obj.part2 = Math.round(message.part2);
    }
    if (message.part3 !== 0) {
      obj.part3 = Math.round(message.part3);
    }
    if (message.part4 !== 0) {
      obj.part4 = Math.round(message.part4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UUID>, I>>(base?: I): UUID {
    return UUID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UUID>, I>>(object: I): UUID {
    const message = createBaseUUID();
    message.part1 = object.part1 ?? 0;
    message.part2 = object.part2 ?? 0;
    message.part3 = object.part3 ?? 0;
    message.part4 = object.part4 ?? 0;
    return message;
  },
};

function createBaseIpv4Addr(): Ipv4Addr {
  return { addr: 0 };
}

export const Ipv4Addr: MessageFns<Ipv4Addr> = {
  fromJSON(object: any): Ipv4Addr {
    return { addr: isSet(object.addr) ? globalThis.Number(object.addr) : 0 };
  },

  toJSON(message: Ipv4Addr): unknown {
    const obj: any = {};
    if (message.addr !== 0) {
      obj.addr = Math.round(message.addr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv4Addr>, I>>(base?: I): Ipv4Addr {
    return Ipv4Addr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv4Addr>, I>>(object: I): Ipv4Addr {
    const message = createBaseIpv4Addr();
    message.addr = object.addr ?? 0;
    return message;
  },
};

function createBaseIpv6Addr(): Ipv6Addr {
  return { part1: 0, part2: 0, part3: 0, part4: 0 };
}

export const Ipv6Addr: MessageFns<Ipv6Addr> = {
  fromJSON(object: any): Ipv6Addr {
    return {
      part1: isSet(object.part1) ? globalThis.Number(object.part1) : 0,
      part2: isSet(object.part2) ? globalThis.Number(object.part2) : 0,
      part3: isSet(object.part3) ? globalThis.Number(object.part3) : 0,
      part4: isSet(object.part4) ? globalThis.Number(object.part4) : 0,
    };
  },

  toJSON(message: Ipv6Addr): unknown {
    const obj: any = {};
    if (message.part1 !== 0) {
      obj.part1 = Math.round(message.part1);
    }
    if (message.part2 !== 0) {
      obj.part2 = Math.round(message.part2);
    }
    if (message.part3 !== 0) {
      obj.part3 = Math.round(message.part3);
    }
    if (message.part4 !== 0) {
      obj.part4 = Math.round(message.part4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv6Addr>, I>>(base?: I): Ipv6Addr {
    return Ipv6Addr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv6Addr>, I>>(object: I): Ipv6Addr {
    const message = createBaseIpv6Addr();
    message.part1 = object.part1 ?? 0;
    message.part2 = object.part2 ?? 0;
    message.part3 = object.part3 ?? 0;
    message.part4 = object.part4 ?? 0;
    return message;
  },
};

function createBaseIpAddr(): IpAddr {
  return { ipv4: undefined, ipv6: undefined };
}

export const IpAddr: MessageFns<IpAddr> = {
  fromJSON(object: any): IpAddr {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Addr.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Addr.fromJSON(object.ipv6) : undefined,
    };
  },

  toJSON(message: IpAddr): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Addr.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Addr.toJSON(message.ipv6);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IpAddr>, I>>(base?: I): IpAddr {
    return IpAddr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IpAddr>, I>>(object: I): IpAddr {
    const message = createBaseIpAddr();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Addr.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Addr.fromPartial(object.ipv6) : undefined;
    return message;
  },
};

function createBaseIpv4Inet(): Ipv4Inet {
  return { address: undefined, networkLength: 0 };
}

export const Ipv4Inet: MessageFns<Ipv4Inet> = {
  fromJSON(object: any): Ipv4Inet {
    return {
      address: isSet(object.address) ? Ipv4Addr.fromJSON(object.address) : undefined,
      networkLength: isSet(object.networkLength) ? globalThis.Number(object.networkLength) : 0,
    };
  },

  toJSON(message: Ipv4Inet): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = Ipv4Addr.toJSON(message.address);
    }
    if (message.networkLength !== 0) {
      obj.networkLength = Math.round(message.networkLength);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv4Inet>, I>>(base?: I): Ipv4Inet {
    return Ipv4Inet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv4Inet>, I>>(object: I): Ipv4Inet {
    const message = createBaseIpv4Inet();
    message.address = (object.address !== undefined && object.address !== null)
      ? Ipv4Addr.fromPartial(object.address)
      : undefined;
    message.networkLength = object.networkLength ?? 0;
    return message;
  },
};

function createBaseIpv6Inet(): Ipv6Inet {
  return { address: undefined, networkLength: 0 };
}

export const Ipv6Inet: MessageFns<Ipv6Inet> = {
  fromJSON(object: any): Ipv6Inet {
    return {
      address: isSet(object.address) ? Ipv6Addr.fromJSON(object.address) : undefined,
      networkLength: isSet(object.networkLength) ? globalThis.Number(object.networkLength) : 0,
    };
  },

  toJSON(message: Ipv6Inet): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = Ipv6Addr.toJSON(message.address);
    }
    if (message.networkLength !== 0) {
      obj.networkLength = Math.round(message.networkLength);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ipv6Inet>, I>>(base?: I): Ipv6Inet {
    return Ipv6Inet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ipv6Inet>, I>>(object: I): Ipv6Inet {
    const message = createBaseIpv6Inet();
    message.address = (object.address !== undefined && object.address !== null)
      ? Ipv6Addr.fromPartial(object.address)
      : undefined;
    message.networkLength = object.networkLength ?? 0;
    return message;
  },
};

function createBaseIpInet(): IpInet {
  return { ipv4: undefined, ipv6: undefined };
}

export const IpInet: MessageFns<IpInet> = {
  fromJSON(object: any): IpInet {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Inet.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Inet.fromJSON(object.ipv6) : undefined,
    };
  },

  toJSON(message: IpInet): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Inet.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Inet.toJSON(message.ipv6);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IpInet>, I>>(base?: I): IpInet {
    return IpInet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IpInet>, I>>(object: I): IpInet {
    const message = createBaseIpInet();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Inet.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Inet.fromPartial(object.ipv6) : undefined;
    return message;
  },
};

function createBaseUrl(): Url {
  return { url: "" };
}

export const Url: MessageFns<Url> = {
  fromJSON(object: any): Url {
    return { url: isSet(object.url) ? globalThis.String(object.url) : "" };
  },

  toJSON(message: Url): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Url>, I>>(base?: I): Url {
    return Url.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Url>, I>>(object: I): Url {
    const message = createBaseUrl();
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseSocketAddr(): SocketAddr {
  return { ipv4: undefined, ipv6: undefined, port: 0 };
}

export const SocketAddr: MessageFns<SocketAddr> = {
  fromJSON(object: any): SocketAddr {
    return {
      ipv4: isSet(object.ipv4) ? Ipv4Addr.fromJSON(object.ipv4) : undefined,
      ipv6: isSet(object.ipv6) ? Ipv6Addr.fromJSON(object.ipv6) : undefined,
      port: isSet(object.port) ? globalThis.Number(object.port) : 0,
    };
  },

  toJSON(message: SocketAddr): unknown {
    const obj: any = {};
    if (message.ipv4 !== undefined) {
      obj.ipv4 = Ipv4Addr.toJSON(message.ipv4);
    }
    if (message.ipv6 !== undefined) {
      obj.ipv6 = Ipv6Addr.toJSON(message.ipv6);
    }
    if (message.port !== 0) {
      obj.port = Math.round(message.port);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketAddr>, I>>(base?: I): SocketAddr {
    return SocketAddr.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketAddr>, I>>(object: I): SocketAddr {
    const message = createBaseSocketAddr();
    message.ipv4 = (object.ipv4 !== undefined && object.ipv4 !== null) ? Ipv4Addr.fromPartial(object.ipv4) : undefined;
    message.ipv6 = (object.ipv6 !== undefined && object.ipv6 !== null) ? Ipv6Addr.fromPartial(object.ipv6) : undefined;
    message.port = object.port ?? 0;
    return message;
  },
};

function createBaseTunnelInfo(): TunnelInfo {
  return { tunnelType: "", localAddr: undefined, remoteAddr: undefined };
}

export const TunnelInfo: MessageFns<TunnelInfo> = {
  fromJSON(object: any): TunnelInfo {
    return {
      tunnelType: isSet(object.tunnelType) ? globalThis.String(object.tunnelType) : "",
      localAddr: isSet(object.localAddr) ? Url.fromJSON(object.localAddr) : undefined,
      remoteAddr: isSet(object.remoteAddr) ? Url.fromJSON(object.remoteAddr) : undefined,
    };
  },

  toJSON(message: TunnelInfo): unknown {
    const obj: any = {};
    if (message.tunnelType !== "") {
      obj.tunnelType = message.tunnelType;
    }
    if (message.localAddr !== undefined) {
      obj.localAddr = Url.toJSON(message.localAddr);
    }
    if (message.remoteAddr !== undefined) {
      obj.remoteAddr = Url.toJSON(message.remoteAddr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TunnelInfo>, I>>(base?: I): TunnelInfo {
    return TunnelInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TunnelInfo>, I>>(object: I): TunnelInfo {
    const message = createBaseTunnelInfo();
    message.tunnelType = object.tunnelType ?? "";
    message.localAddr = (object.localAddr !== undefined && object.localAddr !== null)
      ? Url.fromPartial(object.localAddr)
      : undefined;
    message.remoteAddr = (object.remoteAddr !== undefined && object.remoteAddr !== null)
      ? Url.fromPartial(object.remoteAddr)
      : undefined;
    return message;
  },
};

function createBaseStunInfo(): StunInfo {
  return { udpNatType: 0, tcpNatType: 0, lastUpdateTime: 0, publicIp: [], minPort: 0, maxPort: 0 };
}

export const StunInfo: MessageFns<StunInfo> = {
  fromJSON(object: any): StunInfo {
    return {
      udpNatType: isSet(object.udpNatType) ? natTypeFromJSON(object.udpNatType) : 0,
      tcpNatType: isSet(object.tcpNatType) ? natTypeFromJSON(object.tcpNatType) : 0,
      lastUpdateTime: isSet(object.lastUpdateTime) ? globalThis.Number(object.lastUpdateTime) : 0,
      publicIp: globalThis.Array.isArray(object?.publicIp) ? object.publicIp.map((e: any) => globalThis.String(e)) : [],
      minPort: isSet(object.minPort) ? globalThis.Number(object.minPort) : 0,
      maxPort: isSet(object.maxPort) ? globalThis.Number(object.maxPort) : 0,
    };
  },

  toJSON(message: StunInfo): unknown {
    const obj: any = {};
    if (message.udpNatType !== 0) {
      obj.udpNatType = natTypeToJSON(message.udpNatType);
    }
    if (message.tcpNatType !== 0) {
      obj.tcpNatType = natTypeToJSON(message.tcpNatType);
    }
    if (message.lastUpdateTime !== 0) {
      obj.lastUpdateTime = Math.round(message.lastUpdateTime);
    }
    if (message.publicIp?.length) {
      obj.publicIp = message.publicIp;
    }
    if (message.minPort !== 0) {
      obj.minPort = Math.round(message.minPort);
    }
    if (message.maxPort !== 0) {
      obj.maxPort = Math.round(message.maxPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StunInfo>, I>>(base?: I): StunInfo {
    return StunInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StunInfo>, I>>(object: I): StunInfo {
    const message = createBaseStunInfo();
    message.udpNatType = object.udpNatType ?? 0;
    message.tcpNatType = object.tcpNatType ?? 0;
    message.lastUpdateTime = object.lastUpdateTime ?? 0;
    message.publicIp = object.publicIp?.map((e) => e) || [];
    message.minPort = object.minPort ?? 0;
    message.maxPort = object.maxPort ?? 0;
    return message;
  },
};

function createBasePeerFeatureFlag(): PeerFeatureFlag {
  return {
    isPublicServer: false,
    avoidRelayData: false,
    kcpInput: false,
    noRelayKcp: false,
    supportConnListSync: false,
  };
}

export const PeerFeatureFlag: MessageFns<PeerFeatureFlag> = {
  fromJSON(object: any): PeerFeatureFlag {
    return {
      isPublicServer: isSet(object.isPublicServer) ? globalThis.Boolean(object.isPublicServer) : false,
      avoidRelayData: isSet(object.avoidRelayData) ? globalThis.Boolean(object.avoidRelayData) : false,
      kcpInput: isSet(object.kcpInput) ? globalThis.Boolean(object.kcpInput) : false,
      noRelayKcp: isSet(object.noRelayKcp) ? globalThis.Boolean(object.noRelayKcp) : false,
      supportConnListSync: isSet(object.supportConnListSync) ? globalThis.Boolean(object.supportConnListSync) : false,
    };
  },

  toJSON(message: PeerFeatureFlag): unknown {
    const obj: any = {};
    if (message.isPublicServer !== false) {
      obj.isPublicServer = message.isPublicServer;
    }
    if (message.avoidRelayData !== false) {
      obj.avoidRelayData = message.avoidRelayData;
    }
    if (message.kcpInput !== false) {
      obj.kcpInput = message.kcpInput;
    }
    if (message.noRelayKcp !== false) {
      obj.noRelayKcp = message.noRelayKcp;
    }
    if (message.supportConnListSync !== false) {
      obj.supportConnListSync = message.supportConnListSync;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerFeatureFlag>, I>>(base?: I): PeerFeatureFlag {
    return PeerFeatureFlag.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerFeatureFlag>, I>>(object: I): PeerFeatureFlag {
    const message = createBasePeerFeatureFlag();
    message.isPublicServer = object.isPublicServer ?? false;
    message.avoidRelayData = object.avoidRelayData ?? false;
    message.kcpInput = object.kcpInput ?? false;
    message.noRelayKcp = object.noRelayKcp ?? false;
    message.supportConnListSync = object.supportConnListSync ?? false;
    return message;
  },
};

function createBasePortForwardConfigPb(): PortForwardConfigPb {
  return { bindAddr: undefined, dstAddr: undefined, socketType: 0 };
}

export const PortForwardConfigPb: MessageFns<PortForwardConfigPb> = {
  fromJSON(object: any): PortForwardConfigPb {
    return {
      bindAddr: isSet(object.bindAddr) ? SocketAddr.fromJSON(object.bindAddr) : undefined,
      dstAddr: isSet(object.dstAddr) ? SocketAddr.fromJSON(object.dstAddr) : undefined,
      socketType: isSet(object.socketType) ? socketTypeFromJSON(object.socketType) : 0,
    };
  },

  toJSON(message: PortForwardConfigPb): unknown {
    const obj: any = {};
    if (message.bindAddr !== undefined) {
      obj.bindAddr = SocketAddr.toJSON(message.bindAddr);
    }
    if (message.dstAddr !== undefined) {
      obj.dstAddr = SocketAddr.toJSON(message.dstAddr);
    }
    if (message.socketType !== 0) {
      obj.socketType = socketTypeToJSON(message.socketType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PortForwardConfigPb>, I>>(base?: I): PortForwardConfigPb {
    return PortForwardConfigPb.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortForwardConfigPb>, I>>(object: I): PortForwardConfigPb {
    const message = createBasePortForwardConfigPb();
    message.bindAddr = (object.bindAddr !== undefined && object.bindAddr !== null)
      ? SocketAddr.fromPartial(object.bindAddr)
      : undefined;
    message.dstAddr = (object.dstAddr !== undefined && object.dstAddr !== null)
      ? SocketAddr.fromPartial(object.dstAddr)
      : undefined;
    message.socketType = object.socketType ?? 0;
    return message;
  },
};

function createBaseProxyDstInfo(): ProxyDstInfo {
  return { dstAddr: undefined };
}

export const ProxyDstInfo: MessageFns<ProxyDstInfo> = {
  fromJSON(object: any): ProxyDstInfo {
    return { dstAddr: isSet(object.dstAddr) ? SocketAddr.fromJSON(object.dstAddr) : undefined };
  },

  toJSON(message: ProxyDstInfo): unknown {
    const obj: any = {};
    if (message.dstAddr !== undefined) {
      obj.dstAddr = SocketAddr.toJSON(message.dstAddr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProxyDstInfo>, I>>(base?: I): ProxyDstInfo {
    return ProxyDstInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProxyDstInfo>, I>>(object: I): ProxyDstInfo {
    const message = createBaseProxyDstInfo();
    message.dstAddr = (object.dstAddr !== undefined && object.dstAddr !== null)
      ? SocketAddr.fromPartial(object.dstAddr)
      : undefined;
    return message;
  },
};

function createBaseLimiterConfig(): LimiterConfig {
  return { burstRate: undefined, bps: undefined, fillDurationMs: undefined };
}

export const LimiterConfig: MessageFns<LimiterConfig> = {
  fromJSON(object: any): LimiterConfig {
    return {
      burstRate: isSet(object.burstRate) ? globalThis.Number(object.burstRate) : undefined,
      bps: isSet(object.bps) ? globalThis.Number(object.bps) : undefined,
      fillDurationMs: isSet(object.fillDurationMs) ? globalThis.Number(object.fillDurationMs) : undefined,
    };
  },

  toJSON(message: LimiterConfig): unknown {
    const obj: any = {};
    if (message.burstRate !== undefined) {
      obj.burstRate = Math.round(message.burstRate);
    }
    if (message.bps !== undefined) {
      obj.bps = Math.round(message.bps);
    }
    if (message.fillDurationMs !== undefined) {
      obj.fillDurationMs = Math.round(message.fillDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimiterConfig>, I>>(base?: I): LimiterConfig {
    return LimiterConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimiterConfig>, I>>(object: I): LimiterConfig {
    const message = createBaseLimiterConfig();
    message.burstRate = object.burstRate ?? undefined;
    message.bps = object.bps ?? undefined;
    message.fillDurationMs = object.fillDurationMs ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
