// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: error.proto

/* eslint-disable */

export const protobufPackage = "error";

export interface OtherError {
  errorMessage: string;
}

export interface InvalidMethodIndex {
  serviceName: string;
  methodIndex: number;
}

export interface InvalidService {
  serviceName: string;
}

export interface ProstDecodeError {
}

export interface ProstEncodeError {
}

export interface ExecuteError {
  errorMessage: string;
}

export interface MalformatRpcPacket {
  errorMessage: string;
}

export interface Timeout {
  errorMessage: string;
}

export interface Error {
  otherError?: OtherError | undefined;
  invalidMethodIndex?: InvalidMethodIndex | undefined;
  invalidService?: InvalidService | undefined;
  prostDecodeError?: ProstDecodeError | undefined;
  prostEncodeError?: ProstEncodeError | undefined;
  executeError?: ExecuteError | undefined;
  malformatRpcPacket?: MalformatRpcPacket | undefined;
  timeout?: Timeout | undefined;
}

function createBaseOtherError(): OtherError {
  return { errorMessage: "" };
}

export const OtherError: MessageFns<OtherError> = {
  fromJSON(object: any): OtherError {
    return { errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "" };
  },

  toJSON(message: OtherError): unknown {
    const obj: any = {};
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OtherError>, I>>(base?: I): OtherError {
    return OtherError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OtherError>, I>>(object: I): OtherError {
    const message = createBaseOtherError();
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseInvalidMethodIndex(): InvalidMethodIndex {
  return { serviceName: "", methodIndex: 0 };
}

export const InvalidMethodIndex: MessageFns<InvalidMethodIndex> = {
  fromJSON(object: any): InvalidMethodIndex {
    return {
      serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "",
      methodIndex: isSet(object.methodIndex) ? globalThis.Number(object.methodIndex) : 0,
    };
  },

  toJSON(message: InvalidMethodIndex): unknown {
    const obj: any = {};
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    if (message.methodIndex !== 0) {
      obj.methodIndex = Math.round(message.methodIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidMethodIndex>, I>>(base?: I): InvalidMethodIndex {
    return InvalidMethodIndex.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidMethodIndex>, I>>(object: I): InvalidMethodIndex {
    const message = createBaseInvalidMethodIndex();
    message.serviceName = object.serviceName ?? "";
    message.methodIndex = object.methodIndex ?? 0;
    return message;
  },
};

function createBaseInvalidService(): InvalidService {
  return { serviceName: "" };
}

export const InvalidService: MessageFns<InvalidService> = {
  fromJSON(object: any): InvalidService {
    return { serviceName: isSet(object.serviceName) ? globalThis.String(object.serviceName) : "" };
  },

  toJSON(message: InvalidService): unknown {
    const obj: any = {};
    if (message.serviceName !== "") {
      obj.serviceName = message.serviceName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidService>, I>>(base?: I): InvalidService {
    return InvalidService.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidService>, I>>(object: I): InvalidService {
    const message = createBaseInvalidService();
    message.serviceName = object.serviceName ?? "";
    return message;
  },
};

function createBaseProstDecodeError(): ProstDecodeError {
  return {};
}

export const ProstDecodeError: MessageFns<ProstDecodeError> = {
  fromJSON(_: any): ProstDecodeError {
    return {};
  },

  toJSON(_: ProstDecodeError): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ProstDecodeError>, I>>(base?: I): ProstDecodeError {
    return ProstDecodeError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProstDecodeError>, I>>(_: I): ProstDecodeError {
    const message = createBaseProstDecodeError();
    return message;
  },
};

function createBaseProstEncodeError(): ProstEncodeError {
  return {};
}

export const ProstEncodeError: MessageFns<ProstEncodeError> = {
  fromJSON(_: any): ProstEncodeError {
    return {};
  },

  toJSON(_: ProstEncodeError): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ProstEncodeError>, I>>(base?: I): ProstEncodeError {
    return ProstEncodeError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProstEncodeError>, I>>(_: I): ProstEncodeError {
    const message = createBaseProstEncodeError();
    return message;
  },
};

function createBaseExecuteError(): ExecuteError {
  return { errorMessage: "" };
}

export const ExecuteError: MessageFns<ExecuteError> = {
  fromJSON(object: any): ExecuteError {
    return { errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "" };
  },

  toJSON(message: ExecuteError): unknown {
    const obj: any = {};
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteError>, I>>(base?: I): ExecuteError {
    return ExecuteError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteError>, I>>(object: I): ExecuteError {
    const message = createBaseExecuteError();
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseMalformatRpcPacket(): MalformatRpcPacket {
  return { errorMessage: "" };
}

export const MalformatRpcPacket: MessageFns<MalformatRpcPacket> = {
  fromJSON(object: any): MalformatRpcPacket {
    return { errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "" };
  },

  toJSON(message: MalformatRpcPacket): unknown {
    const obj: any = {};
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MalformatRpcPacket>, I>>(base?: I): MalformatRpcPacket {
    return MalformatRpcPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MalformatRpcPacket>, I>>(object: I): MalformatRpcPacket {
    const message = createBaseMalformatRpcPacket();
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseTimeout(): Timeout {
  return { errorMessage: "" };
}

export const Timeout: MessageFns<Timeout> = {
  fromJSON(object: any): Timeout {
    return { errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "" };
  },

  toJSON(message: Timeout): unknown {
    const obj: any = {};
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Timeout>, I>>(base?: I): Timeout {
    return Timeout.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Timeout>, I>>(object: I): Timeout {
    const message = createBaseTimeout();
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseError(): Error {
  return {
    otherError: undefined,
    invalidMethodIndex: undefined,
    invalidService: undefined,
    prostDecodeError: undefined,
    prostEncodeError: undefined,
    executeError: undefined,
    malformatRpcPacket: undefined,
    timeout: undefined,
  };
}

export const Error: MessageFns<Error> = {
  fromJSON(object: any): Error {
    return {
      otherError: isSet(object.otherError) ? OtherError.fromJSON(object.otherError) : undefined,
      invalidMethodIndex: isSet(object.invalidMethodIndex)
        ? InvalidMethodIndex.fromJSON(object.invalidMethodIndex)
        : undefined,
      invalidService: isSet(object.invalidService) ? InvalidService.fromJSON(object.invalidService) : undefined,
      prostDecodeError: isSet(object.prostDecodeError) ? ProstDecodeError.fromJSON(object.prostDecodeError) : undefined,
      prostEncodeError: isSet(object.prostEncodeError) ? ProstEncodeError.fromJSON(object.prostEncodeError) : undefined,
      executeError: isSet(object.executeError) ? ExecuteError.fromJSON(object.executeError) : undefined,
      malformatRpcPacket: isSet(object.malformatRpcPacket)
        ? MalformatRpcPacket.fromJSON(object.malformatRpcPacket)
        : undefined,
      timeout: isSet(object.timeout) ? Timeout.fromJSON(object.timeout) : undefined,
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.otherError !== undefined) {
      obj.otherError = OtherError.toJSON(message.otherError);
    }
    if (message.invalidMethodIndex !== undefined) {
      obj.invalidMethodIndex = InvalidMethodIndex.toJSON(message.invalidMethodIndex);
    }
    if (message.invalidService !== undefined) {
      obj.invalidService = InvalidService.toJSON(message.invalidService);
    }
    if (message.prostDecodeError !== undefined) {
      obj.prostDecodeError = ProstDecodeError.toJSON(message.prostDecodeError);
    }
    if (message.prostEncodeError !== undefined) {
      obj.prostEncodeError = ProstEncodeError.toJSON(message.prostEncodeError);
    }
    if (message.executeError !== undefined) {
      obj.executeError = ExecuteError.toJSON(message.executeError);
    }
    if (message.malformatRpcPacket !== undefined) {
      obj.malformatRpcPacket = MalformatRpcPacket.toJSON(message.malformatRpcPacket);
    }
    if (message.timeout !== undefined) {
      obj.timeout = Timeout.toJSON(message.timeout);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.otherError = (object.otherError !== undefined && object.otherError !== null)
      ? OtherError.fromPartial(object.otherError)
      : undefined;
    message.invalidMethodIndex = (object.invalidMethodIndex !== undefined && object.invalidMethodIndex !== null)
      ? InvalidMethodIndex.fromPartial(object.invalidMethodIndex)
      : undefined;
    message.invalidService = (object.invalidService !== undefined && object.invalidService !== null)
      ? InvalidService.fromPartial(object.invalidService)
      : undefined;
    message.prostDecodeError = (object.prostDecodeError !== undefined && object.prostDecodeError !== null)
      ? ProstDecodeError.fromPartial(object.prostDecodeError)
      : undefined;
    message.prostEncodeError = (object.prostEncodeError !== undefined && object.prostEncodeError !== null)
      ? ProstEncodeError.fromPartial(object.prostEncodeError)
      : undefined;
    message.executeError = (object.executeError !== undefined && object.executeError !== null)
      ? ExecuteError.fromPartial(object.executeError)
      : undefined;
    message.malformatRpcPacket = (object.malformatRpcPacket !== undefined && object.malformatRpcPacket !== null)
      ? MalformatRpcPacket.fromPartial(object.malformatRpcPacket)
      : undefined;
    message.timeout = (object.timeout !== undefined && object.timeout !== null)
      ? Timeout.fromPartial(object.timeout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
