// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: error.proto

/* eslint-disable */

export const protobufPackage = "error";

export interface OtherError {
  error_message: string;
}

export interface InvalidMethodIndex {
  service_name: string;
  method_index: number;
}

export interface InvalidService {
  service_name: string;
}

export interface ProstDecodeError {
}

export interface ProstEncodeError {
}

export interface ExecuteError {
  error_message: string;
}

export interface MalformatRpcPacket {
  error_message: string;
}

export interface Timeout {
  error_message: string;
}

export interface Error {
  other_error?: OtherError | undefined;
  invalid_method_index?: InvalidMethodIndex | undefined;
  invalid_service?: InvalidService | undefined;
  prost_decode_error?: ProstDecodeError | undefined;
  prost_encode_error?: ProstEncodeError | undefined;
  execute_error?: ExecuteError | undefined;
  malformat_rpc_packet?: MalformatRpcPacket | undefined;
  timeout?: Timeout | undefined;
}

function createBaseOtherError(): OtherError {
  return { error_message: "" };
}

export const OtherError: MessageFns<OtherError> = {
  fromJSON(object: any): OtherError {
    return {
      error_message: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: OtherError): unknown {
    const obj: any = {};
    if (message.error_message !== "") {
      obj.errorMessage = message.error_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OtherError>, I>>(base?: I): OtherError {
    return OtherError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OtherError>, I>>(object: I): OtherError {
    const message = createBaseOtherError();
    message.error_message = object.error_message ?? "";
    return message;
  },
};

function createBaseInvalidMethodIndex(): InvalidMethodIndex {
  return { service_name: "", method_index: 0 };
}

export const InvalidMethodIndex: MessageFns<InvalidMethodIndex> = {
  fromJSON(object: any): InvalidMethodIndex {
    return {
      service_name: isSet(object.serviceName)
        ? globalThis.String(object.serviceName)
        : isSet(object.service_name)
        ? globalThis.String(object.service_name)
        : "",
      method_index: isSet(object.methodIndex)
        ? globalThis.Number(object.methodIndex)
        : isSet(object.method_index)
        ? globalThis.Number(object.method_index)
        : 0,
    };
  },

  toJSON(message: InvalidMethodIndex): unknown {
    const obj: any = {};
    if (message.service_name !== "") {
      obj.serviceName = message.service_name;
    }
    if (message.method_index !== 0) {
      obj.methodIndex = Math.round(message.method_index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidMethodIndex>, I>>(base?: I): InvalidMethodIndex {
    return InvalidMethodIndex.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidMethodIndex>, I>>(object: I): InvalidMethodIndex {
    const message = createBaseInvalidMethodIndex();
    message.service_name = object.service_name ?? "";
    message.method_index = object.method_index ?? 0;
    return message;
  },
};

function createBaseInvalidService(): InvalidService {
  return { service_name: "" };
}

export const InvalidService: MessageFns<InvalidService> = {
  fromJSON(object: any): InvalidService {
    return {
      service_name: isSet(object.serviceName)
        ? globalThis.String(object.serviceName)
        : isSet(object.service_name)
        ? globalThis.String(object.service_name)
        : "",
    };
  },

  toJSON(message: InvalidService): unknown {
    const obj: any = {};
    if (message.service_name !== "") {
      obj.serviceName = message.service_name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InvalidService>, I>>(base?: I): InvalidService {
    return InvalidService.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InvalidService>, I>>(object: I): InvalidService {
    const message = createBaseInvalidService();
    message.service_name = object.service_name ?? "";
    return message;
  },
};

function createBaseProstDecodeError(): ProstDecodeError {
  return {};
}

export const ProstDecodeError: MessageFns<ProstDecodeError> = {
  fromJSON(_: any): ProstDecodeError {
    return {};
  },

  toJSON(_: ProstDecodeError): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ProstDecodeError>, I>>(base?: I): ProstDecodeError {
    return ProstDecodeError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProstDecodeError>, I>>(_: I): ProstDecodeError {
    const message = createBaseProstDecodeError();
    return message;
  },
};

function createBaseProstEncodeError(): ProstEncodeError {
  return {};
}

export const ProstEncodeError: MessageFns<ProstEncodeError> = {
  fromJSON(_: any): ProstEncodeError {
    return {};
  },

  toJSON(_: ProstEncodeError): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ProstEncodeError>, I>>(base?: I): ProstEncodeError {
    return ProstEncodeError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProstEncodeError>, I>>(_: I): ProstEncodeError {
    const message = createBaseProstEncodeError();
    return message;
  },
};

function createBaseExecuteError(): ExecuteError {
  return { error_message: "" };
}

export const ExecuteError: MessageFns<ExecuteError> = {
  fromJSON(object: any): ExecuteError {
    return {
      error_message: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: ExecuteError): unknown {
    const obj: any = {};
    if (message.error_message !== "") {
      obj.errorMessage = message.error_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteError>, I>>(base?: I): ExecuteError {
    return ExecuteError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteError>, I>>(object: I): ExecuteError {
    const message = createBaseExecuteError();
    message.error_message = object.error_message ?? "";
    return message;
  },
};

function createBaseMalformatRpcPacket(): MalformatRpcPacket {
  return { error_message: "" };
}

export const MalformatRpcPacket: MessageFns<MalformatRpcPacket> = {
  fromJSON(object: any): MalformatRpcPacket {
    return {
      error_message: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: MalformatRpcPacket): unknown {
    const obj: any = {};
    if (message.error_message !== "") {
      obj.errorMessage = message.error_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MalformatRpcPacket>, I>>(base?: I): MalformatRpcPacket {
    return MalformatRpcPacket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MalformatRpcPacket>, I>>(object: I): MalformatRpcPacket {
    const message = createBaseMalformatRpcPacket();
    message.error_message = object.error_message ?? "";
    return message;
  },
};

function createBaseTimeout(): Timeout {
  return { error_message: "" };
}

export const Timeout: MessageFns<Timeout> = {
  fromJSON(object: any): Timeout {
    return {
      error_message: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: Timeout): unknown {
    const obj: any = {};
    if (message.error_message !== "") {
      obj.errorMessage = message.error_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Timeout>, I>>(base?: I): Timeout {
    return Timeout.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Timeout>, I>>(object: I): Timeout {
    const message = createBaseTimeout();
    message.error_message = object.error_message ?? "";
    return message;
  },
};

function createBaseError(): Error {
  return {
    other_error: undefined,
    invalid_method_index: undefined,
    invalid_service: undefined,
    prost_decode_error: undefined,
    prost_encode_error: undefined,
    execute_error: undefined,
    malformat_rpc_packet: undefined,
    timeout: undefined,
  };
}

export const Error: MessageFns<Error> = {
  fromJSON(object: any): Error {
    return {
      other_error: isSet(object.otherError)
        ? OtherError.fromJSON(object.otherError)
        : isSet(object.other_error)
        ? OtherError.fromJSON(object.other_error)
        : undefined,
      invalid_method_index: isSet(object.invalidMethodIndex)
        ? InvalidMethodIndex.fromJSON(object.invalidMethodIndex)
        : isSet(object.invalid_method_index)
        ? InvalidMethodIndex.fromJSON(object.invalid_method_index)
        : undefined,
      invalid_service: isSet(object.invalidService)
        ? InvalidService.fromJSON(object.invalidService)
        : isSet(object.invalid_service)
        ? InvalidService.fromJSON(object.invalid_service)
        : undefined,
      prost_decode_error: isSet(object.prostDecodeError)
        ? ProstDecodeError.fromJSON(object.prostDecodeError)
        : isSet(object.prost_decode_error)
        ? ProstDecodeError.fromJSON(object.prost_decode_error)
        : undefined,
      prost_encode_error: isSet(object.prostEncodeError)
        ? ProstEncodeError.fromJSON(object.prostEncodeError)
        : isSet(object.prost_encode_error)
        ? ProstEncodeError.fromJSON(object.prost_encode_error)
        : undefined,
      execute_error: isSet(object.executeError)
        ? ExecuteError.fromJSON(object.executeError)
        : isSet(object.execute_error)
        ? ExecuteError.fromJSON(object.execute_error)
        : undefined,
      malformat_rpc_packet: isSet(object.malformatRpcPacket)
        ? MalformatRpcPacket.fromJSON(object.malformatRpcPacket)
        : isSet(object.malformat_rpc_packet)
        ? MalformatRpcPacket.fromJSON(object.malformat_rpc_packet)
        : undefined,
      timeout: isSet(object.timeout) ? Timeout.fromJSON(object.timeout) : undefined,
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.other_error !== undefined) {
      obj.otherError = OtherError.toJSON(message.other_error);
    }
    if (message.invalid_method_index !== undefined) {
      obj.invalidMethodIndex = InvalidMethodIndex.toJSON(message.invalid_method_index);
    }
    if (message.invalid_service !== undefined) {
      obj.invalidService = InvalidService.toJSON(message.invalid_service);
    }
    if (message.prost_decode_error !== undefined) {
      obj.prostDecodeError = ProstDecodeError.toJSON(message.prost_decode_error);
    }
    if (message.prost_encode_error !== undefined) {
      obj.prostEncodeError = ProstEncodeError.toJSON(message.prost_encode_error);
    }
    if (message.execute_error !== undefined) {
      obj.executeError = ExecuteError.toJSON(message.execute_error);
    }
    if (message.malformat_rpc_packet !== undefined) {
      obj.malformatRpcPacket = MalformatRpcPacket.toJSON(message.malformat_rpc_packet);
    }
    if (message.timeout !== undefined) {
      obj.timeout = Timeout.toJSON(message.timeout);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.other_error = (object.other_error !== undefined && object.other_error !== null)
      ? OtherError.fromPartial(object.other_error)
      : undefined;
    message.invalid_method_index = (object.invalid_method_index !== undefined && object.invalid_method_index !== null)
      ? InvalidMethodIndex.fromPartial(object.invalid_method_index)
      : undefined;
    message.invalid_service = (object.invalid_service !== undefined && object.invalid_service !== null)
      ? InvalidService.fromPartial(object.invalid_service)
      : undefined;
    message.prost_decode_error = (object.prost_decode_error !== undefined && object.prost_decode_error !== null)
      ? ProstDecodeError.fromPartial(object.prost_decode_error)
      : undefined;
    message.prost_encode_error = (object.prost_encode_error !== undefined && object.prost_encode_error !== null)
      ? ProstEncodeError.fromPartial(object.prost_encode_error)
      : undefined;
    message.execute_error = (object.execute_error !== undefined && object.execute_error !== null)
      ? ExecuteError.fromPartial(object.execute_error)
      : undefined;
    message.malformat_rpc_packet = (object.malformat_rpc_packet !== undefined && object.malformat_rpc_packet !== null)
      ? MalformatRpcPacket.fromPartial(object.malformat_rpc_packet)
      : undefined;
    message.timeout = (object.timeout !== undefined && object.timeout !== null)
      ? Timeout.fromPartial(object.timeout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
