// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: peer_rpc.proto

/* eslint-disable */
import {
  Ipv4Addr,
  Ipv6Addr,
  Ipv6Inet,
  NatType,
  natTypeFromJSON,
  natTypeToJSON,
  PeerFeatureFlag,
  SocketAddr,
  Url,
  UUID,
} from "./common";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "peer_rpc";

export enum SyncRouteInfoError {
  DuplicatePeerId = 0,
  Stopped = 1,
  UNRECOGNIZED = -1,
}

export function syncRouteInfoErrorFromJSON(object: any): SyncRouteInfoError {
  switch (object) {
    case 0:
    case "DuplicatePeerId":
      return SyncRouteInfoError.DuplicatePeerId;
    case 1:
    case "Stopped":
      return SyncRouteInfoError.Stopped;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SyncRouteInfoError.UNRECOGNIZED;
  }
}

export function syncRouteInfoErrorToJSON(object: SyncRouteInfoError): string {
  switch (object) {
    case SyncRouteInfoError.DuplicatePeerId:
      return "DuplicatePeerId";
    case SyncRouteInfoError.Stopped:
      return "Stopped";
    case SyncRouteInfoError.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface RoutePeerInfo {
  /** means next hop in route table. */
  peerId: number;
  instId: UUID | undefined;
  cost: number;
  ipv4Addr?: Ipv4Addr | undefined;
  proxyCidrs: string[];
  hostname?: string | undefined;
  udpStunInfo: NatType;
  lastUpdate: Date | undefined;
  version: number;
  easytierVersion: string;
  featureFlag: PeerFeatureFlag | undefined;
  peerRouteId: number;
  networkLength: number;
  quicPort?: number | undefined;
  ipv6Addr?: Ipv6Inet | undefined;
  groups: PeerGroupInfo[];
}

export interface PeerIdVersion {
  peerId: number;
  version: number;
}

export interface RouteConnBitmap {
  peerIds: PeerIdVersion[];
  bitmap: Uint8Array;
}

export interface RouteConnPeerList {
  peerConnInfos: RouteConnPeerList_PeerConnInfo[];
}

export interface RouteConnPeerList_PeerConnInfo {
  peerId: PeerIdVersion | undefined;
  connectedPeerIds: number[];
}

export interface RoutePeerInfos {
  items: RoutePeerInfo[];
}

export interface ForeignNetworkRouteInfoKey {
  peerId: number;
  networkName: string;
}

export interface ForeignNetworkRouteInfoEntry {
  foreignPeerIds: number[];
  lastUpdate: Date | undefined;
  version: number;
  networkSecretDigest: Uint8Array;
  myPeerIdForThisNetwork: number;
}

export interface RouteForeignNetworkInfos {
  infos: RouteForeignNetworkInfos_Info[];
}

export interface RouteForeignNetworkInfos_Info {
  key: ForeignNetworkRouteInfoKey | undefined;
  value: ForeignNetworkRouteInfoEntry | undefined;
}

export interface RouteForeignNetworkSummary {
  infoMap: { [key: number]: RouteForeignNetworkSummary_Info };
}

export interface RouteForeignNetworkSummary_Info {
  peerId: number;
  networkCount: number;
  peerCount: number;
}

export interface RouteForeignNetworkSummary_InfoMapEntry {
  key: number;
  value: RouteForeignNetworkSummary_Info | undefined;
}

export interface PeerGroupInfo {
  groupName: string;
  groupProof: Uint8Array;
}

export interface SyncRouteInfoRequest {
  myPeerId: number;
  mySessionId: number;
  isInitiator: boolean;
  peerInfos: RoutePeerInfos | undefined;
  connBitmap?: RouteConnBitmap | undefined;
  connPeerList?: RouteConnPeerList | undefined;
  foreignNetworkInfos: RouteForeignNetworkInfos | undefined;
}

export interface SyncRouteInfoResponse {
  isInitiator: boolean;
  sessionId: number;
  error?: SyncRouteInfoError | undefined;
}

export interface GetIpListRequest {
}

export interface GetIpListResponse {
  publicIpv4: Ipv4Addr | undefined;
  interfaceIpv4s: Ipv4Addr[];
  publicIpv6: Ipv6Addr | undefined;
  interfaceIpv6s: Ipv6Addr[];
  listeners: Url[];
}

export interface SendV6HolePunchPacketRequest {
  connectorAddr: SocketAddr | undefined;
  listenerPort: number;
}

export interface SelectPunchListenerRequest {
  forceNew: boolean;
}

export interface SelectPunchListenerResponse {
  listenerMappedAddr: SocketAddr | undefined;
}

export interface SendPunchPacketConeRequest {
  listenerMappedAddr: SocketAddr | undefined;
  destAddr: SocketAddr | undefined;
  transactionId: number;
  /** send this many packets in a batch */
  packetCountPerBatch: number;
  /** send total this batch count, total packet count = packet_batch_size * packet_batch_count */
  packetBatchCount: number;
  /** interval between each batch */
  packetIntervalMs: number;
}

export interface SendPunchPacketHardSymRequest {
  listenerMappedAddr: SocketAddr | undefined;
  publicIps: Ipv4Addr[];
  transactionId: number;
  portIndex: number;
  round: number;
}

export interface SendPunchPacketHardSymResponse {
  nextPortIndex: number;
}

export interface SendPunchPacketEasySymRequest {
  listenerMappedAddr: SocketAddr | undefined;
  publicIps: Ipv4Addr[];
  transactionId: number;
  basePortNum: number;
  maxPortNum: number;
  isIncremental: boolean;
}

export interface SendPunchPacketBothEasySymRequest {
  udpSocketCount: number;
  publicIp: Ipv4Addr | undefined;
  transactionId: number;
  dstPortNum: number;
  waitTimeMs: number;
}

export interface SendPunchPacketBothEasySymResponse {
  /** is doing punch with other peer */
  isBusy: boolean;
  baseMappedAddr: SocketAddr | undefined;
}

export interface DirectConnectedPeerInfo {
  latencyMs: number;
}

export interface PeerInfoForGlobalMap {
  directPeers: { [key: number]: DirectConnectedPeerInfo };
}

export interface PeerInfoForGlobalMap_DirectPeersEntry {
  key: number;
  value: DirectConnectedPeerInfo | undefined;
}

export interface ReportPeersRequest {
  myPeerId: number;
  peerInfos: PeerInfoForGlobalMap | undefined;
}

export interface ReportPeersResponse {
}

export interface GlobalPeerMap {
  map: { [key: number]: PeerInfoForGlobalMap };
}

export interface GlobalPeerMap_MapEntry {
  key: number;
  value: PeerInfoForGlobalMap | undefined;
}

export interface GetGlobalPeerMapRequest {
  digest: number;
}

export interface GetGlobalPeerMapResponse {
  globalPeerMap: { [key: number]: PeerInfoForGlobalMap };
  digest?: number | undefined;
}

export interface GetGlobalPeerMapResponse_GlobalPeerMapEntry {
  key: number;
  value: PeerInfoForGlobalMap | undefined;
}

export interface HandshakeRequest {
  magic: number;
  myPeerId: number;
  version: number;
  features: string[];
  networkName: string;
  networkSecretDigrest: Uint8Array;
}

export interface KcpConnData {
  src: SocketAddr | undefined;
  dst: SocketAddr | undefined;
}

function createBaseRoutePeerInfo(): RoutePeerInfo {
  return {
    peerId: 0,
    instId: undefined,
    cost: 0,
    ipv4Addr: undefined,
    proxyCidrs: [],
    hostname: undefined,
    udpStunInfo: 0,
    lastUpdate: undefined,
    version: 0,
    easytierVersion: "",
    featureFlag: undefined,
    peerRouteId: 0,
    networkLength: 0,
    quicPort: undefined,
    ipv6Addr: undefined,
    groups: [],
  };
}

export const RoutePeerInfo: MessageFns<RoutePeerInfo> = {
  fromJSON(object: any): RoutePeerInfo {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      instId: isSet(object.instId) ? UUID.fromJSON(object.instId) : undefined,
      cost: isSet(object.cost) ? globalThis.Number(object.cost) : 0,
      ipv4Addr: isSet(object.ipv4Addr) ? Ipv4Addr.fromJSON(object.ipv4Addr) : undefined,
      proxyCidrs: globalThis.Array.isArray(object?.proxyCidrs)
        ? object.proxyCidrs.map((e: any) => globalThis.String(e))
        : [],
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : undefined,
      udpStunInfo: isSet(object.udpStunInfo) ? natTypeFromJSON(object.udpStunInfo) : 0,
      lastUpdate: isSet(object.lastUpdate) ? fromJsonTimestamp(object.lastUpdate) : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      easytierVersion: isSet(object.easytierVersion) ? globalThis.String(object.easytierVersion) : "",
      featureFlag: isSet(object.featureFlag) ? PeerFeatureFlag.fromJSON(object.featureFlag) : undefined,
      peerRouteId: isSet(object.peerRouteId) ? globalThis.Number(object.peerRouteId) : 0,
      networkLength: isSet(object.networkLength) ? globalThis.Number(object.networkLength) : 0,
      quicPort: isSet(object.quicPort) ? globalThis.Number(object.quicPort) : undefined,
      ipv6Addr: isSet(object.ipv6Addr) ? Ipv6Inet.fromJSON(object.ipv6Addr) : undefined,
      groups: globalThis.Array.isArray(object?.groups)
        ? object.groups.map((e: any) => PeerGroupInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RoutePeerInfo): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.instId !== undefined) {
      obj.instId = UUID.toJSON(message.instId);
    }
    if (message.cost !== 0) {
      obj.cost = Math.round(message.cost);
    }
    if (message.ipv4Addr !== undefined) {
      obj.ipv4Addr = Ipv4Addr.toJSON(message.ipv4Addr);
    }
    if (message.proxyCidrs?.length) {
      obj.proxyCidrs = message.proxyCidrs;
    }
    if (message.hostname !== undefined) {
      obj.hostname = message.hostname;
    }
    if (message.udpStunInfo !== 0) {
      obj.udpStunInfo = natTypeToJSON(message.udpStunInfo);
    }
    if (message.lastUpdate !== undefined) {
      obj.lastUpdate = message.lastUpdate.toISOString();
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.easytierVersion !== "") {
      obj.easytierVersion = message.easytierVersion;
    }
    if (message.featureFlag !== undefined) {
      obj.featureFlag = PeerFeatureFlag.toJSON(message.featureFlag);
    }
    if (message.peerRouteId !== 0) {
      obj.peerRouteId = Math.round(message.peerRouteId);
    }
    if (message.networkLength !== 0) {
      obj.networkLength = Math.round(message.networkLength);
    }
    if (message.quicPort !== undefined) {
      obj.quicPort = Math.round(message.quicPort);
    }
    if (message.ipv6Addr !== undefined) {
      obj.ipv6Addr = Ipv6Inet.toJSON(message.ipv6Addr);
    }
    if (message.groups?.length) {
      obj.groups = message.groups.map((e) => PeerGroupInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoutePeerInfo>, I>>(base?: I): RoutePeerInfo {
    return RoutePeerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoutePeerInfo>, I>>(object: I): RoutePeerInfo {
    const message = createBaseRoutePeerInfo();
    message.peerId = object.peerId ?? 0;
    message.instId = (object.instId !== undefined && object.instId !== null)
      ? UUID.fromPartial(object.instId)
      : undefined;
    message.cost = object.cost ?? 0;
    message.ipv4Addr = (object.ipv4Addr !== undefined && object.ipv4Addr !== null)
      ? Ipv4Addr.fromPartial(object.ipv4Addr)
      : undefined;
    message.proxyCidrs = object.proxyCidrs?.map((e) => e) || [];
    message.hostname = object.hostname ?? undefined;
    message.udpStunInfo = object.udpStunInfo ?? 0;
    message.lastUpdate = object.lastUpdate ?? undefined;
    message.version = object.version ?? 0;
    message.easytierVersion = object.easytierVersion ?? "";
    message.featureFlag = (object.featureFlag !== undefined && object.featureFlag !== null)
      ? PeerFeatureFlag.fromPartial(object.featureFlag)
      : undefined;
    message.peerRouteId = object.peerRouteId ?? 0;
    message.networkLength = object.networkLength ?? 0;
    message.quicPort = object.quicPort ?? undefined;
    message.ipv6Addr = (object.ipv6Addr !== undefined && object.ipv6Addr !== null)
      ? Ipv6Inet.fromPartial(object.ipv6Addr)
      : undefined;
    message.groups = object.groups?.map((e) => PeerGroupInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBasePeerIdVersion(): PeerIdVersion {
  return { peerId: 0, version: 0 };
}

export const PeerIdVersion: MessageFns<PeerIdVersion> = {
  fromJSON(object: any): PeerIdVersion {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: PeerIdVersion): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerIdVersion>, I>>(base?: I): PeerIdVersion {
    return PeerIdVersion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerIdVersion>, I>>(object: I): PeerIdVersion {
    const message = createBasePeerIdVersion();
    message.peerId = object.peerId ?? 0;
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseRouteConnBitmap(): RouteConnBitmap {
  return { peerIds: [], bitmap: new Uint8Array(0) };
}

export const RouteConnBitmap: MessageFns<RouteConnBitmap> = {
  fromJSON(object: any): RouteConnBitmap {
    return {
      peerIds: globalThis.Array.isArray(object?.peerIds)
        ? object.peerIds.map((e: any) => PeerIdVersion.fromJSON(e))
        : [],
      bitmap: isSet(object.bitmap) ? bytesFromBase64(object.bitmap) : new Uint8Array(0),
    };
  },

  toJSON(message: RouteConnBitmap): unknown {
    const obj: any = {};
    if (message.peerIds?.length) {
      obj.peerIds = message.peerIds.map((e) => PeerIdVersion.toJSON(e));
    }
    if (message.bitmap.length !== 0) {
      obj.bitmap = base64FromBytes(message.bitmap);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteConnBitmap>, I>>(base?: I): RouteConnBitmap {
    return RouteConnBitmap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteConnBitmap>, I>>(object: I): RouteConnBitmap {
    const message = createBaseRouteConnBitmap();
    message.peerIds = object.peerIds?.map((e) => PeerIdVersion.fromPartial(e)) || [];
    message.bitmap = object.bitmap ?? new Uint8Array(0);
    return message;
  },
};

function createBaseRouteConnPeerList(): RouteConnPeerList {
  return { peerConnInfos: [] };
}

export const RouteConnPeerList: MessageFns<RouteConnPeerList> = {
  fromJSON(object: any): RouteConnPeerList {
    return {
      peerConnInfos: globalThis.Array.isArray(object?.peerConnInfos)
        ? object.peerConnInfos.map((e: any) => RouteConnPeerList_PeerConnInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RouteConnPeerList): unknown {
    const obj: any = {};
    if (message.peerConnInfos?.length) {
      obj.peerConnInfos = message.peerConnInfos.map((e) => RouteConnPeerList_PeerConnInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteConnPeerList>, I>>(base?: I): RouteConnPeerList {
    return RouteConnPeerList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteConnPeerList>, I>>(object: I): RouteConnPeerList {
    const message = createBaseRouteConnPeerList();
    message.peerConnInfos = object.peerConnInfos?.map((e) => RouteConnPeerList_PeerConnInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRouteConnPeerList_PeerConnInfo(): RouteConnPeerList_PeerConnInfo {
  return { peerId: undefined, connectedPeerIds: [] };
}

export const RouteConnPeerList_PeerConnInfo: MessageFns<RouteConnPeerList_PeerConnInfo> = {
  fromJSON(object: any): RouteConnPeerList_PeerConnInfo {
    return {
      peerId: isSet(object.peerId) ? PeerIdVersion.fromJSON(object.peerId) : undefined,
      connectedPeerIds: globalThis.Array.isArray(object?.connectedPeerIds)
        ? object.connectedPeerIds.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: RouteConnPeerList_PeerConnInfo): unknown {
    const obj: any = {};
    if (message.peerId !== undefined) {
      obj.peerId = PeerIdVersion.toJSON(message.peerId);
    }
    if (message.connectedPeerIds?.length) {
      obj.connectedPeerIds = message.connectedPeerIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteConnPeerList_PeerConnInfo>, I>>(base?: I): RouteConnPeerList_PeerConnInfo {
    return RouteConnPeerList_PeerConnInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteConnPeerList_PeerConnInfo>, I>>(
    object: I,
  ): RouteConnPeerList_PeerConnInfo {
    const message = createBaseRouteConnPeerList_PeerConnInfo();
    message.peerId = (object.peerId !== undefined && object.peerId !== null)
      ? PeerIdVersion.fromPartial(object.peerId)
      : undefined;
    message.connectedPeerIds = object.connectedPeerIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseRoutePeerInfos(): RoutePeerInfos {
  return { items: [] };
}

export const RoutePeerInfos: MessageFns<RoutePeerInfos> = {
  fromJSON(object: any): RoutePeerInfos {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => RoutePeerInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: RoutePeerInfos): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => RoutePeerInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoutePeerInfos>, I>>(base?: I): RoutePeerInfos {
    return RoutePeerInfos.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoutePeerInfos>, I>>(object: I): RoutePeerInfos {
    const message = createBaseRoutePeerInfos();
    message.items = object.items?.map((e) => RoutePeerInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseForeignNetworkRouteInfoKey(): ForeignNetworkRouteInfoKey {
  return { peerId: 0, networkName: "" };
}

export const ForeignNetworkRouteInfoKey: MessageFns<ForeignNetworkRouteInfoKey> = {
  fromJSON(object: any): ForeignNetworkRouteInfoKey {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : "",
    };
  },

  toJSON(message: ForeignNetworkRouteInfoKey): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.networkName !== "") {
      obj.networkName = message.networkName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForeignNetworkRouteInfoKey>, I>>(base?: I): ForeignNetworkRouteInfoKey {
    return ForeignNetworkRouteInfoKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForeignNetworkRouteInfoKey>, I>>(object: I): ForeignNetworkRouteInfoKey {
    const message = createBaseForeignNetworkRouteInfoKey();
    message.peerId = object.peerId ?? 0;
    message.networkName = object.networkName ?? "";
    return message;
  },
};

function createBaseForeignNetworkRouteInfoEntry(): ForeignNetworkRouteInfoEntry {
  return {
    foreignPeerIds: [],
    lastUpdate: undefined,
    version: 0,
    networkSecretDigest: new Uint8Array(0),
    myPeerIdForThisNetwork: 0,
  };
}

export const ForeignNetworkRouteInfoEntry: MessageFns<ForeignNetworkRouteInfoEntry> = {
  fromJSON(object: any): ForeignNetworkRouteInfoEntry {
    return {
      foreignPeerIds: globalThis.Array.isArray(object?.foreignPeerIds)
        ? object.foreignPeerIds.map((e: any) => globalThis.Number(e))
        : [],
      lastUpdate: isSet(object.lastUpdate) ? fromJsonTimestamp(object.lastUpdate) : undefined,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      networkSecretDigest: isSet(object.networkSecretDigest)
        ? bytesFromBase64(object.networkSecretDigest)
        : new Uint8Array(0),
      myPeerIdForThisNetwork: isSet(object.myPeerIdForThisNetwork)
        ? globalThis.Number(object.myPeerIdForThisNetwork)
        : 0,
    };
  },

  toJSON(message: ForeignNetworkRouteInfoEntry): unknown {
    const obj: any = {};
    if (message.foreignPeerIds?.length) {
      obj.foreignPeerIds = message.foreignPeerIds.map((e) => Math.round(e));
    }
    if (message.lastUpdate !== undefined) {
      obj.lastUpdate = message.lastUpdate.toISOString();
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.networkSecretDigest.length !== 0) {
      obj.networkSecretDigest = base64FromBytes(message.networkSecretDigest);
    }
    if (message.myPeerIdForThisNetwork !== 0) {
      obj.myPeerIdForThisNetwork = Math.round(message.myPeerIdForThisNetwork);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForeignNetworkRouteInfoEntry>, I>>(base?: I): ForeignNetworkRouteInfoEntry {
    return ForeignNetworkRouteInfoEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForeignNetworkRouteInfoEntry>, I>>(object: I): ForeignNetworkRouteInfoEntry {
    const message = createBaseForeignNetworkRouteInfoEntry();
    message.foreignPeerIds = object.foreignPeerIds?.map((e) => e) || [];
    message.lastUpdate = object.lastUpdate ?? undefined;
    message.version = object.version ?? 0;
    message.networkSecretDigest = object.networkSecretDigest ?? new Uint8Array(0);
    message.myPeerIdForThisNetwork = object.myPeerIdForThisNetwork ?? 0;
    return message;
  },
};

function createBaseRouteForeignNetworkInfos(): RouteForeignNetworkInfos {
  return { infos: [] };
}

export const RouteForeignNetworkInfos: MessageFns<RouteForeignNetworkInfos> = {
  fromJSON(object: any): RouteForeignNetworkInfos {
    return {
      infos: globalThis.Array.isArray(object?.infos)
        ? object.infos.map((e: any) => RouteForeignNetworkInfos_Info.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RouteForeignNetworkInfos): unknown {
    const obj: any = {};
    if (message.infos?.length) {
      obj.infos = message.infos.map((e) => RouteForeignNetworkInfos_Info.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteForeignNetworkInfos>, I>>(base?: I): RouteForeignNetworkInfos {
    return RouteForeignNetworkInfos.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteForeignNetworkInfos>, I>>(object: I): RouteForeignNetworkInfos {
    const message = createBaseRouteForeignNetworkInfos();
    message.infos = object.infos?.map((e) => RouteForeignNetworkInfos_Info.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRouteForeignNetworkInfos_Info(): RouteForeignNetworkInfos_Info {
  return { key: undefined, value: undefined };
}

export const RouteForeignNetworkInfos_Info: MessageFns<RouteForeignNetworkInfos_Info> = {
  fromJSON(object: any): RouteForeignNetworkInfos_Info {
    return {
      key: isSet(object.key) ? ForeignNetworkRouteInfoKey.fromJSON(object.key) : undefined,
      value: isSet(object.value) ? ForeignNetworkRouteInfoEntry.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: RouteForeignNetworkInfos_Info): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = ForeignNetworkRouteInfoKey.toJSON(message.key);
    }
    if (message.value !== undefined) {
      obj.value = ForeignNetworkRouteInfoEntry.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteForeignNetworkInfos_Info>, I>>(base?: I): RouteForeignNetworkInfos_Info {
    return RouteForeignNetworkInfos_Info.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteForeignNetworkInfos_Info>, I>>(
    object: I,
  ): RouteForeignNetworkInfos_Info {
    const message = createBaseRouteForeignNetworkInfos_Info();
    message.key = (object.key !== undefined && object.key !== null)
      ? ForeignNetworkRouteInfoKey.fromPartial(object.key)
      : undefined;
    message.value = (object.value !== undefined && object.value !== null)
      ? ForeignNetworkRouteInfoEntry.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseRouteForeignNetworkSummary(): RouteForeignNetworkSummary {
  return { infoMap: {} };
}

export const RouteForeignNetworkSummary: MessageFns<RouteForeignNetworkSummary> = {
  fromJSON(object: any): RouteForeignNetworkSummary {
    return {
      infoMap: isObject(object.infoMap)
        ? Object.entries(object.infoMap).reduce<{ [key: number]: RouteForeignNetworkSummary_Info }>(
          (acc, [key, value]) => {
            acc[globalThis.Number(key)] = RouteForeignNetworkSummary_Info.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: RouteForeignNetworkSummary): unknown {
    const obj: any = {};
    if (message.infoMap) {
      const entries = Object.entries(message.infoMap);
      if (entries.length > 0) {
        obj.infoMap = {};
        entries.forEach(([k, v]) => {
          obj.infoMap[k] = RouteForeignNetworkSummary_Info.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteForeignNetworkSummary>, I>>(base?: I): RouteForeignNetworkSummary {
    return RouteForeignNetworkSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteForeignNetworkSummary>, I>>(object: I): RouteForeignNetworkSummary {
    const message = createBaseRouteForeignNetworkSummary();
    message.infoMap = Object.entries(object.infoMap ?? {}).reduce<{ [key: number]: RouteForeignNetworkSummary_Info }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = RouteForeignNetworkSummary_Info.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseRouteForeignNetworkSummary_Info(): RouteForeignNetworkSummary_Info {
  return { peerId: 0, networkCount: 0, peerCount: 0 };
}

export const RouteForeignNetworkSummary_Info: MessageFns<RouteForeignNetworkSummary_Info> = {
  fromJSON(object: any): RouteForeignNetworkSummary_Info {
    return {
      peerId: isSet(object.peerId) ? globalThis.Number(object.peerId) : 0,
      networkCount: isSet(object.networkCount) ? globalThis.Number(object.networkCount) : 0,
      peerCount: isSet(object.peerCount) ? globalThis.Number(object.peerCount) : 0,
    };
  },

  toJSON(message: RouteForeignNetworkSummary_Info): unknown {
    const obj: any = {};
    if (message.peerId !== 0) {
      obj.peerId = Math.round(message.peerId);
    }
    if (message.networkCount !== 0) {
      obj.networkCount = Math.round(message.networkCount);
    }
    if (message.peerCount !== 0) {
      obj.peerCount = Math.round(message.peerCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteForeignNetworkSummary_Info>, I>>(base?: I): RouteForeignNetworkSummary_Info {
    return RouteForeignNetworkSummary_Info.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteForeignNetworkSummary_Info>, I>>(
    object: I,
  ): RouteForeignNetworkSummary_Info {
    const message = createBaseRouteForeignNetworkSummary_Info();
    message.peerId = object.peerId ?? 0;
    message.networkCount = object.networkCount ?? 0;
    message.peerCount = object.peerCount ?? 0;
    return message;
  },
};

function createBaseRouteForeignNetworkSummary_InfoMapEntry(): RouteForeignNetworkSummary_InfoMapEntry {
  return { key: 0, value: undefined };
}

export const RouteForeignNetworkSummary_InfoMapEntry: MessageFns<RouteForeignNetworkSummary_InfoMapEntry> = {
  fromJSON(object: any): RouteForeignNetworkSummary_InfoMapEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? RouteForeignNetworkSummary_Info.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: RouteForeignNetworkSummary_InfoMapEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = RouteForeignNetworkSummary_Info.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteForeignNetworkSummary_InfoMapEntry>, I>>(
    base?: I,
  ): RouteForeignNetworkSummary_InfoMapEntry {
    return RouteForeignNetworkSummary_InfoMapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteForeignNetworkSummary_InfoMapEntry>, I>>(
    object: I,
  ): RouteForeignNetworkSummary_InfoMapEntry {
    const message = createBaseRouteForeignNetworkSummary_InfoMapEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? RouteForeignNetworkSummary_Info.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBasePeerGroupInfo(): PeerGroupInfo {
  return { groupName: "", groupProof: new Uint8Array(0) };
}

export const PeerGroupInfo: MessageFns<PeerGroupInfo> = {
  fromJSON(object: any): PeerGroupInfo {
    return {
      groupName: isSet(object.groupName) ? globalThis.String(object.groupName) : "",
      groupProof: isSet(object.groupProof) ? bytesFromBase64(object.groupProof) : new Uint8Array(0),
    };
  },

  toJSON(message: PeerGroupInfo): unknown {
    const obj: any = {};
    if (message.groupName !== "") {
      obj.groupName = message.groupName;
    }
    if (message.groupProof.length !== 0) {
      obj.groupProof = base64FromBytes(message.groupProof);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerGroupInfo>, I>>(base?: I): PeerGroupInfo {
    return PeerGroupInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerGroupInfo>, I>>(object: I): PeerGroupInfo {
    const message = createBasePeerGroupInfo();
    message.groupName = object.groupName ?? "";
    message.groupProof = object.groupProof ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSyncRouteInfoRequest(): SyncRouteInfoRequest {
  return {
    myPeerId: 0,
    mySessionId: 0,
    isInitiator: false,
    peerInfos: undefined,
    connBitmap: undefined,
    connPeerList: undefined,
    foreignNetworkInfos: undefined,
  };
}

export const SyncRouteInfoRequest: MessageFns<SyncRouteInfoRequest> = {
  fromJSON(object: any): SyncRouteInfoRequest {
    return {
      myPeerId: isSet(object.myPeerId) ? globalThis.Number(object.myPeerId) : 0,
      mySessionId: isSet(object.mySessionId) ? globalThis.Number(object.mySessionId) : 0,
      isInitiator: isSet(object.isInitiator) ? globalThis.Boolean(object.isInitiator) : false,
      peerInfos: isSet(object.peerInfos) ? RoutePeerInfos.fromJSON(object.peerInfos) : undefined,
      connBitmap: isSet(object.connBitmap) ? RouteConnBitmap.fromJSON(object.connBitmap) : undefined,
      connPeerList: isSet(object.connPeerList) ? RouteConnPeerList.fromJSON(object.connPeerList) : undefined,
      foreignNetworkInfos: isSet(object.foreignNetworkInfos)
        ? RouteForeignNetworkInfos.fromJSON(object.foreignNetworkInfos)
        : undefined,
    };
  },

  toJSON(message: SyncRouteInfoRequest): unknown {
    const obj: any = {};
    if (message.myPeerId !== 0) {
      obj.myPeerId = Math.round(message.myPeerId);
    }
    if (message.mySessionId !== 0) {
      obj.mySessionId = Math.round(message.mySessionId);
    }
    if (message.isInitiator !== false) {
      obj.isInitiator = message.isInitiator;
    }
    if (message.peerInfos !== undefined) {
      obj.peerInfos = RoutePeerInfos.toJSON(message.peerInfos);
    }
    if (message.connBitmap !== undefined) {
      obj.connBitmap = RouteConnBitmap.toJSON(message.connBitmap);
    }
    if (message.connPeerList !== undefined) {
      obj.connPeerList = RouteConnPeerList.toJSON(message.connPeerList);
    }
    if (message.foreignNetworkInfos !== undefined) {
      obj.foreignNetworkInfos = RouteForeignNetworkInfos.toJSON(message.foreignNetworkInfos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncRouteInfoRequest>, I>>(base?: I): SyncRouteInfoRequest {
    return SyncRouteInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncRouteInfoRequest>, I>>(object: I): SyncRouteInfoRequest {
    const message = createBaseSyncRouteInfoRequest();
    message.myPeerId = object.myPeerId ?? 0;
    message.mySessionId = object.mySessionId ?? 0;
    message.isInitiator = object.isInitiator ?? false;
    message.peerInfos = (object.peerInfos !== undefined && object.peerInfos !== null)
      ? RoutePeerInfos.fromPartial(object.peerInfos)
      : undefined;
    message.connBitmap = (object.connBitmap !== undefined && object.connBitmap !== null)
      ? RouteConnBitmap.fromPartial(object.connBitmap)
      : undefined;
    message.connPeerList = (object.connPeerList !== undefined && object.connPeerList !== null)
      ? RouteConnPeerList.fromPartial(object.connPeerList)
      : undefined;
    message.foreignNetworkInfos = (object.foreignNetworkInfos !== undefined && object.foreignNetworkInfos !== null)
      ? RouteForeignNetworkInfos.fromPartial(object.foreignNetworkInfos)
      : undefined;
    return message;
  },
};

function createBaseSyncRouteInfoResponse(): SyncRouteInfoResponse {
  return { isInitiator: false, sessionId: 0, error: undefined };
}

export const SyncRouteInfoResponse: MessageFns<SyncRouteInfoResponse> = {
  fromJSON(object: any): SyncRouteInfoResponse {
    return {
      isInitiator: isSet(object.isInitiator) ? globalThis.Boolean(object.isInitiator) : false,
      sessionId: isSet(object.sessionId) ? globalThis.Number(object.sessionId) : 0,
      error: isSet(object.error) ? syncRouteInfoErrorFromJSON(object.error) : undefined,
    };
  },

  toJSON(message: SyncRouteInfoResponse): unknown {
    const obj: any = {};
    if (message.isInitiator !== false) {
      obj.isInitiator = message.isInitiator;
    }
    if (message.sessionId !== 0) {
      obj.sessionId = Math.round(message.sessionId);
    }
    if (message.error !== undefined) {
      obj.error = syncRouteInfoErrorToJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncRouteInfoResponse>, I>>(base?: I): SyncRouteInfoResponse {
    return SyncRouteInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncRouteInfoResponse>, I>>(object: I): SyncRouteInfoResponse {
    const message = createBaseSyncRouteInfoResponse();
    message.isInitiator = object.isInitiator ?? false;
    message.sessionId = object.sessionId ?? 0;
    message.error = object.error ?? undefined;
    return message;
  },
};

function createBaseGetIpListRequest(): GetIpListRequest {
  return {};
}

export const GetIpListRequest: MessageFns<GetIpListRequest> = {
  fromJSON(_: any): GetIpListRequest {
    return {};
  },

  toJSON(_: GetIpListRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetIpListRequest>, I>>(base?: I): GetIpListRequest {
    return GetIpListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetIpListRequest>, I>>(_: I): GetIpListRequest {
    const message = createBaseGetIpListRequest();
    return message;
  },
};

function createBaseGetIpListResponse(): GetIpListResponse {
  return { publicIpv4: undefined, interfaceIpv4s: [], publicIpv6: undefined, interfaceIpv6s: [], listeners: [] };
}

export const GetIpListResponse: MessageFns<GetIpListResponse> = {
  fromJSON(object: any): GetIpListResponse {
    return {
      publicIpv4: isSet(object.publicIpv4) ? Ipv4Addr.fromJSON(object.publicIpv4) : undefined,
      interfaceIpv4s: globalThis.Array.isArray(object?.interfaceIpv4s)
        ? object.interfaceIpv4s.map((e: any) => Ipv4Addr.fromJSON(e))
        : [],
      publicIpv6: isSet(object.publicIpv6) ? Ipv6Addr.fromJSON(object.publicIpv6) : undefined,
      interfaceIpv6s: globalThis.Array.isArray(object?.interfaceIpv6s)
        ? object.interfaceIpv6s.map((e: any) => Ipv6Addr.fromJSON(e))
        : [],
      listeners: globalThis.Array.isArray(object?.listeners) ? object.listeners.map((e: any) => Url.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetIpListResponse): unknown {
    const obj: any = {};
    if (message.publicIpv4 !== undefined) {
      obj.publicIpv4 = Ipv4Addr.toJSON(message.publicIpv4);
    }
    if (message.interfaceIpv4s?.length) {
      obj.interfaceIpv4s = message.interfaceIpv4s.map((e) => Ipv4Addr.toJSON(e));
    }
    if (message.publicIpv6 !== undefined) {
      obj.publicIpv6 = Ipv6Addr.toJSON(message.publicIpv6);
    }
    if (message.interfaceIpv6s?.length) {
      obj.interfaceIpv6s = message.interfaceIpv6s.map((e) => Ipv6Addr.toJSON(e));
    }
    if (message.listeners?.length) {
      obj.listeners = message.listeners.map((e) => Url.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetIpListResponse>, I>>(base?: I): GetIpListResponse {
    return GetIpListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetIpListResponse>, I>>(object: I): GetIpListResponse {
    const message = createBaseGetIpListResponse();
    message.publicIpv4 = (object.publicIpv4 !== undefined && object.publicIpv4 !== null)
      ? Ipv4Addr.fromPartial(object.publicIpv4)
      : undefined;
    message.interfaceIpv4s = object.interfaceIpv4s?.map((e) => Ipv4Addr.fromPartial(e)) || [];
    message.publicIpv6 = (object.publicIpv6 !== undefined && object.publicIpv6 !== null)
      ? Ipv6Addr.fromPartial(object.publicIpv6)
      : undefined;
    message.interfaceIpv6s = object.interfaceIpv6s?.map((e) => Ipv6Addr.fromPartial(e)) || [];
    message.listeners = object.listeners?.map((e) => Url.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSendV6HolePunchPacketRequest(): SendV6HolePunchPacketRequest {
  return { connectorAddr: undefined, listenerPort: 0 };
}

export const SendV6HolePunchPacketRequest: MessageFns<SendV6HolePunchPacketRequest> = {
  fromJSON(object: any): SendV6HolePunchPacketRequest {
    return {
      connectorAddr: isSet(object.connectorAddr) ? SocketAddr.fromJSON(object.connectorAddr) : undefined,
      listenerPort: isSet(object.listenerPort) ? globalThis.Number(object.listenerPort) : 0,
    };
  },

  toJSON(message: SendV6HolePunchPacketRequest): unknown {
    const obj: any = {};
    if (message.connectorAddr !== undefined) {
      obj.connectorAddr = SocketAddr.toJSON(message.connectorAddr);
    }
    if (message.listenerPort !== 0) {
      obj.listenerPort = Math.round(message.listenerPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendV6HolePunchPacketRequest>, I>>(base?: I): SendV6HolePunchPacketRequest {
    return SendV6HolePunchPacketRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendV6HolePunchPacketRequest>, I>>(object: I): SendV6HolePunchPacketRequest {
    const message = createBaseSendV6HolePunchPacketRequest();
    message.connectorAddr = (object.connectorAddr !== undefined && object.connectorAddr !== null)
      ? SocketAddr.fromPartial(object.connectorAddr)
      : undefined;
    message.listenerPort = object.listenerPort ?? 0;
    return message;
  },
};

function createBaseSelectPunchListenerRequest(): SelectPunchListenerRequest {
  return { forceNew: false };
}

export const SelectPunchListenerRequest: MessageFns<SelectPunchListenerRequest> = {
  fromJSON(object: any): SelectPunchListenerRequest {
    return { forceNew: isSet(object.forceNew) ? globalThis.Boolean(object.forceNew) : false };
  },

  toJSON(message: SelectPunchListenerRequest): unknown {
    const obj: any = {};
    if (message.forceNew !== false) {
      obj.forceNew = message.forceNew;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SelectPunchListenerRequest>, I>>(base?: I): SelectPunchListenerRequest {
    return SelectPunchListenerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SelectPunchListenerRequest>, I>>(object: I): SelectPunchListenerRequest {
    const message = createBaseSelectPunchListenerRequest();
    message.forceNew = object.forceNew ?? false;
    return message;
  },
};

function createBaseSelectPunchListenerResponse(): SelectPunchListenerResponse {
  return { listenerMappedAddr: undefined };
}

export const SelectPunchListenerResponse: MessageFns<SelectPunchListenerResponse> = {
  fromJSON(object: any): SelectPunchListenerResponse {
    return {
      listenerMappedAddr: isSet(object.listenerMappedAddr) ? SocketAddr.fromJSON(object.listenerMappedAddr) : undefined,
    };
  },

  toJSON(message: SelectPunchListenerResponse): unknown {
    const obj: any = {};
    if (message.listenerMappedAddr !== undefined) {
      obj.listenerMappedAddr = SocketAddr.toJSON(message.listenerMappedAddr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SelectPunchListenerResponse>, I>>(base?: I): SelectPunchListenerResponse {
    return SelectPunchListenerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SelectPunchListenerResponse>, I>>(object: I): SelectPunchListenerResponse {
    const message = createBaseSelectPunchListenerResponse();
    message.listenerMappedAddr = (object.listenerMappedAddr !== undefined && object.listenerMappedAddr !== null)
      ? SocketAddr.fromPartial(object.listenerMappedAddr)
      : undefined;
    return message;
  },
};

function createBaseSendPunchPacketConeRequest(): SendPunchPacketConeRequest {
  return {
    listenerMappedAddr: undefined,
    destAddr: undefined,
    transactionId: 0,
    packetCountPerBatch: 0,
    packetBatchCount: 0,
    packetIntervalMs: 0,
  };
}

export const SendPunchPacketConeRequest: MessageFns<SendPunchPacketConeRequest> = {
  fromJSON(object: any): SendPunchPacketConeRequest {
    return {
      listenerMappedAddr: isSet(object.listenerMappedAddr) ? SocketAddr.fromJSON(object.listenerMappedAddr) : undefined,
      destAddr: isSet(object.destAddr) ? SocketAddr.fromJSON(object.destAddr) : undefined,
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      packetCountPerBatch: isSet(object.packetCountPerBatch) ? globalThis.Number(object.packetCountPerBatch) : 0,
      packetBatchCount: isSet(object.packetBatchCount) ? globalThis.Number(object.packetBatchCount) : 0,
      packetIntervalMs: isSet(object.packetIntervalMs) ? globalThis.Number(object.packetIntervalMs) : 0,
    };
  },

  toJSON(message: SendPunchPacketConeRequest): unknown {
    const obj: any = {};
    if (message.listenerMappedAddr !== undefined) {
      obj.listenerMappedAddr = SocketAddr.toJSON(message.listenerMappedAddr);
    }
    if (message.destAddr !== undefined) {
      obj.destAddr = SocketAddr.toJSON(message.destAddr);
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.packetCountPerBatch !== 0) {
      obj.packetCountPerBatch = Math.round(message.packetCountPerBatch);
    }
    if (message.packetBatchCount !== 0) {
      obj.packetBatchCount = Math.round(message.packetBatchCount);
    }
    if (message.packetIntervalMs !== 0) {
      obj.packetIntervalMs = Math.round(message.packetIntervalMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketConeRequest>, I>>(base?: I): SendPunchPacketConeRequest {
    return SendPunchPacketConeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketConeRequest>, I>>(object: I): SendPunchPacketConeRequest {
    const message = createBaseSendPunchPacketConeRequest();
    message.listenerMappedAddr = (object.listenerMappedAddr !== undefined && object.listenerMappedAddr !== null)
      ? SocketAddr.fromPartial(object.listenerMappedAddr)
      : undefined;
    message.destAddr = (object.destAddr !== undefined && object.destAddr !== null)
      ? SocketAddr.fromPartial(object.destAddr)
      : undefined;
    message.transactionId = object.transactionId ?? 0;
    message.packetCountPerBatch = object.packetCountPerBatch ?? 0;
    message.packetBatchCount = object.packetBatchCount ?? 0;
    message.packetIntervalMs = object.packetIntervalMs ?? 0;
    return message;
  },
};

function createBaseSendPunchPacketHardSymRequest(): SendPunchPacketHardSymRequest {
  return { listenerMappedAddr: undefined, publicIps: [], transactionId: 0, portIndex: 0, round: 0 };
}

export const SendPunchPacketHardSymRequest: MessageFns<SendPunchPacketHardSymRequest> = {
  fromJSON(object: any): SendPunchPacketHardSymRequest {
    return {
      listenerMappedAddr: isSet(object.listenerMappedAddr) ? SocketAddr.fromJSON(object.listenerMappedAddr) : undefined,
      publicIps: globalThis.Array.isArray(object?.publicIps)
        ? object.publicIps.map((e: any) => Ipv4Addr.fromJSON(e))
        : [],
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      portIndex: isSet(object.portIndex) ? globalThis.Number(object.portIndex) : 0,
      round: isSet(object.round) ? globalThis.Number(object.round) : 0,
    };
  },

  toJSON(message: SendPunchPacketHardSymRequest): unknown {
    const obj: any = {};
    if (message.listenerMappedAddr !== undefined) {
      obj.listenerMappedAddr = SocketAddr.toJSON(message.listenerMappedAddr);
    }
    if (message.publicIps?.length) {
      obj.publicIps = message.publicIps.map((e) => Ipv4Addr.toJSON(e));
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.portIndex !== 0) {
      obj.portIndex = Math.round(message.portIndex);
    }
    if (message.round !== 0) {
      obj.round = Math.round(message.round);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketHardSymRequest>, I>>(base?: I): SendPunchPacketHardSymRequest {
    return SendPunchPacketHardSymRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketHardSymRequest>, I>>(
    object: I,
  ): SendPunchPacketHardSymRequest {
    const message = createBaseSendPunchPacketHardSymRequest();
    message.listenerMappedAddr = (object.listenerMappedAddr !== undefined && object.listenerMappedAddr !== null)
      ? SocketAddr.fromPartial(object.listenerMappedAddr)
      : undefined;
    message.publicIps = object.publicIps?.map((e) => Ipv4Addr.fromPartial(e)) || [];
    message.transactionId = object.transactionId ?? 0;
    message.portIndex = object.portIndex ?? 0;
    message.round = object.round ?? 0;
    return message;
  },
};

function createBaseSendPunchPacketHardSymResponse(): SendPunchPacketHardSymResponse {
  return { nextPortIndex: 0 };
}

export const SendPunchPacketHardSymResponse: MessageFns<SendPunchPacketHardSymResponse> = {
  fromJSON(object: any): SendPunchPacketHardSymResponse {
    return { nextPortIndex: isSet(object.nextPortIndex) ? globalThis.Number(object.nextPortIndex) : 0 };
  },

  toJSON(message: SendPunchPacketHardSymResponse): unknown {
    const obj: any = {};
    if (message.nextPortIndex !== 0) {
      obj.nextPortIndex = Math.round(message.nextPortIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketHardSymResponse>, I>>(base?: I): SendPunchPacketHardSymResponse {
    return SendPunchPacketHardSymResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketHardSymResponse>, I>>(
    object: I,
  ): SendPunchPacketHardSymResponse {
    const message = createBaseSendPunchPacketHardSymResponse();
    message.nextPortIndex = object.nextPortIndex ?? 0;
    return message;
  },
};

function createBaseSendPunchPacketEasySymRequest(): SendPunchPacketEasySymRequest {
  return {
    listenerMappedAddr: undefined,
    publicIps: [],
    transactionId: 0,
    basePortNum: 0,
    maxPortNum: 0,
    isIncremental: false,
  };
}

export const SendPunchPacketEasySymRequest: MessageFns<SendPunchPacketEasySymRequest> = {
  fromJSON(object: any): SendPunchPacketEasySymRequest {
    return {
      listenerMappedAddr: isSet(object.listenerMappedAddr) ? SocketAddr.fromJSON(object.listenerMappedAddr) : undefined,
      publicIps: globalThis.Array.isArray(object?.publicIps)
        ? object.publicIps.map((e: any) => Ipv4Addr.fromJSON(e))
        : [],
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      basePortNum: isSet(object.basePortNum) ? globalThis.Number(object.basePortNum) : 0,
      maxPortNum: isSet(object.maxPortNum) ? globalThis.Number(object.maxPortNum) : 0,
      isIncremental: isSet(object.isIncremental) ? globalThis.Boolean(object.isIncremental) : false,
    };
  },

  toJSON(message: SendPunchPacketEasySymRequest): unknown {
    const obj: any = {};
    if (message.listenerMappedAddr !== undefined) {
      obj.listenerMappedAddr = SocketAddr.toJSON(message.listenerMappedAddr);
    }
    if (message.publicIps?.length) {
      obj.publicIps = message.publicIps.map((e) => Ipv4Addr.toJSON(e));
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.basePortNum !== 0) {
      obj.basePortNum = Math.round(message.basePortNum);
    }
    if (message.maxPortNum !== 0) {
      obj.maxPortNum = Math.round(message.maxPortNum);
    }
    if (message.isIncremental !== false) {
      obj.isIncremental = message.isIncremental;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketEasySymRequest>, I>>(base?: I): SendPunchPacketEasySymRequest {
    return SendPunchPacketEasySymRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketEasySymRequest>, I>>(
    object: I,
  ): SendPunchPacketEasySymRequest {
    const message = createBaseSendPunchPacketEasySymRequest();
    message.listenerMappedAddr = (object.listenerMappedAddr !== undefined && object.listenerMappedAddr !== null)
      ? SocketAddr.fromPartial(object.listenerMappedAddr)
      : undefined;
    message.publicIps = object.publicIps?.map((e) => Ipv4Addr.fromPartial(e)) || [];
    message.transactionId = object.transactionId ?? 0;
    message.basePortNum = object.basePortNum ?? 0;
    message.maxPortNum = object.maxPortNum ?? 0;
    message.isIncremental = object.isIncremental ?? false;
    return message;
  },
};

function createBaseSendPunchPacketBothEasySymRequest(): SendPunchPacketBothEasySymRequest {
  return { udpSocketCount: 0, publicIp: undefined, transactionId: 0, dstPortNum: 0, waitTimeMs: 0 };
}

export const SendPunchPacketBothEasySymRequest: MessageFns<SendPunchPacketBothEasySymRequest> = {
  fromJSON(object: any): SendPunchPacketBothEasySymRequest {
    return {
      udpSocketCount: isSet(object.udpSocketCount) ? globalThis.Number(object.udpSocketCount) : 0,
      publicIp: isSet(object.publicIp) ? Ipv4Addr.fromJSON(object.publicIp) : undefined,
      transactionId: isSet(object.transactionId) ? globalThis.Number(object.transactionId) : 0,
      dstPortNum: isSet(object.dstPortNum) ? globalThis.Number(object.dstPortNum) : 0,
      waitTimeMs: isSet(object.waitTimeMs) ? globalThis.Number(object.waitTimeMs) : 0,
    };
  },

  toJSON(message: SendPunchPacketBothEasySymRequest): unknown {
    const obj: any = {};
    if (message.udpSocketCount !== 0) {
      obj.udpSocketCount = Math.round(message.udpSocketCount);
    }
    if (message.publicIp !== undefined) {
      obj.publicIp = Ipv4Addr.toJSON(message.publicIp);
    }
    if (message.transactionId !== 0) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.dstPortNum !== 0) {
      obj.dstPortNum = Math.round(message.dstPortNum);
    }
    if (message.waitTimeMs !== 0) {
      obj.waitTimeMs = Math.round(message.waitTimeMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketBothEasySymRequest>, I>>(
    base?: I,
  ): SendPunchPacketBothEasySymRequest {
    return SendPunchPacketBothEasySymRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketBothEasySymRequest>, I>>(
    object: I,
  ): SendPunchPacketBothEasySymRequest {
    const message = createBaseSendPunchPacketBothEasySymRequest();
    message.udpSocketCount = object.udpSocketCount ?? 0;
    message.publicIp = (object.publicIp !== undefined && object.publicIp !== null)
      ? Ipv4Addr.fromPartial(object.publicIp)
      : undefined;
    message.transactionId = object.transactionId ?? 0;
    message.dstPortNum = object.dstPortNum ?? 0;
    message.waitTimeMs = object.waitTimeMs ?? 0;
    return message;
  },
};

function createBaseSendPunchPacketBothEasySymResponse(): SendPunchPacketBothEasySymResponse {
  return { isBusy: false, baseMappedAddr: undefined };
}

export const SendPunchPacketBothEasySymResponse: MessageFns<SendPunchPacketBothEasySymResponse> = {
  fromJSON(object: any): SendPunchPacketBothEasySymResponse {
    return {
      isBusy: isSet(object.isBusy) ? globalThis.Boolean(object.isBusy) : false,
      baseMappedAddr: isSet(object.baseMappedAddr) ? SocketAddr.fromJSON(object.baseMappedAddr) : undefined,
    };
  },

  toJSON(message: SendPunchPacketBothEasySymResponse): unknown {
    const obj: any = {};
    if (message.isBusy !== false) {
      obj.isBusy = message.isBusy;
    }
    if (message.baseMappedAddr !== undefined) {
      obj.baseMappedAddr = SocketAddr.toJSON(message.baseMappedAddr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPunchPacketBothEasySymResponse>, I>>(
    base?: I,
  ): SendPunchPacketBothEasySymResponse {
    return SendPunchPacketBothEasySymResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPunchPacketBothEasySymResponse>, I>>(
    object: I,
  ): SendPunchPacketBothEasySymResponse {
    const message = createBaseSendPunchPacketBothEasySymResponse();
    message.isBusy = object.isBusy ?? false;
    message.baseMappedAddr = (object.baseMappedAddr !== undefined && object.baseMappedAddr !== null)
      ? SocketAddr.fromPartial(object.baseMappedAddr)
      : undefined;
    return message;
  },
};

function createBaseDirectConnectedPeerInfo(): DirectConnectedPeerInfo {
  return { latencyMs: 0 };
}

export const DirectConnectedPeerInfo: MessageFns<DirectConnectedPeerInfo> = {
  fromJSON(object: any): DirectConnectedPeerInfo {
    return { latencyMs: isSet(object.latencyMs) ? globalThis.Number(object.latencyMs) : 0 };
  },

  toJSON(message: DirectConnectedPeerInfo): unknown {
    const obj: any = {};
    if (message.latencyMs !== 0) {
      obj.latencyMs = Math.round(message.latencyMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DirectConnectedPeerInfo>, I>>(base?: I): DirectConnectedPeerInfo {
    return DirectConnectedPeerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DirectConnectedPeerInfo>, I>>(object: I): DirectConnectedPeerInfo {
    const message = createBaseDirectConnectedPeerInfo();
    message.latencyMs = object.latencyMs ?? 0;
    return message;
  },
};

function createBasePeerInfoForGlobalMap(): PeerInfoForGlobalMap {
  return { directPeers: {} };
}

export const PeerInfoForGlobalMap: MessageFns<PeerInfoForGlobalMap> = {
  fromJSON(object: any): PeerInfoForGlobalMap {
    return {
      directPeers: isObject(object.directPeers)
        ? Object.entries(object.directPeers).reduce<{ [key: number]: DirectConnectedPeerInfo }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = DirectConnectedPeerInfo.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: PeerInfoForGlobalMap): unknown {
    const obj: any = {};
    if (message.directPeers) {
      const entries = Object.entries(message.directPeers);
      if (entries.length > 0) {
        obj.directPeers = {};
        entries.forEach(([k, v]) => {
          obj.directPeers[k] = DirectConnectedPeerInfo.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerInfoForGlobalMap>, I>>(base?: I): PeerInfoForGlobalMap {
    return PeerInfoForGlobalMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerInfoForGlobalMap>, I>>(object: I): PeerInfoForGlobalMap {
    const message = createBasePeerInfoForGlobalMap();
    message.directPeers = Object.entries(object.directPeers ?? {}).reduce<{ [key: number]: DirectConnectedPeerInfo }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = DirectConnectedPeerInfo.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBasePeerInfoForGlobalMap_DirectPeersEntry(): PeerInfoForGlobalMap_DirectPeersEntry {
  return { key: 0, value: undefined };
}

export const PeerInfoForGlobalMap_DirectPeersEntry: MessageFns<PeerInfoForGlobalMap_DirectPeersEntry> = {
  fromJSON(object: any): PeerInfoForGlobalMap_DirectPeersEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? DirectConnectedPeerInfo.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: PeerInfoForGlobalMap_DirectPeersEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = DirectConnectedPeerInfo.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerInfoForGlobalMap_DirectPeersEntry>, I>>(
    base?: I,
  ): PeerInfoForGlobalMap_DirectPeersEntry {
    return PeerInfoForGlobalMap_DirectPeersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerInfoForGlobalMap_DirectPeersEntry>, I>>(
    object: I,
  ): PeerInfoForGlobalMap_DirectPeersEntry {
    const message = createBasePeerInfoForGlobalMap_DirectPeersEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? DirectConnectedPeerInfo.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseReportPeersRequest(): ReportPeersRequest {
  return { myPeerId: 0, peerInfos: undefined };
}

export const ReportPeersRequest: MessageFns<ReportPeersRequest> = {
  fromJSON(object: any): ReportPeersRequest {
    return {
      myPeerId: isSet(object.myPeerId) ? globalThis.Number(object.myPeerId) : 0,
      peerInfos: isSet(object.peerInfos) ? PeerInfoForGlobalMap.fromJSON(object.peerInfos) : undefined,
    };
  },

  toJSON(message: ReportPeersRequest): unknown {
    const obj: any = {};
    if (message.myPeerId !== 0) {
      obj.myPeerId = Math.round(message.myPeerId);
    }
    if (message.peerInfos !== undefined) {
      obj.peerInfos = PeerInfoForGlobalMap.toJSON(message.peerInfos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportPeersRequest>, I>>(base?: I): ReportPeersRequest {
    return ReportPeersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportPeersRequest>, I>>(object: I): ReportPeersRequest {
    const message = createBaseReportPeersRequest();
    message.myPeerId = object.myPeerId ?? 0;
    message.peerInfos = (object.peerInfos !== undefined && object.peerInfos !== null)
      ? PeerInfoForGlobalMap.fromPartial(object.peerInfos)
      : undefined;
    return message;
  },
};

function createBaseReportPeersResponse(): ReportPeersResponse {
  return {};
}

export const ReportPeersResponse: MessageFns<ReportPeersResponse> = {
  fromJSON(_: any): ReportPeersResponse {
    return {};
  },

  toJSON(_: ReportPeersResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportPeersResponse>, I>>(base?: I): ReportPeersResponse {
    return ReportPeersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportPeersResponse>, I>>(_: I): ReportPeersResponse {
    const message = createBaseReportPeersResponse();
    return message;
  },
};

function createBaseGlobalPeerMap(): GlobalPeerMap {
  return { map: {} };
}

export const GlobalPeerMap: MessageFns<GlobalPeerMap> = {
  fromJSON(object: any): GlobalPeerMap {
    return {
      map: isObject(object.map)
        ? Object.entries(object.map).reduce<{ [key: number]: PeerInfoForGlobalMap }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = PeerInfoForGlobalMap.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: GlobalPeerMap): unknown {
    const obj: any = {};
    if (message.map) {
      const entries = Object.entries(message.map);
      if (entries.length > 0) {
        obj.map = {};
        entries.forEach(([k, v]) => {
          obj.map[k] = PeerInfoForGlobalMap.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GlobalPeerMap>, I>>(base?: I): GlobalPeerMap {
    return GlobalPeerMap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GlobalPeerMap>, I>>(object: I): GlobalPeerMap {
    const message = createBaseGlobalPeerMap();
    message.map = Object.entries(object.map ?? {}).reduce<{ [key: number]: PeerInfoForGlobalMap }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = PeerInfoForGlobalMap.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseGlobalPeerMap_MapEntry(): GlobalPeerMap_MapEntry {
  return { key: 0, value: undefined };
}

export const GlobalPeerMap_MapEntry: MessageFns<GlobalPeerMap_MapEntry> = {
  fromJSON(object: any): GlobalPeerMap_MapEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? PeerInfoForGlobalMap.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: GlobalPeerMap_MapEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = PeerInfoForGlobalMap.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GlobalPeerMap_MapEntry>, I>>(base?: I): GlobalPeerMap_MapEntry {
    return GlobalPeerMap_MapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GlobalPeerMap_MapEntry>, I>>(object: I): GlobalPeerMap_MapEntry {
    const message = createBaseGlobalPeerMap_MapEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? PeerInfoForGlobalMap.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseGetGlobalPeerMapRequest(): GetGlobalPeerMapRequest {
  return { digest: 0 };
}

export const GetGlobalPeerMapRequest: MessageFns<GetGlobalPeerMapRequest> = {
  fromJSON(object: any): GetGlobalPeerMapRequest {
    return { digest: isSet(object.digest) ? globalThis.Number(object.digest) : 0 };
  },

  toJSON(message: GetGlobalPeerMapRequest): unknown {
    const obj: any = {};
    if (message.digest !== 0) {
      obj.digest = Math.round(message.digest);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGlobalPeerMapRequest>, I>>(base?: I): GetGlobalPeerMapRequest {
    return GetGlobalPeerMapRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGlobalPeerMapRequest>, I>>(object: I): GetGlobalPeerMapRequest {
    const message = createBaseGetGlobalPeerMapRequest();
    message.digest = object.digest ?? 0;
    return message;
  },
};

function createBaseGetGlobalPeerMapResponse(): GetGlobalPeerMapResponse {
  return { globalPeerMap: {}, digest: undefined };
}

export const GetGlobalPeerMapResponse: MessageFns<GetGlobalPeerMapResponse> = {
  fromJSON(object: any): GetGlobalPeerMapResponse {
    return {
      globalPeerMap: isObject(object.globalPeerMap)
        ? Object.entries(object.globalPeerMap).reduce<{ [key: number]: PeerInfoForGlobalMap }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = PeerInfoForGlobalMap.fromJSON(value);
          return acc;
        }, {})
        : {},
      digest: isSet(object.digest) ? globalThis.Number(object.digest) : undefined,
    };
  },

  toJSON(message: GetGlobalPeerMapResponse): unknown {
    const obj: any = {};
    if (message.globalPeerMap) {
      const entries = Object.entries(message.globalPeerMap);
      if (entries.length > 0) {
        obj.globalPeerMap = {};
        entries.forEach(([k, v]) => {
          obj.globalPeerMap[k] = PeerInfoForGlobalMap.toJSON(v);
        });
      }
    }
    if (message.digest !== undefined) {
      obj.digest = Math.round(message.digest);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGlobalPeerMapResponse>, I>>(base?: I): GetGlobalPeerMapResponse {
    return GetGlobalPeerMapResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGlobalPeerMapResponse>, I>>(object: I): GetGlobalPeerMapResponse {
    const message = createBaseGetGlobalPeerMapResponse();
    message.globalPeerMap = Object.entries(object.globalPeerMap ?? {}).reduce<{ [key: number]: PeerInfoForGlobalMap }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = PeerInfoForGlobalMap.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.digest = object.digest ?? undefined;
    return message;
  },
};

function createBaseGetGlobalPeerMapResponse_GlobalPeerMapEntry(): GetGlobalPeerMapResponse_GlobalPeerMapEntry {
  return { key: 0, value: undefined };
}

export const GetGlobalPeerMapResponse_GlobalPeerMapEntry: MessageFns<GetGlobalPeerMapResponse_GlobalPeerMapEntry> = {
  fromJSON(object: any): GetGlobalPeerMapResponse_GlobalPeerMapEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? PeerInfoForGlobalMap.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: GetGlobalPeerMapResponse_GlobalPeerMapEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = PeerInfoForGlobalMap.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGlobalPeerMapResponse_GlobalPeerMapEntry>, I>>(
    base?: I,
  ): GetGlobalPeerMapResponse_GlobalPeerMapEntry {
    return GetGlobalPeerMapResponse_GlobalPeerMapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGlobalPeerMapResponse_GlobalPeerMapEntry>, I>>(
    object: I,
  ): GetGlobalPeerMapResponse_GlobalPeerMapEntry {
    const message = createBaseGetGlobalPeerMapResponse_GlobalPeerMapEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? PeerInfoForGlobalMap.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseHandshakeRequest(): HandshakeRequest {
  return { magic: 0, myPeerId: 0, version: 0, features: [], networkName: "", networkSecretDigrest: new Uint8Array(0) };
}

export const HandshakeRequest: MessageFns<HandshakeRequest> = {
  fromJSON(object: any): HandshakeRequest {
    return {
      magic: isSet(object.magic) ? globalThis.Number(object.magic) : 0,
      myPeerId: isSet(object.myPeerId) ? globalThis.Number(object.myPeerId) : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      features: globalThis.Array.isArray(object?.features) ? object.features.map((e: any) => globalThis.String(e)) : [],
      networkName: isSet(object.networkName) ? globalThis.String(object.networkName) : "",
      networkSecretDigrest: isSet(object.networkSecretDigrest)
        ? bytesFromBase64(object.networkSecretDigrest)
        : new Uint8Array(0),
    };
  },

  toJSON(message: HandshakeRequest): unknown {
    const obj: any = {};
    if (message.magic !== 0) {
      obj.magic = Math.round(message.magic);
    }
    if (message.myPeerId !== 0) {
      obj.myPeerId = Math.round(message.myPeerId);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.features?.length) {
      obj.features = message.features;
    }
    if (message.networkName !== "") {
      obj.networkName = message.networkName;
    }
    if (message.networkSecretDigrest.length !== 0) {
      obj.networkSecretDigrest = base64FromBytes(message.networkSecretDigrest);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandshakeRequest>, I>>(base?: I): HandshakeRequest {
    return HandshakeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandshakeRequest>, I>>(object: I): HandshakeRequest {
    const message = createBaseHandshakeRequest();
    message.magic = object.magic ?? 0;
    message.myPeerId = object.myPeerId ?? 0;
    message.version = object.version ?? 0;
    message.features = object.features?.map((e) => e) || [];
    message.networkName = object.networkName ?? "";
    message.networkSecretDigrest = object.networkSecretDigrest ?? new Uint8Array(0);
    return message;
  },
};

function createBaseKcpConnData(): KcpConnData {
  return { src: undefined, dst: undefined };
}

export const KcpConnData: MessageFns<KcpConnData> = {
  fromJSON(object: any): KcpConnData {
    return {
      src: isSet(object.src) ? SocketAddr.fromJSON(object.src) : undefined,
      dst: isSet(object.dst) ? SocketAddr.fromJSON(object.dst) : undefined,
    };
  },

  toJSON(message: KcpConnData): unknown {
    const obj: any = {};
    if (message.src !== undefined) {
      obj.src = SocketAddr.toJSON(message.src);
    }
    if (message.dst !== undefined) {
      obj.dst = SocketAddr.toJSON(message.dst);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KcpConnData>, I>>(base?: I): KcpConnData {
    return KcpConnData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KcpConnData>, I>>(object: I): KcpConnData {
    const message = createBaseKcpConnData();
    message.src = (object.src !== undefined && object.src !== null) ? SocketAddr.fromPartial(object.src) : undefined;
    message.dst = (object.dst !== undefined && object.dst !== null) ? SocketAddr.fromPartial(object.dst) : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
