/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface KeyValuePair {
  key: string
  value: string
}

export declare function collectNetworkInfos(): Array<KeyValuePair>

export declare function collectRunningNetwork(): Array<string>

export declare function hilogGlobalOptions(domain: number, tag: string): void

export declare function initPanicHook(): void

export declare function initTracingSubscriber(): void

export declare function isRunningNetwork(instId: string): boolean

export declare function parseConfig(cfgStr: string): boolean

export declare function runNetworkInstance(cfgStr: string): boolean

export declare function setTunFd(instId: string, fd: number): boolean

export declare function stopNetworkInstance(instNames: Array<string>): void

